### ISSUE TITLE
text dans le mail des devis

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#1]
lorsque qu'on entre dans un scénario qui implique le form de contact , le texte que tu as mis n'est pas le bon

Maison de 90 M2 situé sur la commune de CHANTILLY (60500).
Les diagnostics obligatoire avant une vente sont les suivant:
• DPE
• Gaz
• Amiante
• Electrique
• ERNMT (Offert)

à remplacer par

"
Maison de 90 M2 située sur la commune de CHANTILLY (60500).
Pour les diagnostics obligatoires avant une vente suivant:
• DPE
• Gaz
• Amiante
• Electrique
"

et attention si c'est un appartement , ne pas mettre de e à la fin du mot situé

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
merkrrrri :)
