### ISSUE TITLE
Devis : faute d'orthographe

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#101]
si tu va sur la page de devis , tu regarderas le titre : 

Devis - Disagnostic immobilier

le mot diagnostic contient une faute à corriger rapidement stp : il y a un S entre le i et le a

Merci fiston

**Comment by corentin-begne** [comment]
C'est corrigé, il y avait la même faute sur le formulaire de résulta "Le tarif que nous proposons pour ces ... disagnostics ..." c'est corrigé aussi et en prod.

**Comment by kapeco** [comment]
Merci mon lapinkrrr
