### ISSUE TITLE
Ordre de mission

### ISSUE THREAD

**Issue by corentin-begne** [corentin-begne/kap#11]
@kapeco 
Le formulaire a été remis en place amélioré dans la liste des liens lorsque l'on est loggé en tant que diagnostiqueur ou agence, il est présent à l'url kapeco/mission.  
Par contre j'aurais besoin de précision sur l'utilisation des data par rapport à ton doc : 
```
Envoyer un push sur smartphone (exemple de code http://www.kapeco.com/push.php  l’appel se fait sur la page d’accueil)
```
ça ok je vais voir comment t'as fait.

```
Envois d’un mail d’alerte aux diagnostiqueurs liés à l’agence qui à fait la demande d’ordre de mission
```
ça je comprends pas parce que si c'est une agence qui fait la demande, comment je sais à quelle agence est rattaché le diagnostiqueur vu qu'il est déjà rattaché à sa propre agence ?

```
Créer une nouvelle ligne dans une page dédiée aux demandes d’ordre de mission en attente.
Cette page est accessible uniquement aux diagnostiqueurs liés à l’agence.
Sur cette page on doit y retrouver les informations suivantes :
NOM AGENCE | VILLE DU BIEN | DATE-HEURE INTEVENTION SOUHAITE | LISTE DIAG A FAIRE
Si on clic sur la ligne ca affiche l’ensemble des infos qui ont été rentrées dans le formulaire.
Ensuite le diagnostiqueur peut soit valider directement ou modifier les date d’intervention et valider.
Une fois validé :
la ligne apparait avec une petite image de check verte en début de ligne
enregistre l’ensemble dans le google agenda du diagnostiqueur qui a validé
envois un mail a l’agence lui indiquant que ça a été validé
```
Faut voir pour le google agenda mais ça me parait pas trop compliqué à part qu'il pourrait y avoir des problème de concurrence au niveau de la prise de rendez vous, ça risque d'être long à mettre en place

```
(Petite parenthèse : donc si ce n’est pas déjà fait, lorsqu’on crée une agence immobilière, on doit la lier à un ou plusieurs diagnostiqueurs)
```
ça non plus je comprends pas, ça va surement avec ma remarque du dessus, de ce que j'ai compris une agence est soit une agence immobilière soit une agence diagnostiqueur et un user est rattaché à une agence donc logiquement les users client sont rattachés aux agences immobilière et les users diagnostiqueur sont rattachés aux agences diagnotiqueur.

**Comment by kapeco** [comment]
Oui c'est ça mais disons aussi qu'une agence immobilière fait partie du portefeuille d'une agence Kapeco .
Alors prenons un exemple simple (et à la volée j'en profite pour affiner ce que je disais plus haut ) : 
1er phase :
- création de l'agence de diagnostic "Kapeco Oise "
- création de l'utilisateur "Franky"
- on le met dans le groupe "diagnostiquent"
- on l'attache à l'avance de diagnostic "Kapeco Oise"
(Donc la j'existe et je suis bien dans mon agence à moi )
2ème phase :
- création de l'agence Immobiliere "Orpi chantilly"
- création de l'utilisateur Bernard 
- assignation de Bernard a l'agence Orpi chantilly 
- on met l'agence "Orpi chantilly" dans le portefeuille de l'agence de diagnostic "Kapeco Oise "

( maintenant l'agence de diagnostic et Orpi chantilly sont donc liées )

3ème phase :
- bernard de l'agence "Orpi chantilly" crée un ordre de mission 
- le Push et le mail sont envoyés aux diagnostiqueur de l'agence de diagnostic "Kapeco Oise" et dans ce cas pour le moment que a Franky 

4ème phase :

- Lorsque je me connecte sur le site en tant que diagnostiqueur dans le liens "ordre de mission " j'y vois la liste des ordre de mission en attente 
- il me reste donc plus qu'à valider ou changer la date pour qu'ensuite ça l'enregistre dans le Google agenda de l'agence de diagnostic "Kapeco Oise"
- envois d'une notification mail à Bernard de l'agence Orpi chantilly 
- sur le site : mise a jour de l'état de la demande de l'ordre de mission : "planifiée"

**Comment by corentin-begne** [comment]
ok c'est déjà plus clair.
ça veut dire que quand on crée une agence il faut savoir si c'est une agence immobilière ou une agence kapeco et si c'est une agence immobilière il faut pouvoir la rattacher à des agences kapeco. Est qu'une agence kapeco peut être rattachée à plusieurs agence immobilière ? Dans le process, je comprends pas comment ça se passe si c'est un diagnostiqueur qui crée l'ordre de mission.

**Comment by kapeco** [comment]
oui c'est ça.
Changeons les termes pour être plus clair : agence de diagnostic , deviens "franchise"
donc on ajoute une franchise kapeco à laquelle on rattache une ou plusieurs agence immobilière.
dans le process ce sont donc les agences qui crées un ordre de mission pour un franchise

**Comment by corentin-begne** [comment]
J'ai bien avancé. Donc, j'ai ajouté un type aux agences (immobilière ou franchise), tu peux associer des agences entre elles, une franchise peut être liée à une ou plusieurs immobilière et inversement, tu as un nouveau lien dans l'admin "Agences Franchise", la colonne category et filtré sur les agences immobilière et la colonne franchise sur les franchises. J'ai changé aussi les liens d'accès, Ordre de mission en tant que diagnostiqueur va lister les ODM en attente pour son agence et en tant qu'Agence permet d'accéder au formulaire de création d'ODM. Je t'ai créé un compte agence pour que tu puisse y accéder : 
franckyAgence
123456
Actuellement quand tu valide ça enregistre en bdd et je récup la liste des diagnostiqueurs rattaché aux franchises associées à l'agence du créateur de l'ODM.
Il me reste a envoyer le push et le mail pour cette partie mais il me faudrait le formatage que tu veux pour les deux.

**Comment by corentin-begne** [comment]
pareil pour le listing côté diagnotiqueur il me faudrait le design

**Comment by kapeco** [comment]
Vous pouvez répéter la question ?

**Comment by corentin-begne** [comment]
1. Il me faut le formatage au niveau des data pour le push et le mail que je dois envoyer, pour le push je connais pas la syntaxe et pour le mail la mise en forme HTML des données récupérées dans le formulaire ou je sais pas ce que tu veux que les diagnostiqueurs reçoivent.
2. Pour le push sur le site de prod j'ai ça : 
```
curl_setopt_array($ch = curl_init(), array(
  CURLOPT_URL => "https://api.pushover.net/1/messages.json",
  CURLOPT_POSTFIELDS => array(
  "token" => "agE61sk9QjTPu9qMdoAcomKVKF9fGj",
  "user" => "ufi7vxXGamMYZiAMwwgkZDnF79aVqB",
  "message" => "$message",
)));
curl_exec($ch);
curl_close($ch);
```
c'est configuré sur un user qui doit être toi j'imagine mais comment je fais pour l'envoyer à nos users ?
3. Il me faut le design de l'interface que tu veux que j'affiche aux diagnostiqueurs concernant les ODM en attente

**Comment by kapeco** [comment]
Ok je fais ça ce week-end

**Comment by kapeco** [comment]
Le formatage est simple , on reprend juste les questions mise en phrase non interrogatives , avec au bout les réponses

Concernant le push c'est effectifement ça le code , 
concernant les users , ce sont les diagnostiqueurs de la franchise qui reçoivent le mail et le push
Mais du coup il faut ajouter je pense dans leur profil la possibilité de cocher ou non push et mail

**Comment by corentin-begne** [comment]
je peux mettre ces deux infos supplémentaires dans les infos user mais comment je fais pour générer un token user push pour chaque user ?

**Comment by kapeco** [comment]
Ça ce sont les user qui doivent le renseigner du coup .
C'était une bonne question 😉
Donc faut ajouter un champs "token " dans le profil
Car lorsqu'on s'inscrit au service on a un token d'attribuer

**Comment by kapeco** [comment]
Idem pour le user qu'il y a dans le code

**Comment by kapeco** [comment]
Tu peux test en regardants l'application "pushover "

**Comment by corentin-begne** [comment]
Donc il faut une interface de setting user pour qu'il puisse choisir si il veut ou non les push et alertes mail et si il coche push il doit renseigner le token et le user.

**Comment by corentin-begne** [comment]
j'ai ajouté alert email et push ainsi que push token et user dans la table user. alert mail et a default sur 1 et push à 0 avec les valeur de push à NULL. Tout le fonctionnel est fait, tu as du recevoir un mail d'un ordre de mission que j'ai créé avec mon comte agence. Je vais faire l'interface setting pour pouvoir configurer le push et voir comment ça rend (je pourrais pas te dire faudra que tu tests). Pour les tests j'ai enlevé le réinit de la form après la création de l'ODM.

**Comment by kapeco** [comment]
yes j'ai vu ça c'est nickel

Du coup le template est un peut lourd si on reprend chaque désignation des champs, je vais te mettre au dessous:

Type de mission : Vente
Type de bien : Appartement
Annee de construction : Entre 1949 et 1997
Adresse du bien : 3 avenues 60500 Chantilly
Numero de lot : 4
Étages : 2
Porte : 3
Autre : zeze

Nom du propriétaire : ferfe
Adresse du propriétaire : 43 rue de la touffe 59000 Lilles
Email du propriétaire : test@test.com
Tél du propriétaire : 0320212425

Missions:
- Carrez
- Electricite
- Termites
- Ernt
- Etat-des-lieux

Date d'intervention souhaitee : 2015-05-04 02:38
Clef a l'agence ? oui
RDV avec le client sur le lieu ? oui
Règlement : Notaire

Adresse du notaire : place de l'arnaque 57000 Nancy
Email du notaire : test@test.com
Tél du notaire : 0320323536

**Comment by kapeco** [comment]
PEut etre ajouter le nom du notaire dans l'ODM

**Comment by corentin-begne** [comment]
j'ai modifié et j'ai ajouté le nom du notaire. Avec l'interface paramètre user tu peux config ton compte push pour voir ce que ça rend.

**Comment by kapeco** [comment]
![image](https://cloud.githubusercontent.com/assets/11981295/7462610/27394d34-f2b3-11e4-9167-f845f244fd88.jpg)

**Comment by corentin-begne** [comment]
j'ai modifié dis moi si c'est bon

**Comment by corentin-begne** [comment]
j'ai également ajouté un loader pour toute les requêtes ajax, tu me diras si tu veux le changer.

**Comment by kapeco** [comment]
Impeccable pour le moment 😊

**Comment by corentin-begne** [comment]
j'ai refais deux tests dis moi si tu les as reçus

**Comment by kapeco** [comment]
Oui bien reçu par mail et par push 
Les deux impeccable

**Comment by kapeco** [comment]
j'ai fait un ODM aujourd'hui et je n'ai rien recu ...
je n'ai pas pu vérifier dans mon profil la config puisque le liens a disparu

**Comment by corentin-begne** [comment]
j'ai reçu un devis ce matin, je viens de test et j'ai bien reçu l'odm. Le
lien paramètre n'est présent que quand t loggé en tant que diagnostiqueur
les agences/clients ne reçoivent pas d'alerte.

**Comment by kapeco** [comment]
Impeccable la je viens de recevoir 

Il faudrait que le liens apparaissent aussi quand je suis logué en admin , bien que je pense que mon compte soit admin et diagnostiqueur !

**Comment by corentin-begne** [comment]
tu devrais le voir pourtant, seulement quand t'es loggé en tant qu'agence/client que tu les vois pas, normalement si t'as que les droits admin/super admin tu ne vois aucun lien.

**Comment by kapeco** [comment]
Admin et super admin doivent tout voir , c'est un minimum

**Comment by corentin-begne** [comment]
il faut qu'on revoit les permission alors.
- SuperAdmin : 
  - accès bakend
- Admin : 
  - édtion articles/catégories frontend
- Diagnotiqueur : 
   - lister/editer ODM
   - recherche agence
   - créer/lister/éditer diagnostiques
   - paramètres alerte mail et push
- Agence : 
  - créer ODM
  - lister diagnostiques
- Client : 
  - lister diagnostiques

Si ces droits sont corrects, tu vois bien que les superadmin et admin ne peuvent avoir accès à rien, à la limite paramètre mais ça n'a pas de sens car ils ne recevront pas d'alertes, seul les diagnostiqueurs en reçoivent.

**Comment by kapeco** [comment]
C'est exactement ça 
Mais j'ai du mal m'exprimer a un moment .
Tu as bien lister la hiérarchie mais si tu regarde bien en partant du bas , agence a les même droits que client plus odm et en remontant c'est la même chose 
Ça reprend les droits qu'il y a au dessous et ça en ajoute
Donc forcément super admin devrai avoir tout les droits

**Comment by corentin-begne** [comment]
le problème pour moi c'est que les droits agence/client et diagnostiqueur ne peuvent pas se croiser et aussi pour moi un admin peut simplement être admin, il n'est pas forcément un user.

**Comment by kapeco** [comment]
Ouais mais je ne peux pas me deloguer et reloguer a chaque fois que je veux faire quelque chose

**Comment by kapeco** [comment]
Mais en me lattant dans plusieurs groupes ça devrait fonctionner ?

**Comment by corentin-begne** [comment]
bah oui comme là, tu es superadmin, admin et diagnostiqueur comme moi, tu dois voir tous les liens. Avec ton compte agence par contre tu ne dois voir que deux lien pour créer les ordres de mission et lister les diagnostiques.

**Comment by corentin-begne** [comment]
Sinon, j'ai bien avancé sur le listing des ODM. Quand tu es loggé en tant que diagnostiqueur, le lien Ordre de mission, actuellement ça liste tous les ordres de mission auquel l'agence du diagnostiqueur est rattaché. ça classe de en attente, nom agence, date de création desc. Si tu cliques sur En attente, il te demande si tu veux prendre en charge l'ODM, il y a une validation sur la date puis ça envoie en bdd. Actuellement ça ne fait que enregistrer en bdd, pour le mail aux agence il me faudrait le contenu et pour le google agenda il faudrait voir comment faire pour avoir les permissions, peut être ajouter dnas les paramètres faut que je regarde la doc encore. Je me mets sur le détail dés que possible qui va afficher le contenu du mail de création en plein sur un fond noir avec le nom du diagnostiqueur qui l'a pris en charge si c'est réservé. Dis moi pour réservé et en attente si tu veux des icône et si je dois virer la colonne de droite comme pour les diagnostiques.

**Comment by corentin-begne** [comment]
@kapeco j'ai terminé le détail, quand tu clique sur la ligne d'un ODM (sauf sur la case en attente) ça affiche le détails en plein écran avec la personne qui l'a pris en charge avec le nom de son agence si c'est le cas, si tu cliques n'importe où ça se ferme.  Pour moi c'est terminé sur cette partie, j'attends ton retour pour les finalisations.

**Comment by kapeco** [comment]
Ok je suis en train de Check 
Retire la colonne de droite aussi 
les agences doivent voir aussi la liste de leur demande d'odm en attente et celles qui sont planifiées et confirmées par le diagnostiqueur 
Dans le formulaire de l'odm, concernant la porte : alphanumérique et non numérique

**Comment by kapeco** [comment]
L'odm une fois valider , dot rester édita le par le diagnostiqueur, on sait jamais si on se trompe ou si on doit décaler 
Et quand je veux valider la date je n'ai qu'un calendrier qui apparaît et disparaît tout de suite , donc c'est validé sans date ... :(

**Comment by corentin-begne** [comment]
ok je vais modifier ça, normalement si tu cliques sur l'input le calendrier réapparait

**Comment by corentin-begne** [comment]
après il faut perdre le focus de l'input et le reprendre pour qu'il réapparaisse

**Comment by kapeco** [comment]
Et faut qu'on puisse éditer le contenu d'un odm a tout moment car souvent les agences font des conneries

**Comment by kapeco** [comment]
Je viens de test en perdant le focus mais idem ça apparaît une demi seconde avant de disparaître à nouveau 
J'utilise beaucoup safari ça r je travaille beaucoup depuis mon tel

**Comment by corentin-begne** [comment]
éditer tout le contenu ça va être chaud quand même faut que je retravaille pas mal dessus pour parce qu'il faut que je te recale tout le formulaire de l'odm avec les valeurs affectées :/
pour safari dsl je peux vraiment pas test j'ai aucun matos de la sale pomme et j'ai essayé de l'installer sous windows mais il ne fonctionne pas

**Comment by kapeco** [comment]
Y a safari pour Windows qui s'installe facilement pourtant ... Tu n'as pas réussi ??? Étrange
Je testerai demain sur le Pc voir si j'ai les même erreurs

**Comment by corentin-begne** [comment]
si j'ai réussi à l'installer mais j'ai page blanche pas d'erreur je peux rien faire

**Comment by kapeco** [comment]
;(

**Comment by kapeco** [comment]
bon je n'arrive pas à accéder au site : TO

**Comment by corentin-begne** [comment]
je le relance ce midi dsl.

**Comment by corentin-begne** [comment]
c'est fait

**Comment by corentin-begne** [comment]
c'est terminé pour la partie agence, il me reste à faire l'édition sur la partie diag, je fais ça ce soir. Donc les agences peuvent créer, afficher et liste les ODM, les diag pourront en plus réserver et éditer.

**Comment by kapeco** [comment]
impec j'attend de voir ça

petite remarque au passage , j'ai voulu "réserver" mais impossible le calendrier est trop en bas
![2015-05-21 19_16_36-](https://cloud.githubusercontent.com/assets/11981295/7754609/451717c6-ffee-11e4-9bee-b69a3359a0d2.png)

**Comment by corentin-begne** [comment]
tu peux scroller ... c'est parce que c'est le datetimepicker, il est fait pour être associé à une input sinon je dois le refaire. Ce soir ça devrait être bon pour le reste jte dis quoi !

**Comment by corentin-begne** [comment]
ah non tu peux pas scroller .. je vais voir ça

**Comment by kapeco** [comment]
merci fiston :)

**Comment by kapeco** [comment]
Par contre ajoute aussi les droits d'édition pour les agences tant que ce n'est pas réservé par un diagnostiqueur.
Et lorsqu'on clic sur une ligne pour voir le détail ça serait bien que ça ne soit pas tout noir
que ça soit plutôt dans les tons clairs et dans un cadre pas sur tout l'écran

**Comment by corentin-begne** [comment]
je vais voir pour modifier les droits, je voulais savoir aussi si quand un odm et déjà réservé est ce qu'il peut être réservé par un autre diag ? est ce qu'un autre diag peut éditer ? car il peut éditer la date dans le formulaire. Pour l'affichage du détail, je vais voir pour ajouter ton cadre mais je pense que ça sera carrément moins lisible. Je dois le mettre pour tous les affichage plein écran que j'ai mis en fond noir  ?

**Comment by kapeco** [comment]
oui pas de fond noir
oui aussi un autre diag peut éditer et modifier,

**Comment by corentin-begne** [comment]
dans ce cas faut voir pour le google agenda et le mail à l'agence ce que je dois faire, je dois revalider ? et pouur l'ancien diag je dois lui supprimer sa réservation dans son google agenda ? ça devient bizarre, une agence pourra recevoir plusieurs réservation et des diag pourront écraser les réservation des autres ça va être le carnage.

**Comment by corentin-begne** [comment]
j'ai mis en place le fond blanc avec les bords sur le detail des odm.

**Comment by corentin-begne** [comment]
pour l'édition des odm par les agences, je trouve ça anormal car sinon il va y avoir des incohérences avec les mails reçu par les diags.

**Comment by corentin-begne** [comment]
je ne peux pas mettre de scroll pour le datetimepicker car les popup sont en position fixed pour ne pas pouvoir les zapper et passer en dehors.

**Comment by kapeco** [comment]
Tu as raison concernant Google agenda 
Une fois validé il faudrait genre un t'aimer de 2 mn pour avoir le temps de modifier si erreur et ensuite c'est bloqué et validé de chez validé 
Du coup idem pour les agences , elles on 5 mn si elles veulent modifier

**Comment by corentin-begne** [comment]
c'est compliqué ton affaire, ça va faire des incohérences dans les interfaces, à l'init ça sera dans un état mais quand il fera l'action il n'aura pas forcément le droit il faudra que je mette plein de check partout et du coup je dois envoyer les alertes que à la fin du timer ce qui n'est pas possible ou il faut faire tourner des crons :////

**Comment by kapeco** [comment]
bon alors une double validation , genre il fait "valider" puis ça lui redemande sir il est sur car après ça sera non modifiable avec deux options "revenir à l'ODM" - "Valider définitivement"

**Comment by corentin-begne** [comment]
j'ai mis en place la double validation. Donc pour le diag, il a le droit de modifier l'ODM entièrement tant qu'il n'est pas réservé et quand il réserve ça enrgistre dans google agenda et ça envoie un mail à l'agence (il faudrait le contenu stp). Ensuite, aucun diag ne peut modifier cet ODM ni le réserver de nouveau. Je suis en train de voir pour google agenda mais pour test je dois avoir une url valide donc j'ai mis en place la preprod sur mon mutu, je suis en train de test.

**Comment by corentin-begne** [comment]
j'ai ajouté dans les paramètres user un bouton "lier avec google agenda" qui permet de récupérer le token d'accès associé à l'application et l'enregistre en bdd sur validation et refresh la page, le bouton n'est visible que si l'user n'a pas de token. Je vais voir maintenant comment faire l'ajout sur le google agenda.

**Comment by corentin-begne** [comment]
j'ai mis en place la réservation sur google agenda, tu peux tester en préprod. En fait ça crée un event, donc j'ai du mettre une date de fin, j'ai mis +2h tu me dis si tu veux changer. Pareil pour le titre et la description. Il me reste a terminer l'édition et mettre l'envoie de mail agence et donc je vais bloquer l'édition et la réservation une fois que l'odm est réservé car on ne peut pas supprimer d'event apparemment.

**Comment by corentin-begne** [comment]
@kapeco 
J'ai terminé l'édition et la suppression, c'est en preprod. J'ai modifié pour que quand tu réserve en retour ça t'ouvre l'event dans un nouvel onglet. Il me manque plus que le mail à l'agence pour que cette partie soit terminé.

**Comment by kapeco** [comment]
Merci mon coco

plusieurs chose

lorsque je veux reserver l'odm : 

1) si je clic j'ai la premiere petite fenetre qui s'ouvre , si je valide en cliquant sur OK , gros bug cf photo 
![2015-06-02 19_00_41-ordre de mission](https://cloud.githubusercontent.com/assets/11981295/7941793/fa4ee000-0959-11e5-8af2-3819a084d27f.png)

2) si je veux changer la date , ça ouvre le time picker , mais je ne peux pas valider , cf deuxieme photo
![2015-06-02 19_03_40-](https://cloud.githubusercontent.com/assets/11981295/7941827/2599fd30-095a-11e5-949f-5efb431f515d.png)

3) si je veux modifier l'odm , ca ouvre bien un popup , mais impossible de valider , cf photo
![2015-06-02 19_04_44-](https://cloud.githubusercontent.com/assets/11981295/7941860/5c072fd2-095a-11e5-9570-a6008c95051e.png)

**Comment by corentin-begne** [comment]
1) c'est corrigé.  
2) je peux rien faire il faut avoir un écran assez grand sinon je dois refaire le plugin.  
3) sur chrome j'ai une scrollbar.  
4) j'ai ajouté la possibilité de délier le compte  
Le tout est en preprod

**Comment by kapeco** [comment]
1) merci

2) c'est problématique car on a tous le même écran 

3) on a tous Firefox

4) merci

**Comment by corentin-begne** [comment]
2) sur mon écran ça passe, je vais voir ce que je peux faire mais j'ai déjà perdu bcp de temps dessus.
3) oui mais on a dit qu'on ferait une passe sur ff et ie à la fin et que tu devais test sur chrome !!!

**Comment by kapeco** [comment]
2) ma résolution 1600x900
3) c'est vrai désolé ;) je regarde ca sous chrome

**Comment by corentin-begne** [comment]
j'ai test la suppression sous chrome en local et preprod, sous linux et window et ça fonctionne. j'ai test deux fois ...

**Comment by kapeco** [comment]
Étrange car j'ai test plusieurs fois depuis Chrome sous Windows et rien ne se passe :(

**Comment by corentin-begne** [comment]
t'as quand même la popup de confirmation ? si oui regarde dans le retour ajax ce que tu as et regarde dans la console si ya pas une erreur, peut être le cache aussi.

**Comment by corentin-begne** [comment]
j'ai trouvé une solution pour le datetimepicker, je l'ai réduit donc ça devrait mieux passer mtn. J'ai ajouté un check pour vérifier la validité de la date avec message d'erreur si elle n'est pas bonne.

**Comment by corentin-begne** [comment]
me manque tjrs le contenu du mail à l'agence ;)

**Comment by kapeco** [comment]
Bon

la suppression fonctionne sur firefox et chrome maintenant !!!

**Comment by kapeco** [comment]
voici le contenu du mail aux agences : 
"Bonjour,

Votre demande d'ordre de mission viens d'être validée et planifiée.
Retrouvez toutes les informations sur http://www,kapeco.com/mission/find

L'équipe KAPECO."

**Comment by corentin-begne** [comment]
j'ai ajouté le mail, ça l'envoi à celui qui a créé l'ordre de mission et au manager de l'agence si ils sont différents. J'ai corrigé un bug sur la gestion du token google agence, il faudra délier et relier le compte quand tu testera en preprod, pour l'instant c'est que en dev.

**Comment by kapeco** [comment]
Ok merci 
Je vais faire une passe de teste demain

**Comment by kapeco** [comment]
Petit soucis lorsqu'on crée un odm, dans les infos appartement , j'avais déjà signalé que c'était de l'aphanumérique
![2015-06-22 08_56_14-ordre de mission](https://cloud.githubusercontent.com/assets/11981295/8276928/be3a7fd0-18bc-11e5-83ba-187ce1b73b59.png)

**Comment by corentin-begne** [comment]
je te corrige ça ce soir

**Comment by corentin-begne** [comment]
c'est corrigé et j'ai viré la colonne Nom agence quand on est log en tant qu'agence.

**Comment by kapeco** [comment]
yes nickel , en plus j'y ai pensé mais je ne voulais pas te charger alors que ce soir tu dois revetir ta cape ;)

**Comment by corentin-begne** [comment]
Z

**Comment by kapeco** [comment]
krr

**Comment by kapeco** [comment]
lorsqu'on reçoit les alerte de l'odm , y mettre aussi le tel qui est rentré stp

**Comment by corentin-begne** [comment]
lequel et comment ?

**Comment by kapeco** [comment]
celui qui est rentré dans la création de l'odm 
tu te souviens on met toutes les infos qui sont rentrées

alors que là dans le mail jai bien toutes les info mais sur google agenda me manque le tel

pareil dans l'agencement du listing des odm , les mettre dans l'odre de création et non en fonction des dates de rdv, le plus récement créer étant en haut de liste

**Comment by corentin-begne** [comment]
bah dans le mail toute les infos sont reprise .. il y a plusieurs tel. J'ai classé les odm par état donc ceux en attente en premier puis par date décroissante, je pensais que ce qui était le plus important était de voir ceux en attente par les derniers.

**Comment by kapeco** [comment]
Oui en attente en premier puis par ordre de création 
Ou un système de tri par colonne

**Comment by kapeco** [comment]
C'est sur Google agenda qu'il manque les tel

**Comment by corentin-begne** [comment]
ben c'est déjà le cas pour le tri classé par en attente puis creation desc. Sur google agenda j'ai mis que la liste des mission, si tu compare au mail manque plein de truc, mais oui je peux ajouter le tel du proprio.

**Comment by kapeco** [comment]
toutes les info ça serait mieux encore, car l'orsqu'on se déplace on regarde notre agenda souvent pour y retrouver les infos .

sinon sur le site coté diagnostiqueur aujourd'hui on affiche les colonnes : 
 Nom agence	Ville du bien	Intervention	Diagnostiques
il faudrait 
Nom agence	Nom propriétaire Ville du bien	Intervention	Diagnostiques

coté agence on a  : 
Ville du bien	Intervention	Diagnostiques
il faudrait
Nom propriétaire Ville du bien	Intervention	Diagnostiques

**Comment by corentin-begne** [comment]
ok, j'ai mis le même contenu que le mail dans la des sur google agenda et j'ai ajouté le nom du propriétaire. C'est en preprod.

**Comment by kapeco** [comment]
merde !!!

Forbidden

You don't have permission to access / on this server.

faut stopper démone lol

**Comment by kapeco** [comment]
je ferme
