### ISSUE TITLE
Interface recherche agence

### ISSUE THREAD

**Issue by corentin-begne** [corentin-begne/kap#15]
Il me faudrait le design et les fonctionnalités

**Comment by kapeco** [comment]
Page avec l'affichage de la liste des agences liées à la franchise :
NomAgence: villeagence : cpagence : telcontact : emailcontact 
Voici les champs pour le moment .
Bien-sûr avec un moteur de rechercher qui fonctionne aussi bien sur le nom la ville ou le cp

Lorsqu'on sélectionne l'agence on arrive dans une liste de fonction :
Contact et historique des contacts avec l'agence 
Possibilité d'uploader un pdf pour l'agence 
Lister les demandes d'ordre de mission en attente ainsi que l'historique 

Voilà au moins pour le moment

**Comment by corentin-begne** [comment]
ok pour le listing avec les infos agences et le moteur de recherche (filtre) sur ville/cp. Par contre il me faut quand même le design et comment j'affiche les infos complémentaires surtout qu'il y en pas avec des fonctionnalités spécifique.

**Comment by kapeco** [comment]
Je ne vois pas trop ce que tu veux ... Fait un premier jet et on complétera

**Comment by corentin-begne** [comment]
un problème aussi c'est que ces infos ne sont pas rattachée directement à une agence, ce sont les users agence qui ont cette info mais dans ce cas lequel prendre ? ou alors je liste les users ?

**Comment by kapeco** [comment]
prendre celui qu'on défini "par défaut" pour afficher dans le listing générale , mais quand on entre dans le détail, on liste les Users aussi frocément

**Comment by kapeco** [comment]
a faire après la premiere MEP

**Comment by kapeco** [comment]
laisse tomber pour le moment , finissons le reste

je ferme on rouvrira plus tard
