### ISSUE TITLE
Interface upload diagnostic

### ISSUE THREAD

**Issue by corentin-begne** [corentin-begne/kap#16]
Il me faudrait le design et les fonctionnalités

**Comment by kapeco** [comment]
Une page ou on peut uploader un pdf pour une agence 
Donc moteur de recherche d'agence intégré et possibilité d'uploader a une agence qui n'est pas rattaché à la franchise pour laquelle je travail car souvent on se refile des clients .
Donc une fois l'agence sélectionnée et le contact de celle ci sélectionné aussi on peut charger le pdf 
On a des Check box qui nous permettent d'agir sur le statut et l'état 
Mais par défaut le statut non payé est et l'état est verrouillé

**Comment by corentin-begne** [comment]
ok je fais un champ d'autocompletion sur le nom des agences, une fois sélectionnée, j'affiche le champ d'upload pdf avec deux checkbox, une pour le statut et une pour l'état (bien que je ne vois pas à quoi sert l'état), une fois validé ça reset tout.

**Comment by kapeco** [comment]
Ok

**Comment by corentin-begne** [comment]
j'ai bien avancé, tu peux voir avec ton compte diagnostiqueur le lien "Upload un diagnostique" (tu me diras ce que tu veux). Dis moi les changements que tu veux pour le design et je me disais que ça serais mieux de stocker les pdf en bdd pour des raisons de sécurité. Je me en stand by sur ça, je vais faire le reste de l'enregistrement et commencer le listing.

**Comment by kapeco** [comment]
ok du coup je pense qu'il faut ajouter :+1: 
Clientname: adresse : type de bien : type transaction : statut: état : note
histoire d'être en accord avec la page de listing des dossiers

**Comment by corentin-begne** [comment]
ok je vais ajouter ça. Si ça upload sur envoyer, si t'as pas select de fichier il veut pas envoyer (j'ai pas mis de message d'erreur), c'est filtré sur pdf/xls

**Comment by corentin-begne** [comment]
pour le champ note ça correspond à un commentaire ou un chiffre ?

**Comment by kapeco** [comment]
Juste de notes libres alphanumérique 255 caractères

**Comment by corentin-begne** [comment]
J'ai terminé l'interface avec les nouveaux champs et l'enregistrement du fichier en bdd.

**Comment by corentin-begne** [comment]
j'ai refais le bouton upload pour qu'il soit compatible sous ff

**Comment by kapeco** [comment]
ok alors c'est nickel tout ça , juste changer la phrase "sélectionner un diagnostic" par "sélectionner un rapport"
et quand je sélectionne un fichier c'est déconcertant car je ne vois pas le nom du fichier en attente d'upload mais toujours "sélectionner un diagnostic", du coup on a l'impression que ça foire et on recommence , ce qui n'est pas top
idem quand on envois , il ne se passe rien , on a l'impression que ça foire , du coup ca crain 

et je me dit que lorsqu'on recherche l'agence on devrait voir l'ensemble de ses fichier avec une option d'upload pour un nouveau fichier , donc peut etre fusionner ces deux pages

**Comment by corentin-begne** [comment]
j'ai modifié le nom du bouton et que quand tu sélectionnes un fichier ça mets son nom en vert à la place du nom du bouton. Pour l'envoie, il y a maintenant un loader sur tous les envois (de toute façon tu ne pouvais pas valider tant que la requête était en cours). Ok je vais voir pour modifier l'interface pour la fusionner avec le listing.

**Comment by kapeco** [comment]
Impeccable tu taff bien fiston 😉
Merci encore
