### ISSUE TITLE
Interface listing diagnostic

### ISSUE THREAD

**Issue by corentin-begne** [corentin-begne/kap#17]
Il me faudrait le design et les fonctionnalités

**Comment by kapeco** [comment]
Page avec la liste des diagnostics réalisés pour une agence :
Clientname: adresse : type de bien : type transaction : statut: état  : note 

Le statut peut être : payé: nonpayé: en attente
L'état peut être verrouillé : non verrouillé 

Si verrouillé : impossibilité de télécharger le document ( payement en ligne pour débloquer ou action d'un diagnostiqueur pour débloquer )

**Comment by kapeco** [comment]
Ajouter aussi un compteur de téléchargement pour chaque fichier 
Quand au design faire comme dans l'ancien site .
Et concernant le module de payement on fera ça dans une seconde étape mais laisse toi la possibilité de le faire

**Comment by corentin-begne** [comment]
```
Clientname: adresse : type de bien : type transaction : statut: état : note
```
dans cette liste je n'ai que statut et état qui ont été saisis sur l'interface d'upload.

**Comment by kapeco** [comment]
ajouter tout ça  : 
Clientname: adresse : type de bien : type transaction : statut: état : note

**Comment by corentin-begne** [comment]
ce que tu m'expliques c'est pour l'accès agence/client mais quand c'est un diagnostiqueur qui accède a cette page, j'imagine qu'il peut téléchargement le fichier même si il est locké et peut le verrouiller/déverouiller. Pour le compteur de téléchargement, est qu'il peut être global ou tu veux savoir qui l'a téléchargé et combien de fois ? Pour le design je vais prendre ce que j'ai fais dans le back. Est ce que tu veux que je mettes une pagination ? Si oui, dis moi de quelle forme et si t'as un design spécial que tu veux stp.

**Comment by kapeco** [comment]
exactement tout ce que tu as écrit, idem pour la pagination, un truc simple

**Comment by corentin-begne** [comment]
j'ai bien avancé, j'ai fusionné l'upload et le listing, j'ai créé un système de pagination, j'ai mis la limite à 1/page pour que tu puisses la voir sinon je mettrais 20.  Pour l'instant je n'ai pluggé que la création (ce que j'avais fais avant) mais j'ai fais listing avec la gestion des droits. Si t'es diag tu peux toujours dl et tu peux ajoute/editer/supprimer (donc seulement ajouter fonctionne pour le moment) et si t'es agence, selon que c'est locké ou pas tu vois l'icone de dl ou le lock et bien sur tu vois pas les icones ajouter/editer/supprimer. Pour payé/en attente/non payé j'ai mis un fond vert/orange/rouge tu me dis si tu veux autre chose, pareil pour les icones. Tu peux déjà test ça, j'ai mis le nb de dl dans le title de l'icon, je ne prendrais en compte que les dl agence/client

**Comment by corentin-begne** [comment]
le lien "Diagnotiques" dans le menu

**Comment by kapeco** [comment]
ok j'ai vu , je te laisse terminer car tout n'est pas encore fonctionnel encore de mon côté donc difficile d'en dire plus mais c'est sur la bonne voie.
Les autres liens ne fonctionnent plus pour info  !

**Comment by corentin-begne** [comment]
quel liens ?

**Comment by kapeco** [comment]
Odm et les autres qui sont dans cette catégories

**Comment by corentin-begne** [comment]
odm pour l'instant il ne fonctionne que quand t'es loggé en tant qu'agence vu que j'ai fais que la création, upload fonctionne plus parce qu'il a fusionné avec Diagnostiques (je l'ai supprimé d'ailleur), agence j'ai rien fais et Paramètres fonctionne encore.

**Comment by corentin-begne** [comment]
L'ajout, la modification et la suppression sont fonctionnelles, il reste à faire le dl, je m'en occupe tout à l'heure.

**Comment by corentin-begne** [comment]
c'est terminé, toute les actions sont pluggé avec la gestion des permissions selon que t'es diagnostiqueur ou agence.

**Comment by kapeco** [comment]
Pour l'odm , ne pas afficher le liens si on a pas les droits !
Le dl ne fonctionne toujours pas pour moi

**Comment by corentin-begne** [comment]
Le lien va exister juste que la page n'est pas encore faite. Pour le dl je comprends pas moi ça marche nickel, j'ai ressayé avec un nouveau rapport puis en le modifiant et ça fonctionne toujours, le rese des fonctionnalité aussi. Quand je regarde ton rapport en bdd il est à 0 ko je sais pas comment t'as fais car t'es obligé de mettre un fichier pour valider la création d'un diagnostique, t'as du up un fichier vide. Dis moi si ya des trucs à changer, je passe sur autre chose.

**Comment by kapeco** [comment]
Étrange mon fichier n'est pas vide 
Ça charge ça charge ... Puis au bout d'un moment ça met que c'est ok mais apparement non !

**Comment by corentin-begne** [comment]
il fait combien ton pdf ? tu peux me l'envoyer par mail stp. t'es sous quel os et browser ?

**Comment by kapeco** [comment]
je viens de t'envoyer un mail avec le fichier 

aujourd'hui j'ai une erreur , regarde : 
![2015-05-12 20_42_06-rechercher un diagnotique](https://cloud.githubusercontent.com/assets/11981295/7595460/7c2630f2-f8e7-11e4-9d46-8cbde7b49ec1.png)

**Comment by corentin-begne** [comment]
oui j'ai ajouté le check du fichier up, donc il a pas réusi a le up, peut être à cause de la taille ou quoi je vais voir.

**Comment by corentin-begne** [comment]
c'est ct la taille max de up qui était à 2M tu peux retest.

**Comment by kapeco** [comment]
Ok cool je test ça demain

**Comment by kapeco** [comment]
impossible d'acceder au site ....

**Comment by corentin-begne** [comment]
je le relance ce midi

**Comment by corentin-begne** [comment]
c'est up !

**Comment by kapeco** [comment]
c'est bon ça up !!!

Par contre plusieurs remarques : 
- le loader est super moche : mettre quelque chose de plus convivial avec une barre de progression par exemple qui serait bien car suivant la connexion on ne sait pas si ça foire ou si ça up toujours
- lorsqu'on veut télécharger un dossier "non payé"  : y a l'affichage rapide du fameux loader .
il faudrait plutôt un message indiquant que le téléchargement du dossier sera possible une fois le dossier payé
- je viens de la passer en "payé" : impossible de le télécharger ensuite

**Comment by corentin-begne** [comment]
- pour le loader file moi celui que tu veux, si tu veux un barre de progression ça fait du dev en plus.
- tu dois confondre, la téléchargement n'est permis que si le diag n'est pas vérouillé, qu'il soit payé, non payé ou en attente (c'est ce que j'avais compris) et en tant qu'agence, si un diag est verrouillé tu vois un cadenas à la place et quand tu cliques dessus ça ne fait (pas de loader) seul si t'es diag tu peux tout le temps dl quelque soit la config du diag, il ne doit pas avoir juste un loader qui dl rien sinon c'est que le diag est foiré

**Comment by kapeco** [comment]
hum
je suis connecté uniquement en diagnostiqueur donc je pourrais dl d'après toi mais ça ne passe pas !

- si c'est payé ça doit passé en déverrouillé automatiquement
- si c'est non payé ça doit passé en verrouillé automatiquement
- l'action manuelle du verrou se fait sur "en attente"

sinon je confirme une barre de progression lors de l'up

**Comment by corentin-begne** [comment]
connecté en diag, le dl sur ton rue de joinville diag fonctionne très bien, j'ai le pdf mission de repérage ..
ok bah faut que je change du coup j'avais compris que ct complètement dissocié et ok pour le up mais tu l'auras pour toute les requête ajax alors

**Comment by corentin-begne** [comment]
peut être que c'est bloqué par ton navigateur.

**Comment by kapeco** [comment]
ah bon c'est un loader général ? , moi je te parle d'une barre de progression sur la page pas sous forme de loarder

**Comment by corentin-begne** [comment]
oui, l'upload ne s'effectue qu'à la validation du formulaire, pas quand tu sélectionnes le fichier.

**Comment by kapeco** [comment]
ok pas grave ça

**Comment by corentin-begne** [comment]
non qu'il soit vérouillé ou pas ça ne change rien en tant que diag, je pense que ton browser doit bloquer la popup chez moi ça fonctionne.

**Comment by kapeco** [comment]
Il ne bloque pas normalement , et je me voit mal expliqué aux agences de vérifier etc ... Tu connais les agences .
Faut que ce soit bon contraignant

**Comment by corentin-begne** [comment]
si tu veux un dl ça lance forcément une popup sinon pas de dl.

**Comment by kapeco** [comment]
oui je sais bien et je dl sur tous les site sauf celui-ci ....

**Comment by kapeco** [comment]
je viens de test en préprod

j'up le fichier, ensuite ça écrit ok, je clic et y a rien de plus sur la page . 
![2015-06-02 19_08_22-rechercher un diagnotique](https://cloud.githubusercontent.com/assets/11981295/7941915/c704d5b4-095a-11e5-80c5-7b6395576319.png)

**Comment by corentin-begne** [comment]
j'ai modifié le système pour que ça fonctionne sous firefox donc normalement tout est fini sur cette interface.

**Comment by corentin-begne** [comment]
je viens de test sur chrome ça fonctionne nickel, je vois bien mon diagnostique, faire gaffe la limite en up sur les mutu c'est 50Mo je crois.

**Comment by corentin-begne** [comment]
sur firefox ça foire effectivement.

**Comment by corentin-begne** [comment]
non en fait ça fait pareil sur chrome, je pense que ça vient de la taille du fichier mais côté mysql, je vais faire des tests pour trouver.

**Comment by corentin-begne** [comment]
@kapeco 
oui donc ça vient de la config mysql sur mon mutu : 
```
#1153 - Got a packet bigger than 'max_allowed_packet' bytes
```
Il est configuré à 1 048 576 octet et le post_max_size est à 64Mo

**Comment by corentin-begne** [comment]
c'est bon pour cette partie ?

**Comment by kapeco** [comment]
non pas tout à fait

changer le tire "Rechercher un diagnostique" en "Les diagnostics"

et aussi afficher sous le moteur de recherche la liste des agences ( 10 max / page avec pagination) et si on clic sur une agence on arrive au meme resultat que si on recherche une agence dans le moteur de recherche , c'est à diire la liste des diag up

**Comment by corentin-begne** [comment]
ça me demande pas mal de changement d'afficher la liste des agences au lieur d'afficher celle sélectionné dans le moteur de recherche. Pareil pour le compte du dl, il va falloir que je change là je l'ai mis en global seul les diag ne sont pas pris en compte et si il faut que j'affiche la liste des users qui l'on dl il faudrait me dire comment.

**Comment by kapeco** [comment]
Quand on est admin , juste au survol on a une petite box avec les infos ( qui quand combien)

**Comment by corentin-begne** [comment]
en fait tu veux fusionner les diags et la recherche/listing d'agence ? Je te propose d'ajouter dans l'auto completion l'adresse de l'agence et ça affiche les infos dans le result sinon il faut que je termine la partie agence avant et franchement je comprends pas bien l'intérêt d'avoir un listing intermédiaire des agences avant d'accéder aux diags. Tu peux check ce que ça rend en dev. Je fais la parties dl dès que possible.

**Comment by kapeco** [comment]
en fait on arrive et on voit la liste des agences avec lesquelles on travail, mais certain peuvent en avoir beaucoup , du coup faut un moteur de recherche.
une fois l'agence trouvée , on clic dessus et on a accès a la liste des diags déja envoyé et la possibilité d'en up un nouveau

**Comment by corentin-begne** [comment]
ok donc je t'ai mis le listing des agences à l'init avec la pagination, quand on clique sur la ligne de l'agence on arrive sur la liste des diags associés de la même manière qu'avec la moteur de recherche dans lequel j'ai jouté l'adresse, la partie recherchée en gras et il cherche dans toute la chaine.
J'ai également modifié le dl pour l'associé aux user, maintenant seulement quand on est admin et diag on a le compte des download au survol ainsi que la liste des users et le nb de fois qu'ils ont dl. 
J'ai aussi associé le select de l'état avec le lock pour ne pouvoir le modifier que quand c'est en attente sinon il se lock automatiquement sur le bon état.
Le tout est en preprod.

**Comment by corentin-begne** [comment]
@kapeco c'est good ou pas ?

**Comment by kapeco** [comment]
oui ça a l'air tout bon ça
