### ISSUE TITLE
drag&drop des liens

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#19]
les drag&drop des liens dans les autres catégories que la première ne fonctionne pas.
En effet ça semble fonctionner mais ça ne mémorise pas

**Comment by corentin-begne** [comment]
non c'est normal, les liens ne sont pas interchangeable entre catégorie.

**Comment by kapeco** [comment]
Non non mais au sein de la même catégorie je parle

**Comment by corentin-begne** [comment]
au sein de la même catégorie ça fonctionne, je viens de retester dans les deux (pb de cache peut être).

**Comment by kapeco** [comment]
Ça fonctionne puis des que tu clic sur un lien ça se remet comme c'était

**Comment by corentin-begne** [comment]
je n'arrive pas à reproduire, que je clique sur le lien après avoir validé ou que je refresh la page ça fonctionne :/

**Comment by kapeco** [comment]
étrange ça fonctionne nickel maintenant
