### ISSUE TITLE
Edition d'un article bloque

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#2]
j'ai utilisé l'admin front pour changer le texte de mon liens "bla bla"

j'appuis sur OK mais il ne se passe rien
![2015-04-13 19_47_16-bla bla](https://cloud.githubusercontent.com/assets/11981295/7185461/073a9032-e463-11e4-935c-e74f3d1b65d5.png)

**Comment by corentin-begne** [comment]
c'est corrigé

**Comment by kapeco** [comment]
au top !!!
