### ISSUE TITLE
Probleme dans le display "diagnostique"

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#20]
![2015-05-09 11_23_02-rechercher un diagnotique](https://cloud.githubusercontent.com/assets/11981295/7549622/decd7c80-f63d-11e4-990e-2b2f557f778e.png)

**Comment by corentin-begne** [comment]
?

**Comment by corentin-begne** [comment]
les largeurs des colonnes s'adaptent au contenu et c'est limité car la largeur de ton site est fixe.

**Comment by kapeco** [comment]
Dans ce cas retirons la colonne de droite quand on est dans ce menu

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
merci
