### ISSUE TITLE
BO : Creation des agences

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#21]
Dans la partie BO , séparer le création des agences immo et celle des franchises
Fusionner le rattachement d'une agence immo a une franchise dans le formulaire de création et édition d'une agence immo

![2015-05-09 11_27_43-admin kapeco](https://cloud.githubusercontent.com/assets/11981295/7549643/ab2bf540-f63e-11e4-82b2-ed86fa19e218.png)

**Comment by corentin-begne** [comment]
là ce sont des formulaires qui sont généré automatiquement basé sur les tables et les clés étrangère, si tu veux ça je dois dois faire une interface spécifique et refaire quasiment toute les fonctionalités

**Comment by kapeco** [comment]
Obligé car ça va vite être le Bordel sinon

**Comment by corentin-begne** [comment]
Je croyais qu'on restait sur du basic sur le BO, si tu le veux pour ça tu vas le vouloir pour les permissions aussi j'imagine, on a pas fini ... je vais réfléchir à un système.

**Comment by kapeco** [comment]
Bon mais la ce sont deux choses complètement différentes , y a des retouches à faire , les infos ne seront pas forcément les mêmes

**Comment by corentin-begne** [comment]
Comme vu ensemble, on mettra ça en place dans un second temps après le lancement.

**Comment by kapeco** [comment]
Oui
