### ISSUE TITLE
compatibilité browser/os

### ISSUE THREAD

**Issue by corentin-begne** [corentin-begne/kap#23]
Le site est fait pour être visualisé sur un ordi normal avec un browser récent full HTML5/CSS3 de part les tailles fixes en css, les articles, les formulaires et les plugins JS. Je ne peux pas dire si ça fonctionne sur autre chose ni dev ou test dessus mais il se peut fortement que certaines chose ne fonctionne pas du tout.

**Comment by kapeco** [comment]
ça j'en suis conscient, je suis sous le dernier firefox 38.0.1
Faudrait aussi assurer un compatibilité avec google chrome

**Comment by corentin-begne** [comment]
je dev sur chrome donc ça c'est, ça devrait fonctionner sur ie11 et firefox sans bug sinon j'adapterai mais c'est surtout mobile tablette et portable qui m'inquiète.

**Comment by kapeco** [comment]
bon je viens de regarder , sous chrome je dl bien le fichier 

Sous firefox , toujours pas alors que le navigateur ne bloque pas les pop-up
![2015-05-23 20_57_31-options](https://cloud.githubusercontent.com/assets/11981295/7785397/8969b78e-018e-11e5-8a88-2ea68782230d.png)

lorsque je clic , en fait j'ai 1/2 seconde le loader puis rien de plus

**Comment by kapeco** [comment]
Bon faudrait tout de même faire ça en urgence maintenant

**Comment by corentin-begne** [comment]
ça fait longtemps déjà que j'ai modifié la méthode de génération et de dl du pdf, je l'avais testé sur ff ça fonctionnait.

**Comment by kapeco** [comment]
oui mais pas l'ordre de mission

**Comment by corentin-begne** [comment]
depuis quand l'odm doit être téléchargeable ?

**Comment by kapeco** [comment]
Mais non mdr 
Depuis Firefox en tant qu'agence je ne peux pas créer un odm

**Comment by corentin-begne** [comment]
ah ok bah je check ça ce soir

**Comment by kapeco** [comment]
merkrrrrrrriii :)

**Comment by corentin-begne** [comment]
c'est fait en dev

**Comment by kapeco** [comment]
je test

**Comment by kapeco** [comment]
le picker pour la date est un peu bas

**Comment by corentin-begne** [comment]
je ne vois pas de quoi tu parles

**Comment by kapeco** [comment]
bon ben rien c'est bon maintenant
go to prod aussi

**Comment by corentin-begne** [comment]
c'est en prod

**Comment by kapeco** [comment]
impec
