### ISSUE TITLE
loader

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#24]
une idée de loader qui peut aussi servir pour les upload

http://blog.websourcing.fr/percentageloader-plugin-jquery-loaders-toute-beaute/

**Comment by corentin-begne** [comment]
je l'ai mis en place, en fait il y en a deux, un pour la requête réseau et l'autre pour l'upload. Celui de l'upload n'est présent que quand il y a en a un, il est deux fois moins grand et juste au dessus de l'autre qui est centré.

**Comment by corentin-begne** [comment]
j'ai également mis une interface blanche avec un croix en haut à droite pour fermer et un fond en opacité 0.3 noir sur les popups plein écran.

**Comment by kapeco** [comment]
Ok je vais regarder ce soir ce que ça donne

**Comment by kapeco** [comment]
nickel
