### ISSUE TITLE
Plus de liens 

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#26]
Un fois connecté je n'ai plus aucun liens dans la catégorie qui correspond normalement à l'affichage des liens comme diagnostic, profil etc ...

**Comment by corentin-begne** [comment]
je viens de test avec mon compte superadmin/admin/diag et mon compte agence et j'ai bien les liens correspondant à leur permissions qui s'affichent. Avec quel compte tu te connecte ?

**Comment by corentin-begne** [comment]
je viens de test avec tes deux comptes et je vois bien les liens correspondant à leur droits

**Comment by kapeco** [comment]
ça y est ça fonctionne mais que depuis mon pc , plus depuis mon iphone :(

**Comment by corentin-begne** [comment]
peut être à cause du loader, il utilise un canvas 2D pour faire le chargement. Je peux pas test pour voir, t'as des erreurs ?

**Comment by corentin-begne** [comment]
en fait il y avait un bug quand tu te trompais de login/password, il te loggait quand même mais ça foirait ... c'est corrigé.

**Comment by kapeco** [comment]
Ok merci je vais test
