### ISSUE TITLE
Upload diag

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#29]
que j'up un fichier , le loader charge jusqu'a 100% puis affiche un message "ok"
donc je clic pour valider , mais mon up n'apparait pas dans la liste !!!

**Comment by corentin-begne** [comment]
t'as regardé mon dernier commentaire dans l'autre issue concernant la limitation sur mon mutu ?

**Comment by kapeco** [comment]
Ah oui c'est vrai désolé

**Comment by kapeco** [comment]
J'espère que je n'aurais pas ce soucis sur mon compte ovh , sinon faudra revoir la méthode de stockage

**Comment by corentin-begne** [comment]
dans ce cas faut changer d'hébergeur ya carrément mieux pour moins cher.

**Comment by corentin-begne** [comment]
parce que  t'as les vps qui sont mieux et moins même chez ovh, je ne sais pas quel hébergement mutu tu as mais ça vaut peut être la peine de changer (jte fais l'install si tu veux) : 
https://www.ovh.com/fr/vps/vps-classic.xml

**Comment by kapeco** [comment]
Je vais me pencher sur ça ...

En attendant j'ai réussi à up avec un fichier plus petit .
Par contre plusieurs constats : 
1) j'ai envoyé le fichier en non payé et jai laissé le cadenas fermé, pourtant j'arrive à DL le fichier  ... ça ne devrait pas être possible
2) quand je dl le fichier , il n'a plus le même non que lorsque je l'ai envoyé, il faudrait pouvoir garder le nom

**Comment by corentin-begne** [comment]
C'est normal quand t'es diag tu peux le dl tout le temps et si t'es en agence seulement si il est dévérouillé, la payé et vérouillé sont dissociés actuellement.  Pour le nom je vais voir pour changer pour le récupérer à l'upload et le stocker en bdd mais bon du coup ça peut être des noms pourris, je ne pense pas que ça soit une bonne idée.

**Comment by kapeco** [comment]
y a pas de nom pourris , ce sont le "nomduclient - adresse .pdf"

**Comment by kapeco** [comment]
Petit soucis lors de l'édition d'un diag en mode diagnostiqueur : 
![2015-06-12 15_39_00-rechercher un diagnotique](https://cloud.githubusercontent.com/assets/11981295/8131278/7d6a5232-1119-11e5-93c5-f1352fdfd49a.png)
si j'édit celui du milieu qui est en "non payé" , une fois la fenêtre d'édition ouverte alors le status est "en attente"
![2015-06-12 15_39_26-rechercher un diagnotique](https://cloud.githubusercontent.com/assets/11981295/8131296/9f2be8c2-1119-11e5-8b0a-2988fe573453.png)
pour info j'ai essayé de l'édité apres avoir up un diag en attente

**Comment by kapeco** [comment]
je reviens sur le VPS, c'est bien mais tu as juste un Os , faut installer , le serveur web , mail , mysql  ....

pas plus simple ça https://www.ovh.com/fr/hebergement-web/offres-performance.xml

**Comment by corentin-begne** [comment]
je sais pas, c'est beaucoup plus cher quand même et puis t'as pas besoin de tout ça, je peux te faire l'install si tu veux.

**Comment by kapeco** [comment]
Mes besoins : 
avoir plus de 100 mails en kapeco.com
pouvoir stocker en DB tous les diags uploadés (1,5 GO environ surement plus plus tard )

**Comment by corentin-begne** [comment]
pour la bdd aucun pb par contre pour les compte mails je n'ai jamais vraiment utilisé et de ce que j'en sais c'est galère à gérer, peut être voir à utiliser un service tiers.

**Comment by kapeco** [comment]
ouais mais non , on a déjà tout de configuré avec la messagerie de l'hebergement ovh

**Comment by corentin-begne** [comment]
faudrait que je me renseigne sur le serveur mail.

**Comment by kapeco** [comment]
j'ai fait pas mal d'admin système et les mail j'ai toujours galéré.
Je pense que dans un premier temps c'est pas mal ce que je tai montré car depuis l'admin d'ovh je peux directement migrer vers ça , du coup j'imagine qu'il n'y a pas à tout reconfigurer

**Comment by corentin-begne** [comment]
oui tu dois avoir une preconfig j'imagine faudrait pouvoir test.

**Comment by kapeco** [comment]
On verra ça rapidement , faisons déjà cette mep

**Comment by kapeco** [comment]
J'ai ouvert un ticket y a 4 jour chez Ovh pour augmenter la taille des fichiers pouvant être stocké en db .... toujours de réponse

Je me demandais aussi si ça ne venait pas de la config php

**Comment by corentin-begne** [comment]
c'est une variable mysql, on ne peut pas la modifier par le htaccess ou php.

**Comment by kapeco** [comment]
Je suis avec OVH au tel et le gars me dit que la limitation de taille par fichier est fixée à 16MO

Il lui faudrait les messages d'erreur pour pouvoir faire une recherche

**Comment by corentin-begne** [comment]
l'erreur est 
```
#1153 - Got a packet bigger than 'max_allowed_packet' bytes
```
dès qu'on up un fichier de plus de 1Mo, j'ai matté dans phpmyadmin les varibale globale et max_allowed_packet est configuré à 1 048 576 octet

**Comment by kapeco** [comment]
c'est exactement ce qu'il m'a dit du coup.

Faut que je prenne une mysql privée comme ça on a plus de limite

**Comment by kapeco** [comment]
Mysql 5.5 ça te va ou tu as une restriction et il te faut 5.1 ?

**Comment by corentin-begne** [comment]
même 5.6.+ ça serait mieux car j'ai mis un double timestamp dans certaines tables et du coup j'ai du bidouiller pour pouvoir les exporter dans ta bdd et du coup ils ne sont pas mis à jour, j'ai juste mis dans le code pour forcer pour link pour pouvoir gérer les date pour le seo

**Comment by kapeco** [comment]
y a pas 5.6 , que 5.5 max

**Comment by corentin-begne** [comment]
c'est dla merde !!!

**Comment by kapeco** [comment]
lol tu veux que je fasse quoi de plus !

**Comment by corentin-begne** [comment]
je sais pas mais je trouve que c'est abusé que tu payes un serveur sql privé et que tu puisse même pas choisir la version ...

**Comment by kapeco** [comment]
si entre deux versions c'est tout !
tu as travaillé pour eux , tu sais comment ça se passe ;)
Bon elle est commandée avec une taille illimité, j'attend d'avoir les accès, ensuite on passera la preprod dessus pour tester avant de migrer la prod bien-sur

**Comment by corentin-begne** [comment]
ok ça  marche.

**Comment by kapeco** [comment]
regarde ton mail

**Comment by kapeco** [comment]
tu t'en sort avec la base de donnée ou t'es en grèves lol

**Comment by corentin-begne** [comment]
j'y accède comment par phpmyadmin ?

**Comment by kapeco** [comment]
Ben ouais

**Comment by kapeco** [comment]
https://sqlprive.ovh.net

**Comment by corentin-begne** [comment]
vaec l'ip locale et les anciens paramètres de connection de preprod ça ne focntionne pas, t'as pas un autre host pour phpmyadmin ?

**Comment by kapeco** [comment]
Je te l'ai envoyé y a deux jour par mail

**Comment by corentin-begne** [comment]
oui tu m'as filé une ip en 10.* qui est une ip locale et que phpmyadmin ne reconnait pas apparemment.

**Comment by kapeco** [comment]
je m'y suis connecté avec pourtant , je regarde ça

**Comment by kapeco** [comment]
Je suis dessus ça marche très bien

**Comment by corentin-begne** [comment]
avec l'ancien login et pass de la preprod ?

**Comment by kapeco** [comment]
normalement oui mais je viens de te renvoyer un mail

**Comment by corentin-begne** [comment]
oula t'avais pris mon ancienne preprod j'essayait avec celle actuelle.

**Comment by kapeco** [comment]
ah ben c'était les config que j'avais

**Comment by corentin-begne** [comment]
bon j'ai mis les data de la prod dans la nouvelle preprod et j'ai fait une mise en preprod pour que ça pointe sur la nouvelle, tu peux tester l'up.

**Comment by kapeco** [comment]
passe pas :(

**Comment by corentin-begne** [comment]
max allowed packet est toujours à  1 048 576 octets

**Comment by kapeco** [comment]
mais là on peut le changer normalement

**Comment by corentin-begne** [comment]
```
set global max_allowed_packet=10M
#1227 - Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

**Comment by kapeco** [comment]
c'est ce que j'allais faire

**Comment by kapeco** [comment]
SET GLOBAL max_allowed_packet=12582912;

**Comment by corentin-begne** [comment]
bien joué t'as plus qu'à test

**Comment by kapeco** [comment]
c'est bon j'ai appliqué et ça fonctionne impec , par contre si on redémarre le serveur  faudra rejouer la requette

**Comment by kapeco** [comment]
ya plus qu'a migrer la prod aussi

**Comment by corentin-begne** [comment]
ok

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
Merci
