### ISSUE TITLE
Liens reférencement

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#3]
Ajouter les liens en bas de page pour le référencement
côté admin , on ajoute un nom de ville et ça génère les page avec le contenu et les liens, cf site d'origine

**Comment by corentin-begne** [comment]
j'ai presque terminé, donc tu as une catégorie "faux liens" dans l'admin qui te permet de gérer la liste des villes. Les liens qui sont crée correspondent à ceux de la première categorie et affiche:
catName llinkName Ville
pareil pour le lien
/catPath/linkPath/ville
et dans le texte ça renvoie sur le lien de l'article correspondant, tu peux test j'ai saisi quelques villes, reste qu'à faire le css normalement.

**Comment by kapeco** [comment]
je n'arrive pas à me connecter ... TimeOut

**Comment by kapeco** [comment]
c'est bon ce matin

Par contre c'est magnifique mais y a une couille dans le pottage : 
"Diagnostics immobiliers Accueil gagny "

c'est quoi ça un diagnostic accueil ??? pour les stagiaire en secrétariat  ? xD

**Comment by corentin-begne** [comment]
ben ça reprend les noms des liens de la categorie principale, faut changer accueil par autre chose ou sinon je peux l'exclure.
Je comprends pas ce que tu veux que je remplace les deux textes sont pareil xD
Je vais voir pour ajouter l'édition du template

**Comment by kapeco** [comment]
Oui exclusion pour accueil 
Ah excuse lol 😀 
Remplacer "diagnostic immobilier gaz gagny "
Par "diagnostic gaz gagny"

**Comment by kapeco** [comment]
Tu auras compris j'ai oublier la majuscule et les s 

😉

**Comment by corentin-begne** [comment]
j'ai fais les changements pour les textes. Pour l'édition du template c'est compliqué car il y a du php dedans, sinon il faudrait que je crée un système spécial avec des tags à remplacer et après faut voir comment tu veux l'éditer.

**Comment by kapeco** [comment]
Si il y a du Php c'est pas grave , je ferai en sorte qu'il n'y a que moi qui le fasse comme ça pas de cassage de code

**Comment by corentin-begne** [comment]
C'est en place, il y a un nouveau lien dans l'admin "Faux liens template", j'ai utilisé le plugin Ace que je trouve pas mal. J'ai choisi le mode HTML et le thème twilight, tu peux test et choisir autre chose sur ce lien si tu veux : 
http://ace.c9.io/tool/mode_creator.html

**Comment by kapeco** [comment]
Ok super même presque impec car ça ne met pas à jour sur le front

**Comment by corentin-begne** [comment]
c'est corrigé par contre étrangement je n'ai pas ce template dans ma liste, il faut que je trouve comment le récupérer.

**Comment by kapeco** [comment]
nikel merci

par contre du coup je ne peux pas tout éditer .. ! mais c'est déja bien comme ca

si je prend un exemple : 
dans title="<?=$title?>" il y a :
Diagnostic Loi carrez chantilly
a remplacer par
Diagnostic Loi carrez à chantilly

**Comment by corentin-begne** [comment]
je t'ai mis la création de la variable au début du template pour que tu puisses la custom.

**Comment by kapeco** [comment]
Ça c'est impeccable, merci 😊
