### ISSUE TITLE
Mise en Prod

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#30]
une fois que https://github.com/corentin-begne/kap/issues/17 et https://github.com/corentin-begne/kap/issues/11 seront ok et que la compatibilité navigateur le sera aussi alors ou pourra faire une première mise en prod

**Comment by corentin-begne** [comment]
#17 et #11 devrait être ok normalement, c'est en preprod je te laisse test oublie pas de relier ton google agenda. Une fois que t'auras validé on pourra commencer les tests browser.

**Comment by kapeco** [comment]
krr ..
L'idée c'est de pouvoir mettre en prod cette semaine.
Jeudi j'ai une démo à faire pour un réseau d'agence immobilière.

Il y a encore quelques rectification à faire dans les différents sujets ouvert, ensuite plus de modif mais du cosmétique pour les différents navigateurs. et on pourra mettre en prod
Penses tu que ça va être jouable ?

**Comment by corentin-begne** [comment]
ça va être compliqué car les modifs que tu me demande sur la partie agence et mission me demande énormément de taf, je ne sais pas du tout quand est ce que je pourrais les faire et vu que je reviens encore sur ce que j'ai fais ça risque de générer des bugs. et après faudra encore debug ie et ff krr

**Comment by kapeco** [comment]
Faire au mieux alors ...

**Comment by kapeco** [comment]
Faudrait quand même qu'on puisse faire une mep du site dans cet état afin de changer la vitrine du site actéuel et que je puisse en modifier correctement le contenu de chaque liens .
Comme ça en attendant tu continu a travailler sur ce qui est caché ( car nécessite d'avoir un compte pour ce connecter )

**Comment by corentin-begne** [comment]
parce que ce week end j'étais pas là et le soir cette semaine j'aurais pu faire quelque modif mais ça implique que je m'y mette pendant plusieurs heures, ça va êre compliqué :/

**Comment by kapeco** [comment]
pas possible de faire juste la MEP de l'état actuel ?

**Comment by corentin-begne** [comment]
si bien sur, me faut juste les accès.

**Comment by kapeco** [comment]
ok impec , a quelle heure on peut faire ça ?
Les accès je te les avais envoyé au tout début , mais si tu ne retrouver pas je te redonnerais ça

**Comment by kapeco** [comment]
je t'ai vidé le dossier /dev
