### ISSUE TITLE
Accès admin

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#31]
lorsqu'on se log en back office , on y voit la liste des liens de la partie admin avant même d'être loguée
![2015-06-12 16_09_58-admin kapeco](https://cloud.githubusercontent.com/assets/11981295/8131877/a46247ba-111d-11e5-8a38-28f3d38cc236.png)

**Comment by corentin-begne** [comment]
c'est quand t'es déjà loggé mais pas avec les bonnes permissions, je vais corriger ça

**Comment by corentin-begne** [comment]
c'est corrigé en dev

**Comment by kapeco** [comment]
nickel
