### ISSUE TITLE
Back office - impossible de créer un user

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#32]
![2015-06-12 16_20_54-admin kapeco](https://cloud.githubusercontent.com/assets/11981295/8132041/1c0060e4-111f-11e5-8e20-10b0843881cf.png)
Quand j'essaye de rentrer l'adresse , qui je pense devrait être sur plusieurs champs (adresse cp ville) ce qui permettra dans l'outil de recherche d'agence de faire une recherche , par nom de ville , cp etc ... mais ce n'est pas le soucis actuel , je n'arrive pas à rentrer ce que je veux , c'est comme si mon clavier devenait fou , je tape sur une lettre et y en a plusieurs qui s'affichent ... je pense qu'il y a une désynchro entre la clavier et l'interface

SI je passe et que j'essaye de remplir le formulaire jusqu'au bout j'ai d'autres soucis : 
![2015-06-12 16_26_30-admin kapeco](https://cloud.githubusercontent.com/assets/11981295/8132147/e8792ff2-111f-11e5-9264-d14e44360c66.png)
impossible d'entrer plus d'un caractère pour les champs alert_email et alert_push

**Comment by corentin-begne** [comment]
alert_email et alert_push sont des boolean qui ne peuvent contenir que les valeur 0 ou 1 . J'ai réussi à créer des users, il faut remplir tous les champs et mettre les bonnes valeurs par contre la fenêtre ne se ferme pas et l'interface ne se rafraichit pas parce qu'il y a un warning dans le retour, je vais désactiver tous les warning sur la preprod.

**Comment by kapeco** [comment]
Ok

**Comment by corentin-begne** [comment]
@kapeco 
j'ai fais une mise à jour sur les formulaires du backend, le listing et l'ajout sont plus lisible et plus facile à utiliser, je te laisse check en dev, il manquera plus qu'à mettre la pagination et pouvoir joindre plusieurs formulaire, je le ferais plus tard.

**Comment by corentin-begne** [comment]
@check si ça te vas, si tu veux d'autres petit changements

**Comment by kapeco** [comment]
c'est mieux comme ça

Par contre pour la création des agences faudrait ajouter les adresses

**Comment by corentin-begne** [comment]
on avait dit que l'adresse de l'agence est l'adresse du manager.

**Comment by kapeco** [comment]
A bon ? ... Hum pas pour les agences Immo

**Comment by corentin-begne** [comment]
si  pour les deux et surtout pour les immo car ce sont les seules qui sont affichées en lisitng avec l'adresse associé qui est donc celle du manager.

**Comment by kapeco** [comment]
WTF ??!

je check mais ça me semble étrange

**Comment by corentin-begne** [comment]
dans la partie interface recherche agence: 
"un problème aussi c'est que ces infos ne sont pas rattachée directement à une agence, ce sont les users agence qui ont cette info mais dans ce cas lequel prendre ? ou alors je liste les users ?"
tu m'as dit : 
"prendre celui qu'on défini "par défaut" pour afficher dans le listing générale , mais quand on entre dans le détail, on liste les Users aussi forcément"

Donc j'ai considéré l'user par défaut donc le manager comme ayant les infos principales de l'agence (addresse, ville, cp, email, tel)

**Comment by kapeco** [comment]
yep mais pas l'adresse physique, on ne s'était pas compris

**Comment by kapeco** [comment]
je viens d'essayer de créer un user et ...

![2015-06-26 14_12_08-admin kapeco](https://cloud.githubusercontent.com/assets/11981295/8377000/719788ea-1c0d-11e5-991a-6d9935ae9e1a.png)

Je viens de me rendre compte d'une chose aussi lors de la création d'un user il y a 
first_name, last_name et name. je pense qu'il serait bien de supprimer name

J'imagine aussi que c'est name qui est utilisé en login , mais l'adresse email serait plus judicieuse afin d'éviter les pseudo 
J'imagine qussi que c'est name qui est repris pour savoir qui a téléchargé un fichier , dans ce cas mettre le fisrt_name+last_name

**Comment by corentin-begne** [comment]
j'ai réussi à créé un user en preprod sans erreur, quelle adresse est ce que tu utilise pour y accéder ?
name est utilisé dans toute les table pour faire la liaison des clefs étrangère pour afficherr les select dans toute les tables, si je change ça je dois changer tout mon système. mais tu peux mettre first_name + last_name dans name si tu veux. Je peux également changer au login pour mettre le mail à la place du name.

**Comment by kapeco** [comment]
Ok change pour le Login 
Du coup nous n'utiliseront pas le name en utilisateur , ça sera utilisé dans tes requêtes

**Comment by kapeco** [comment]
Je n'arrive toujours pas à créer un user , j'ai vu le tiens , et je n'arrive même pas à le supprimer, même erreur que lors de la création
j'utilise le liens de preprod et je suis sous chrome

**Comment by corentin-begne** [comment]
j'ai modifié sur le front pour que l'on puisse se loger avec l'email.

**Comment by kapeco** [comment]
que l'on puisse ou obligatoire ?

**Comment by corentin-begne** [comment]
obligatoire mais sur l'admin j'ai laissé le name

**Comment by kapeco** [comment]
ok on changera plus tard
