### ISSUE TITLE
Pastille

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#33]
Salut coco
J'ai pensé a une petite nouveauté qui je pense ne prendra pas trop de temps mais améliorera considérablement l'expérience diagnostiqueur
dans le menu suivant
![2015-06-22 09_02_26-accueil](https://cloud.githubusercontent.com/assets/11981295/8276983/a0570c12-18bd-11e5-8358-0053422f1da0.png)
Changer la couleur de la puce en rouge pour les liens odm et diagnostics quand il y a une nouvelle demande non encore traité

**Comment by corentin-begne** [comment]
Je ne peux pas, la puce est une image que j'ai récup de ton ancienne interface.

**Comment by corentin-begne** [comment]
sinon je peux mettre le compte en attente entre parenthèse à côté quand yen a.

**Comment by kapeco** [comment]
yep mais en rouge
sinon je te fait la même image mais en rouge et tu jongles

**Comment by corentin-begne** [comment]
envoie

**Comment by kapeco** [comment]
![arrowhoverred](https://cloud.githubusercontent.com/assets/11981295/8289162/ee2a6670-191a-11e5-983d-e1cafe2f721e.gif)

**Comment by corentin-begne** [comment]
ok jte fais ça après, alors la pastille plus le nb entre parenthèse, je le met en rouge aussi ?

**Comment by kapeco** [comment]
yep

fais gaffe je viens juste de remettre a jour la pastille,(plus rouge maintenant)

**Comment by corentin-begne** [comment]
ok tkt façon je vais bouffer :D

**Comment by kapeco** [comment]
bonap ;)

**Comment by corentin-begne** [comment]
en fait ya un normal et un hover normalement.

**Comment by kapeco** [comment]
Tu as les deux là non ? 
Celui d'origine plus le nouveau que j'ai mis

**Comment by corentin-begne** [comment]
ben l'autre je l'avais dl avant que tu changes

**Comment by corentin-begne** [comment]
c'est en preprod avec une seule image

**Comment by kapeco** [comment]
nickel , juste une petite chose , laisser le liens de le même couleur de base , faut juste que la puce et ce qu'il y a entre parenthèse (parenthése compris) soit rouge
ensuite, j'ai validé un odm et la ça m'ouvre une nouvelle page avec mon google agenda ??
![2015-06-23 11_23_20-](https://cloud.githubusercontent.com/assets/11981295/8302957/abbc23de-199a-11e5-830f-bbe9c2ce8f94.png)

ça peut être pas mal mais étant donné que je valide déjà une date sur kapeco , quel est l'interet d'ouvrir google agenda , car j'imagine que si je modif sur google agenda , ce n'est pas répercuté sur le site

**Comment by corentin-begne** [comment]
ok je change la couleur ce soir. Oui j'ai mis le lien vers le google agenda qui s'ouvre dans une autre fenêtre, si jamais on veut rajouter des infos ou simplement pour vérifier que tout est ok, de toute manière l'user pourra toujours modifier les infos ultérieurement et ça ne sera pas répercuté sur le site, je trouvais que c'était pratique.

**Comment by kapeco** [comment]
non c'est la merde faut retirer ça stp

**Comment by corentin-begne** [comment]
comme tu veux, je le vire tout à l'heure

**Comment by corentin-begne** [comment]
envoie la pastille plus claire à mettre en normal aussi stp

**Comment by kapeco** [comment]
ben la pastille plus claire c'est celle déja existante sur le site, y a pas de soucis avec les pastilles

**Comment by corentin-begne** [comment]
non mais celle en belur j'en ai deux, une normal et une hover, pour la rouge j'en ai qu'une, la plus foncée, il m'en faudrait une rouge plus claire pour que ça rende mieux.

**Comment by kapeco** [comment]
ah ok je pige mieux :)
je te fais ça tout a l'heure , là je dois sortir

**Comment by corentin-begne** [comment]
c'est fait, sauf pour la pastille.

**Comment by kapeco** [comment]
voilà les pastilles

![menu_arrow_red](https://cloud.githubusercontent.com/assets/11981295/8325322/de3aab1e-1a58-11e5-8e92-fc70f2fafe51.gif)
![menu_arrow_red_hover](https://cloud.githubusercontent.com/assets/11981295/8325321/de3a3850-1a58-11e5-843f-e8bb4ccd201d.gif)

**Comment by corentin-begne** [comment]
c'est en preprod

**Comment by kapeco** [comment]
je vais tester ça ;)

**Comment by kapeco** [comment]
nickel
