### ISSUE TITLE
Preprod out

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#34]
Forbidden

You don't have permission to access / on this server.

**Comment by corentin-begne** [comment]
je sais pas pk, j'ai fais un ticket à OVH :(

**Comment by kapeco** [comment]
ok

**Comment by corentin-begne** [comment]
c'est réparé

**Comment by kapeco** [comment]
j'ai vu ça , tu sais ce qui s'est passé ?

**Comment by corentin-begne** [comment]
tu vas te marrer, fichier suspect .nfs0000000006659b69000071be je l'ai delete. Il était dans un dossier que j'avais filé en dédié à démone pour qu'elle puisse mettre son site de créa, apparemment elle s'en sert encore et up de la merde xD

**Comment by kapeco** [comment]
whouaaaaaaaaaaaaaaaaaaaaa  !!!!!!!!!!!!!!! Démone !!!!!
ça fait un baille , toujours en contact avec elle ou ça date de la préhistoire ? :D

**Comment by corentin-begne** [comment]
ouais non c'est historique xD . Bon il est de nouveau fermé, fichier suspect .nfs00000000065e9a44000079b5 mais pas dans le dossier de demone cette fois, il va falloir que je matte les logs pour voir d'où ça vient, fait chier !

**Comment by kapeco** [comment]
tu m'étonnes !

**Comment by corentin-begne** [comment]
bon je crois que j'ai trouvé d'où venait la faille, je fermé le sous domaine et j'ai réouvert l'hébergement.

**Comment by kapeco** [comment]
ok

**Comment by kapeco** [comment]
Forbidden

You don't have permission to access / on this server.

**Comment by corentin-begne** [comment]
réouvert

**Comment by kapeco** [comment]
yes thx petit ;)

**Comment by kapeco** [comment]
out again :(
