### ISSUE TITLE
ODM : levée d'un lièvre

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#35]
Krro Krro
J'ai levé un lièvre dans le formulaire de création des odm

![2015-06-25 09_58_46-ordre de mission](https://cloud.githubusercontent.com/assets/11981295/8350015/0581c09e-1b22-11e5-849f-b2635d287ecc.png)
déjà sous la date d'intervention mettre le type de bien 
et au dessous y mettre le numéro de lot

Mais le soucis est que pour une maison y a pas de numéro de lot sauf si en copropriété

donc ça donne ça : 

- Date d'intervention souhaitée ( ça on n'y touche pas)
- Type de bien : 
1) si "maison" alors demander si en copropriété
1.A) si copro alors demander le numéro de lot
1.B) si pas copro ne pas demander le numéro de  lot

2) si "appartement" ne pas demander si en copropriété car ça l'est toujours , donc demander le numéro de lot
2.1) demander si il y a une cave, si oui demander le numéro de lot de la cave
2.2) idem pour un parking
2.3) idem pour un box

puis comme d'hab on demande les infos de l'appartement

Et ensuite on demande l'année de construction

**Comment by corentin-begne** [comment]
merci pour ces infos, t'aurais pu me les donner avant, ça fait des grosses modif je dois tout recheck :(

**Comment by kapeco** [comment]
suis dsl , mais c'est une ommission

**Comment by kapeco** [comment]
Bon suite à la prez de hier avec Efficity voici d'autres modifs à faire sur le formulaire d'ODM
la premiere partie reste comme ça : 
![1-](https://cloud.githubusercontent.com/assets/11981295/8504608/b273c55a-21d4-11e5-9ffc-c4fe1ce9fe2c.png)
Ensuite arrive la partie "type de bien " avec ce qu'on à vu au dessus
Puis année de construction

Puis arrive la partie mission , avec les case précochées par défaut selon les même critéres que la partie devis.
C'est coches doivent rester manipulable par l'utilisateur , mais c'est un gain de temps et surtout des risques d'ommission en moins car les agents immobiliers ne savent pas toujours ce qu'il faut cocher

Et enfin on laisse le dernier bloque comme il est

**Comment by kapeco** [comment]
Bon j'ai réfléchi à quelque chose de plus simple 
Pour le numéro de lot : juste un seul champs : petit textarea, 
Car si y a plusieurs parking cave etc .... Alors il manquera des champs

**Comment by corentin-begne** [comment]
j'ai bien avancé sur cette partie, tu peux déjà check si le fonctionnel correspond à ce que tu veux et je finaliserais le reste. J'ai pas encore fait le check auto pour les missions.

**Comment by kapeco** [comment]
ok je check demain , là j'ai une mission  ;)

**Comment by corentin-begne** [comment]
ok amuse toi bien ;)

**Comment by corentin-begne** [comment]
j'ai fais l'enregistrement en bdd, la modif de l'arlet et la prise en compte de la modif à l'édition, il me reste donc le check auto des missions.

**Comment by corentin-begne** [comment]
pour les missions, je n'ai pas l'info pour le gaz et les termites, je ne sais pas quel règle appliquer pour Assainissement et Etat de lieux et j'ai ajouté Boutin.

**Comment by corentin-begne** [comment]
j'ai déjà mis en place avec les règles que je connaissais, j'ai ajouté une icone dans le fieldset des missions et quand tu cliques dessus ça fait le check

**Comment by kapeco** [comment]
yes ça a l'air pas mal , par contre au lieu de l'icone faudrait que ce soit automatique

Concernant le champ "Notes" , faudrait le mettre un peut plus grand et à la fin comme j'avais demandé , c'est à dire après "règlement"
L'auto complétion des villes  en fonction du CP serait un plus comme dans le module "devis" pour le choix des termites ou non
Comme ça , ça check termite ou pas , en fonction de ... comme dans la partie "devis"

**Comment by corentin-begne** [comment]
je vais voir pour le mettre en auto , je vire l'icône du coup ?
je mettrais Notes tout en bas, ça sera en dessous de toute les infos notaires si ce type de règlement est sélectionné.
Je vais voir pour te remettre l'autocompletion des villes avec les termites.
Tu m'as pas dis pour Gar, Assainissement et Etat des lieux ce que j'en fait.

**Comment by kapeco** [comment]
Ah oui 
Pour gaz , ne pas cocher  mais mettre une Astérix avec un petit libellé juste au dessous du cadre "*verifier si ce diagnostic doit être réalisé "
Pour assainissement ne rien cocher par défaut pour le moment , idem pour état des lieux 

Oui vite l'icône

**Comment by corentin-begne** [comment]
c'est fait !!!

**Comment by kapeco** [comment]
je check ça

**Comment by kapeco** [comment]
1) Première remarque, tu peux retirer (cave parking box) pour une maison comme on met un zone alphanumérique pour le numéro de lot
2) L'user de l'agence n'a pas recu de mail de confirmation que l'odm est validé par franck
3) toujours côté agence , la puce du liens ODM n'est pas passée en rouge avec les chiffre en rouge entre ()

**Comment by corentin-begne** [comment]
1) ben je l'ai mis que pour la maison donc je les vires ? je mets que le numéro de lot ?
2) je l'ai reçu, tu as du  le recevoir aussi, matte dans mandrill je le vois.
3) c'est dans quelle circonstance que je dois mettre le chiffre en rouge ? comme le diag ?

**Comment by kapeco** [comment]
1) oui tu vire et tu laisse numéro de lot comme c'est
2) effectivement je l'ai reçut mais après un petit moment
3) voir https://github.com/corentin-begne/kap/issues/69

**Comment by corentin-begne** [comment]
1) c'est fait
2) :p 
3) c'est pas vraiment possible ça car le système n'est pas prévue pour et même si je le mets en place, ça ne fonctionnera que pour le premier agent qui accédera à l'interface car les odm ne sont pas associés aux users. Pour que ça fonctionne, il faut une solution bien lourde, que je gère en plus une table de vue user/odm

**Comment by kapeco** [comment]
1) Parfait
2) idem
3) quoi c'est pas associé aux users ?? les users ne doivent pas voir les autres odm des autres users , même au seins de la même agence

**Comment by corentin-begne** [comment]
enfin si c'est associé à l'user qui l'up mais cette info n'est pas utilisée dans l'interface, actuellement ça liste tous les odm de l'agence

**Comment by corentin-begne** [comment]
je vais changer et du coup ajouter un champ de vue là ça fonctionnera

**Comment by corentin-begne** [comment]
par contre je les mets tous en lu dès qu'il affiche l'interface ou il faut qu'il parcours les page si il y en a ?

**Comment by kapeco** [comment]
qu'il parcours les page si il y en a plusieurs

**Comment by corentin-begne** [comment]
ok mais je comprends pas le but de le mettre en rouge alors que c'est lui qui le crée, il ne verra jamais le lien car li'nterface se rafraichie à la fin de la création.

**Comment by kapeco** [comment]
non , mettre en rouge quand le diagnostiqueur a validé l'odm, pas à la création sinon effectivement ça ne sert a rien

**Comment by corentin-begne** [comment]
d'accord

**Comment by corentin-begne** [comment]
bon ben j'en ai pour un moment à mettre ça en place, j'avais pas fait la mise à jour auto du nb dans le menu en mode diag, en même temps je ferais l'affichage pour la partie diag.

**Comment by kapeco** [comment]
ça marche, en attendant si tu veux pousser le reste en prod , vas y

**Comment by corentin-begne** [comment]
je peux pas, je fait tout sur la même branche mais une fois que tu auras validé cette partie on pourra. Par contre j'ai fais beaucoup de changement en bdd ça risque de mettre un moment et il faudra que je del tous les diags

**Comment by corentin-begne** [comment]
est ce que tu veux que les éléments qui sont dans le listing et qui sont "vue" aient un background différent, genre rouge transparent qui disparaitrait sur le retour de la maj de leur status avec le count ?

**Comment by kapeco** [comment]
Je ne vois pas trop ce que ça peut donner mais ne t'embête pas

**Comment by corentin-begne** [comment]
ok, je mets quand même un timer de 0.5 sur l'envoi de la requête pour ne pas que ça mette en lue si il zaap les pages

**Comment by corentin-begne** [comment]
c'est fait pour la partie odm pour agence et diag, je me met sur la partie diag

**Comment by kapeco** [comment]
La partie diag ? Côté agence tu parles ?

**Comment by corentin-begne** [comment]
non je parle d'afficher le nb de diagnostic en attente de dl pour les agences, dans la partie odm c'est fait pour les agences et les diagnostiqueurs

**Comment by kapeco** [comment]
Ah ok

Par contre je viens de vérifier le template du mail que l'agence revoit quand l'odm est validée :
"Bonjour,

Votre demande d'ordre de mission viens d'être validée et planifiée.
Retrouvez toutes les informations sur KAPECO Missions

L'équipe KAPECO."

Faudrait remplacer "Retrouvez toutes les informations sur KAPECO Missions"
Par "Retrouvez toutes les informations sur KAPECO Diagnostics"

**Comment by corentin-begne** [comment]
ok j'ai changé mais j'ai laissé le lien vers missions/find derrière.

**Comment by corentin-begne** [comment]
c'est bon aussi pour la partie diagnostique

**Comment by kapeco** [comment]
Impeccable 
Go to mep aussi

**Comment by kapeco** [comment]
MEP ok
