### ISSUE TITLE
Meta

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#36]
Concernant les meta voici un peu d'info

il faut mettre tout ça : 

	<META Http-Equiv="Content-Type" Content="text/html; charset=utf-8">
	<META Http-Equiv="Content-Language" Content="fr">
	<TITLE> - Diagnostic immobilier - </TITLE>
	<META Name="Title" Lang="fr" Content="Kapeco diagnostic immobilier">
	<META Name="Description" Lang="fr" Content=" - Diagnostic immobilier - ">
	<META Name="Keywords" Lang="fr" Content=" - Diagnostic immobilier - ">

	<META Name="Language" Content="fr">
	<META Name="Reply-To" Content="contact@kapeco.com">
	<META Name="Category" Content="Environnement">
	<META Name="Robots" Content="index, follow">
	<meta name="rating" content="general" />
	<META Name="Distribution" Content="worldwide">
	<meta name="clientbase" content="worldwide" />
	<META Name="Revisit-After" Content="2 days">
	<META Name="Author" Lang="fr" Content="">

	<META Name="Copyright" Content="©">
	<META Name="Identifier-URL" Content="http://www.kapeco.com">
	<META Name="Expires" Content="never">
	<META Name="Date-Creation-yyyymmdd" Content="20091019">
	<META Name="Date-Revision-yyyymmdd" Content="20120108">
	<META name="y_key" content="515ce904ebdd2af9">

Par contre seulement certaines balise doivent être renseignée à partir du backoffice lors de l'ajout d'une page (lien)

 TITLE> - Diagnostic immobilier - </TITLE>
	META Name="Title" Lang="fr" Content="Kapeco diagnostic immobilier">
	META Name="Description" Lang="fr" Content=" - Diagnostic immobilier - ">
	META Name="Keywords" Lang="fr" Content=" - Diagnostic immobilier - ">

et  c'est deux balises sont dynamiques, la première fixé lors de la création et l'autre changeante en fonction de la date de la mise à jour de la page
META Name="Date-Creation-yyyymmdd" Content="20091019">
META Name="Date-Revision-yyyymmdd" Content="20120108">

**Comment by corentin-begne** [comment]
actuellement en bdd je n'ai qu'un seul champ nommé meta, je le met dans keyword ou dans description ? ou tu veux peut être que j'en mette deux ?
La balise title est déjà géré dynamiquement, elle reprends le champ name de l'article ou un titre correspondant à l'action pour l'odm, diag, devis etc et sinon j'ai mis ton titre par défaut.

**Comment by kapeco** [comment]
ah zut ça n'affiche pas correctement ce que  j'ai mis, j'édite ça

**Comment by corentin-begne** [comment]
j'ai modifié le champ meta en keywords et j'ai ajouté le champ description dans la table link. j'ai tout pluggé dans les meta correspondante et j'ai plugé le created_at et le updated_at sur les deux autres meta qui sont mis à jour avec les liens. C'est en preprod tu peux test.

**Comment by kapeco** [comment]
Très bien mais faut permettre aussi le title

**Comment by corentin-begne** [comment]
title c'est name

**Comment by kapeco** [comment]
Parfait :)

**Comment by kapeco** [comment]
Vla le bordel :!!!!! 

j'ai changé tout les name puisque c'est la balise title , mais tout mes noms de liens ont changés aussi !!!!
name  = nom du lien

il me faut donc title  = balise meta title

c'est urgent ça , merci d'avance

**Comment by corentin-begne** [comment]
oui name c'est aussi le nom sur le front

**Comment by corentin-begne** [comment]
je pensais que tu le savais ça ...

**Comment by kapeco** [comment]
faut dissocié alors sinon c'est pas possible , je viens de tout effacer cette partie que j'avais fait mais faut que je puisse la refaire vite proprement pour que le ref nat recommence correctement

**Comment by corentin-begne** [comment]
ok jte fais ça t'al

**Comment by kapeco** [comment]
merci
