### ISSUE TITLE
New user grant access

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#38]
Salut mon coco Lapin Krrrrrrr

étant donné que l'on va travailler avec des réseau comme Orpi, la demande des dirigeant et de pouvoir visualiser ce que font les différentes agences, c'est à dire avoir une vu de qui fait quoi , agence par agence
Donc j'imagine un utilisateur "patron d'agences" , qui une fois logué, puisse voir un liens
"Diagnostics" , lorsque q'uil clic sur le liens, il voit la liste des agences dont il est le bosse
Lorsqu'il clic sur une agence, il voit la liste des utilisateur(commerciaux) de l'agence en question
Et quand il clic sur un utilisateur il voit la liste des diag de l'utilisateur

**Comment by corentin-begne** [comment]
Avec ce que l'on a mis en place ce n'est pas possible ce que tu me demande car un user est rattaché à une seule agence, ce sont les agences immobilières/franchises qui sont rattachées entre elles. Si tu veux un user de ce genre il faut que je refasse le système des permissions, la structure de mes tables et revoir toute mes requêtes ainsi que le traitement .... :(
Par contre, on pourrait peut être faire un user qui est rattaché à une agence immobilière mère et qui est elle même rattachée à d'autres agences immobilières au lieu d'être rattaché à des agences franchise et on lui mettrai la permission admin/agence pour l'identifier.

**Comment by kapeco** [comment]
si on arrive au même résultat pourquoi pas, sauf que ce user n'est pas forcément rattaché à un agence mère, faut garder énormément de souplesse dans les droits, comme je te l'avais dit déjà , car c'est la dessus que va se faire une grosse partie du système.

ce qu'il faut c'est pouvoir avoir exactement ce que j'ai écrit plus haut.

**Comment by corentin-begne** [comment]
ben ya de la souplesse déjà là tu peux mettre autant de niveaux que tu veux dans deux type de categories diag et agence mais ce que tu demande ne correspond pas au fait qu'un user est associé à une agence comme tu me l'as décrit et je ne conçois pas des système plus complexe que nécessaire juste au cas où mais si tu me l'avais dis j'aurais fais autrement là ça implique que je refonte tout quasiment.

**Comment by kapeco** [comment]
je ne pensais pas qu'il y aurait une refonte totale pour ça  ....

**Comment by corentin-begne** [comment]
ça supprime la clé étrangère de la table user sur la table agency, quasiment toute les requêtes et le fonctionnel est basé sur ça donc je dois repasser sur toute les interfaces, les actions, les requêtes et modifier en fonction.

**Comment by kapeco** [comment]
ok , milles excuses alors :(

**Comment by kapeco** [comment]
bon je reviens la dessus, c'est quasiment ce qu'ont a actuellement en tant que diagnostiqueur du coup
"Donc j'imagine un utilisateur "patron d'agences" , qui une fois logué, puisse voir un liens
"Diagnostics" , lorsque q'uil clic sur le liens, il voit la liste des agences dont il est le bosse
Lorsqu'il clic sur une agence, il voit la liste des utilisateur(commerciaux) de l'agence en question
Et quand il clic sur un utilisateur il voit la liste des diag de l'utilisateur"

Je reprend ce que tu as dit : "Par contre, on pourrait peut être faire un user qui est rattaché à une agence immobilière mère et qui est elle même rattachée à d'autres agences immobilières au lieu d'être rattaché à des agences franchise et on lui mettrai la permission admin/agence pour l'identifier."

c'est bien ça après coup krr

Donc pour résumer les fonctions : 

1) Un patron de plusieurs agence => visualise ses agences => visualise ensuite les users de chaque agence => et visualise la liste des diagnostics de chaque user

2) Une patron d'une seule agence (donc un niveau intermédaire)=> visualise ensuite les users de son agence => et visualise la liste des diagnostics de chaque user

**Comment by corentin-begne** [comment]
Ok donc j'ai ajouté la permission manager et la possibilité d'associer des agence immobilière à d'autres agence immobilière grâce au lien "Agences groupe" dans le BO. 
De cette manière si tu crée un user et que tu lui met la permission manager, si il est attaché à une agence immobilière qui n'est ratatché à aucune agence immobilière (en source) alors il est dans ton cas 2) et si l'agence est rattaché à d'autres agences alors il est dans le cas 1). 
Je t'ai mis en place tout le fonctionnement comme tu me l'a décrit, jte laisse test.
Concernant les stats, si tu veux un historique permanent il faudrait peut être voir à les tracker par analytics ou mettre en place un système d'event interne mais bon c'est dommage si on utilise déjà analytics.

**Comment by kapeco** [comment]
bon ça a l'air très bien ça :)
il y a juste qu'il faudrait que je puisse donner le droit de DL des diags même si ils ne sont pas payé à certains manageur, du coup j'imagine que c'est juste un droit "download" a ajouter en plus et que j'affect a l'utilisateur de mon choix , qu'en pense tu ?

Concernant les stats via analytics , je ne sais pas si un manageur pourra avoir une vu des diags de l'ensemble de ses collaborateurs  ..

**Comment by corentin-begne** [comment]
pour tous les diags ou que pour certains ? si c'est pour tous on peut faire comme ça.
je peux mettre en place des stats internes si tu veux, quels event tu veux que je log et avec quelles infos ? pareil pour les odm

**Comment by corentin-begne** [comment]
c'est fait pour la permission download supplémentaire pour les managers. 
Pour les events, ça vaudrait le coup de faire une autre issue et tu me liste ceux que tu veux avec les data associées.

**Comment by kapeco** [comment]
ok je ferais un autre issue pour ça , c'est mieux

Par contre une question , j'ai vu qu'on peut mettre sous une agence , plusieurs agences , ça c'est mega top !!!

Agence_source => agency=> users

Par contre du coup je me retrouve un peu bloqué car dans un cas precis avec efficity on à ça en deux fois 
Agence_source_1 => agency_1=> users
Agence_source_2 => agency_2=> users

et il faudrait que je puisse avoir un user qui puisse voir ce qu'il y a dans Agence_source_1 et 2

J'ai donc essayé de créer : 
Agence_source_0=> agency(qui est Agence_source_1 )
Agence_source_0=> agency(qui est Agence_source_1 )

Mon user de Agence_source_0 liste bien Agence_source_1 et deux , mais quand il rentre dedans il ne voit plus agency_1 et 2 et leurs users

Donc question : on peut aller jusqu'a combien de niveau ? juste 2 ou est-il possible d'enchainer autant qu'on veut ?

l'idéal serait de pouvoir enchainer comme on veut

**Comment by corentin-begne** [comment]
oui le manager ne voit que les agences qui lui sont directement associé, ça ne fonctionne pas en cascade en tout cas au niveaux du regroupement mais tu peux faire autant de niveau que tu veux.

**Comment by corentin-begne** [comment]
tu voudrais qu'il puisse voir toute les agences de tous les niveaux ?

**Comment by kapeco** [comment]
ah oui faut que ca fonctionne en cascade

**Comment by corentin-begne** [comment]
c'était pas vraiment prévu, je vais voir ce que je peux faire.

**Comment by kapeco** [comment]
ça serait top !

**Comment by corentin-begne** [comment]
sympa tu lui passera le bonjour aussi !
bon normalement c'est fait, test bien dans tous les cas de figure.

**Comment by kapeco** [comment]
Autocompletion de quoi ?

**Comment by kapeco** [comment]
![2015-07-21 08_29_07-rechercher un diagnostic](https://cloud.githubusercontent.com/assets/11981295/8794303/a22c596c-2f82-11e5-842e-014fef22d55d.png)

Bon y a un soucis de hiérarchie , tous les niveau sont au même niveau :(
je devrais voir  : 

efficity indépendant => avec dedans "efficity pierre lièvre"
                                => "efficity alain dupont"
Efficity salarie => avec dedans "efficity ludovic franoux" et "efficity gilbert montanier"

Si tu veux test essaye avec le compte suivant : mgourdel@efficity.ru (m^me pass qu'a la création des users)

**Comment by corentin-begne** [comment]
ah bah oui je croyais que le but était que le manager vois les agences auxquelles il est directement rattaché et celles auxquelles elle sont rattachées et ainsi de suite, donc toutes les agences sont listée, les niveaux ne sont pas explicite pour faire ce que tu me demande ça me demande beaucoup de dev et ça ne rentre pas dans le fonctionnement de l'interface, je devrais faire un gros cas spécial :(

**Comment by kapeco** [comment]
ça ajoute un niveau de hierarchie dans ce cas là
mais l'idée est de visualiser un systeme pyramidal, ou chacun peu voir ce qu'il a au dessous de lui si il est manageur mais en respectant la vision hierarchique  et ça sur x niveaux

**Comment by corentin-begne** [comment]
ok mais ça me demande un gros dev, je ne sais pas quand j'aurai le temps de faire ça

**Comment by corentin-begne** [comment]
c'est fait ! par contre le pb avec ton truc c'est que le super manager ne peut accéder que aux users des agences finale (qui ne sont pas des sources) sauf si il cherche l'agence dans l'autocompletion.
Il faudra s'assurer qu'une agence n'ai qu'une seule source sinon ça va tout péter.

**Comment by kapeco** [comment]
hum ... d'après ce que je comprend ca ne va pas trop le faire, faut qu'il puisse voir les users de chaques niveau ... je vais test

**Comment by corentin-begne** [comment]
c'est pour ça que dans la version d'avant j'vais listé toute les agences directement, parce que là en cascade seul le dernier niveau accède aux users.

**Comment by kapeco** [comment]
Bon effectivement c'est le box
si on prend plievre@efficity.ru qui est le manager d'une agence  (droit : manager)
si il se log il voit deux users qui sont au-dessous de lui (normal) , mais n'est pas lui même un "user" apparament car il ne voit pas les diag que je lui met 
si je lui ajout les droits agence , il se voit comme un  user classic mais ne voit plus les autres user

donc rien ne fonctionne en fait  :(

**Comment by corentin-begne** [comment]
les manager ne sont pas des users

**Comment by kapeco** [comment]
ils peuvent être les deux

**Comment by corentin-begne** [comment]
je n'ai pas eu cette info et ça implique que je refasse une bonne partie et de toute façon il ne se verra jamais car il ne voit que les users des agences qui sont sous la sienne et qu'il a sélectionné, le but d'un manager sinon il se fait un user agence ....

**Comment by corentin-begne** [comment]
pour le manager normal lui je peux l'ajouter dans les users mais pas le super manager.

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
qu'est-ce qui est fait ? je ne vois pas de différence

**Comment by corentin-begne** [comment]
ce qui est fait est que quand l'user a les droits agence et manager et qu'il n'est pas super manager, il se voit dans la liste des users.

**Comment by corentin-begne** [comment]
au niveau fonctionnel j'ai fais ce que tu m'as demandé, niveau accès et hiérarchie, ça fait déjà deux fois que je le refais et si je fais ce que tu me demande je dois réussir à supprimer tout ce que j'ai fais dans la partie diagnostic et faire une nouvelle interface complexe qui va me demander plein de dev

**Comment by corentin-begne** [comment]
je te rappel, même si tu le sais, que ce ne sont pas des maquettes photoshop que je fais, à chaque fois ya plein de dev associé

**Comment by kapeco** [comment]
Je disais ça au cas ou ça soit plus simple car pour le moment je ne vois rien qui fonctionne correctement de ce côté là
Qu'elle est la différence entre manager et super manager pour toi ?
quand quelqu'un est manager d'une agence il voit tout ce qu'il y a dans sont agence, mais si il y a d'autres agences sous la sienne il doit pouvoir le voir aussi, la vu doit respecter les différentes entités
Si y a un truc pas clair pour toi , reformule ou pose des questions avant de te lancer dans le dev, sinon c'est sur que tu travails pour rien mon petit , c'ets pas le but

**Comment by corentin-begne** [comment]
la différence entre manager et super manager  et que l'agence du manager n'a pas d'agence en dessous d'elle.
oui on aurait mieux fait de s'appeller c'est sur mais j'avais pas de question, j'ai suivit ce que tu as décrit en te l'expliquant derrière et tu ne m'as pas dit que ça ne correspondait pas même l'inverse, je te relève les incohérences après mais je fais d'abord ce que tu me demande, c'est à toi, pour moi, de relever les problème et de trouver une solution avant de me demander de faire des trucs, normalement me filer les maquettes avec les fonctionnements définit là je galère pour rien et c'est pas le premier coup mais là ça va être super bloquant et je peux pas faire de mep tant que c'est pas réglé.

**Comment by corentin-begne** [comment]
et puis tu m'avais bien dit comme le diagnostiqueur et lui ne se voit jamais, j'avais fait qu'un niveau du coup après j'en ai fait plusieurs rassemblé sur un pour pouvoir accéder à tous les users de chaque agences directement comme le diagnostiqueur

**Comment by kapeco** [comment]
ok ok..... 
je vais te faire un donc complet sur ça, si tu peux passer le reste en prod fait le , ne modif plus rien sur ça, tant que je n'ai aps fait le doc , il y au ra donc surement des changement apr rapport à ce qui a déja été dit , mais au fond ça sera définitif , après une séance de question réponse.

J'attaque

**Comment by corentin-begne** [comment]
ok ça marche.
bah tant que tu mets pas les permissions manager ça ne devrait pas avoir d'incidence.
Faudrait refaire un tour en mode diag/agence pour être sur que tout fonctionne bien sur cette partie.
valide moi ça, je termine les functions user et on pourra faire une mep

**Comment by kapeco** [comment]
ça a l'air nickel

**Comment by corentin-begne** [comment]
j'ai refais une mep pour le bouton back, tu peux check

**Comment by kapeco** [comment]
c'est tout bon
