### ISSUE TITLE
Suppression ODM

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#39]
En tant que diagnostiqueur , il faut que je puisse supprimer un ODM de la liste quand je veux

**Comment by corentin-begne** [comment]
j'ai considéré que si il était réservé il ne pouvait plus être supprimé pour garder une trace vu qu'il aura du être fait normalement.

**Comment by kapeco** [comment]
non pas forcément de trace car on ne va pas garder indéfiniment un ODM en liste

**Comment by corentin-begne** [comment]
ok je change ça

**Comment by kapeco** [comment]
merci fiston
