### ISSUE TITLE
Dossier images

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#40]
pour info sur le site de prod , dans le dossier images , j'ai ajouté un dossier "sign" , il nous sert pour nos signature mail

**Comment by corentin-begne** [comment]
ok bah faudra que je le répercute en dev pour pas que ça écrase dans les prochaines mep

**Comment by kapeco** [comment]
yes c'est pour ça que je t'en informe mon petit ;)

**Comment by kapeco** [comment]
Jai aussi ajouté 3 fichiers : sitemap.xml, Paste.html et robot.txt

il faut que je rajoute les fichier de vérification pour google, mais il va surement falloir ajouter du code dans la home, je prépare le ticket

**Comment by kapeco** [comment]
c'est bon , plus de fichier de vérif google puisque tu as ajouté la basile hier
