### ISSUE TITLE
user attaché à une agence

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#41]
J'ai crée deux users que j'ai attaché à la même agence, cependant lorsque je suis en diagnostiqueur et que je vais dans diagnostics, je vois bien la liste des agences , et quand je clic sur l'agence en question, je ne vois pas les différents users a qui je peux envoyer le diag  !

**Comment by corentin-begne** [comment]
heu cette partie là n'existe pas, quand tu cliques sur une agence, tu vois et tu peux uploader des diag pour l'agence en question ce n'est pas associé à un user. Après en tant qu'agence dans le listing tu les vois tous, tu ne m'as jamais parler de l'associé à un user.

**Comment by kapeco** [comment]
ben si pourtant c'etait un des premier trucs demandé, avant meme de travailler sur gitub il me semble

**Comment by corentin-begne** [comment]
il a toujours été question d'up pour une agence et en testant tu m'as jamais dis que ça ne correspondait pas.

**Comment by kapeco** [comment]
parceque j'attendais de pouvoir créer un user pour tester

**Comment by corentin-begne** [comment]
par contre je t'avais demandé si li fallait rattaché les dl aux user pour avoir la liste de ceux de l'agence qui ont dl et tu m'as bien dis que oui et de mettre la liste au survol quand on est admin, si ct rattaché à un user il n'y aurait pas eu de liste.

**Comment by corentin-begne** [comment]
et puis c'est le même fonctionnement d'accès que les odm et je ne comprends pas pk associé l'up à un user, c'est l'agence qui reçoit le diag pas l'user particulièrement enfin sinon je capte vraiment rien au truc

**Comment by kapeco** [comment]
si c'est bien l'user qui recoit , pas l'agence

**Comment by corentin-begne** [comment]
J'ai pas compris ça comme ça et si je relis les issue concernant l'interface des diags je ne vois pas l'info plutot la mienne qui se confirme car tu dis bien  " Page avec la liste des diagnostics réalisés pour une agence " donc pour moi, comme les odm, on up pour l'agence et les user associé peuvent y accéder. De ce que j'avais compris les users sont déterminé par des droits d'accès mais tout se passe d'agence à agence et quand je me suis mis en cas réel je trouvais ça logique que tous les users de l'agence y ait accès (d'où l'historique des dl par user) et pareil pour l'odm.

**Comment by corentin-begne** [comment]
ce que je comprends pas c'est que j'en ai parlé explicitement et rien dans mon interface ne pouvait supposé ton fonctionnement ... ça me fait beaucoup de modif, il faut que je repasse sur toute la partie diag si je change ça

**Comment by kapeco** [comment]
ben si car jai ma liste d'agence et quand je clic je vois les diags, comme je n'avais pas encore fait deux users , je pensais qu'on voyé les diags par defaut comme y avait qu'un seul user

**Comment by corentin-begne** [comment]
ben non la liste d'agence tu me l'a fait mettre à la fin, au début il n'y avait que le champ de recherche qui permettait de trouver une agence pour lister tous ses diags, on a pas parlé des users et dans l'interface il n'y a pas de colonne indiquant a quel user est le diag

**Comment by kapeco** [comment]
bon les infos se sont perdu car j'avais deja dit et c'est pour ça que je l'ai redit.
mais il faut que ça fonctionne comme ça , c'est le principe de base

**Comment by corentin-begne** [comment]
dans ce cas il faut bien définir dès le début, c'est ce que je demandais au début de l'issue, avec le reste ça commence à faire beaucoup, je t'ai fais un super tarif mais c'est sans devoir refaire la moitié de ce que j'ai fais :( normalement il restait que la partie recherche d'agence et depuis je t'ai fais plein de trucs en plus, je trouve que c'est un peu abusé ...

**Comment by kapeco** [comment]
retirons la partie recherche d'agence alors car pour le coup vu comment tu as fait les reste et comment ça doit être , elle n'est plus primordiale par rapport au reste 
Y a des choses qui avaient étaient évoquées, d'autres qui sont arrivées en plus , suis dsl, fait un effort fiston , fait ça pour ton papy ! je t'offrirais un cape toute neuve .
Appel moi quand tu peux j'ai aussi deux trois trucs à voir avec toi au tel ça sera plus simple

**Comment by corentin-begne** [comment]
Bah la partie recherche d'agence j'ai déjà fait la moitié sur le lien recherche d'agence (avec le début des tri et le listing, une partie js  ect ...) et j'ai pluggé une partie dans les diags. En fait tu as fusionné la partie recherche d'agence avec l'interface diagnostic. Jt'apellerai ce soir.

**Comment by kapeco** [comment]
ok par contre avant 20h car ce soir Terminator lol, sinon plus tard

**Comment by corentin-begne** [comment]
donc j'ai associé les diagnostics aux user. Quand t'es diagnostiqueur, tu arrive sur la liste des agences auquel ton agence est rattaché, si tu clique sur une agence sur arrive sur la liste de ses users et si tu cliques sur un user tu arrive sur la liste de ses diags et tu peux lui en up. Si tu recherche une agence tu arrive sur la liste de ses users. En mode agence l'user arrive directement sur la ilste de ses diags. Tu peux check tout ça en dev, il me reste à associer aux agence une adresse, tel car pour l'instant c'est celui du manager qui apparait.

**Comment by corentin-begne** [comment]
c'est fait, donc dans listing agence, les infos sont toute rattaché à l'agence à part l'adresse email qui est celle du manager. J'ai aussi fait la modif dans l'auto-complétion. tu peux test en dev

**Comment by kapeco** [comment]
Ok super je vais tester ca 😊

**Comment by kapeco** [comment]
Par contre je ne peux pas test car en dev je ne sais plus les login/pass

**Comment by kapeco** [comment]
En fait il faudrait un mail pour l'agence , le manager je l'attacherai à l'agence , ça sera plus simple comme ça

**Comment by kapeco** [comment]
Faudrait aussi faciliter la navigation , car lorsque je suis dans une agence puis un utilisateur et que je veux revenir à la liste des users de l'agence, faut que je recommence ma recherche depuis le début . Avoir un petit liens en haut à gauche "retour" serait sympa sur chaque niveau.

**Comment by kapeco** [comment]
quand je suis connecté en utilisateur d'une agence et que je vais dans diagnostics je vois : 

Agence Efficity Pierre Lièvre
Utilisateur Marie Christine Julien 

ces deux lignes ne doivent pas apparaitre

**Comment by corentin-begne** [comment]
c'est fait en dev

**Comment by kapeco** [comment]
putin tu m'a viré tous les utilisateurs que j'avais fait :(
je recommence le test

**Comment by kapeco** [comment]
ah non mais y a un bug je ne vois que deux agences sur les quatres ...

**Comment by kapeco** [comment]
bon c'est impec tout ça fiston ;)

il manquerait juste un truc quand on est agence, dans diagnostics on à plusieurs champs : 
Nom | Adresse | Type | Note | État

il faudrait ajouter un champ "Diagnostiqueur"

Nom | Adresse | Type | Note | Diagnostiqueur | État


et au survol du nom du diagnostiqueur on voit son mail et tel

**Comment by corentin-begne** [comment]
ok je t'ajoute ça

**Comment by kapeco** [comment]
merci

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
c'ets impec tout ça , go to prod ;)

**Comment by kapeco** [comment]
MEP ok
