### ISSUE TITLE
balise pour google

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#42]
Copiez la balise Meta ci-dessous et collez-la sur la page d'accueil de votre site. Elle doit être placée dans la section <head>, avant la première section <body>

< meta name="google-site-verification" content="fCO2DLfhlHSGfrrWOVUedAeYyWr_cG7u3U4fOM0XNI4" />

**Comment by corentin-begne** [comment]
?

**Comment by kapeco** [comment]
edit mon post tu veras le détail

**Comment by kapeco** [comment]
voila j'ai ajouté un espace après le < du début

**Comment by corentin-begne** [comment]
ok tu la veux que sur la homepage ?

**Comment by kapeco** [comment]
ben ouais pour le moment , je ne sais pas trop

**Comment by corentin-begne** [comment]
c'est fait donc que sur l'url http://www.kapeco.com/

**Comment by kapeco** [comment]
merci c'est impec
