### ISSUE TITLE
balise title error

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#43]
![2015-07-01 11_50_13-admin kapeco](https://cloud.githubusercontent.com/assets/11981295/8451937/7072ff34-1fe7-11e5-8c58-9a1fc14bef0c.png)

**Comment by corentin-begne** [comment]
c'est corrigé, je l'ai fait direct en prod faudra pas que j'oublie de le remettre dans le project.

**Comment by kapeco** [comment]
merci :)
