### ISSUE TITLE
couleur des faux liens

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#44]
![2015-07-01 12_30_09-rechercher un diagnotique](https://cloud.githubusercontent.com/assets/11981295/8452642/fce3fa5e-1fec-11e5-9c5a-dddd3ed7a58b.png)

Aujourd'hui c'est moche

Il faudrait que la couleur des liens soient dans les tons gris comme ceci
![2015-07-01 12_31_38-immo en belgique_ acheter ou louer un bien immobilier - logic-immo be](https://cloud.githubusercontent.com/assets/11981295/8452663/2d402a06-1fed-11e5-8b04-2b0bf69b589f.png)
Avec le même effet au survol le texte est souligné et une fois visité la couleur reste toujours du même Gris : EDEDED
Reduire aussi la taille de la police d'un point

**Comment by corentin-begne** [comment]
ok jte change ça t'al

**Comment by kapeco** [comment]
Merci
