### ISSUE TITLE
Différents point concernant le SEO

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#45]
1) dessous des champs d'identification on a le liens "Mot de passe oublié ? " qui pointe vers http://www.kapeco.com/password?PHPSESSID=16j8kskk5uoa9eclpqba6mrlo5

Page not found => 404

2) Pour les phpssehid https://moz.com/ugc/removing-phpsessid-from-an-url

3) On a un problème avec la page d'accueil qui est accessible aussi bien par http://www.kapeco.com/ que http://www.kapeco.com/diagnostic-immobiliers/accueil
il faudrait donc qu'elle soit accessible avec uniquement l'url www.kapeco.com, peut etre faire une exception dans le code pour cette page 

4) Problème avec les balises H1 absentes
certaine page n'en contiennent pas 
ex:  http://www.kapeco.com/autres-controles/assainissement
J'avais sollutionner ce problème dans l'ancienne version, en dissociant le titre et le contenu de la page, j'avais un éditeur pour chacune des deux partie , et le titre était balisé par H1 en dur 

5) Problème avec les balises H1 en trop
ex: http://www.kapeco.com/diagnostic-immobiliers/loi-carrez
![2015-07-01 14_34_32-metrage loi carrez - kapeco](https://cloud.githubusercontent.com/assets/11981295/8454529/5ea981c6-1ffe-11e5-9b71-07d0d8378b5b.png)
Je n'ai pas accès aux balises de la page en mode édition pour supprimer manuellement les balises

**Comment by corentin-begne** [comment]
1) bah ouais on a pas fait l'interface (je vais le virer)
2) ouais mais là on est sur un mutu ovh, tu avait pas fait quelque chose avant pour pas l'avoir, c'est sur que ça vient de la config du 60gp
3) ça va pourrir le code mais c'est toi qui voit
4) je ne comprends pas bien l'intérêt de séparer, je pensais que ct pour ça qu'on avait mis un éditeur évolué, pour pouvoir editer l'article entièrement, si on peut pas éditer la balises il sert à rien ... si certains n'en ont pas c'est parce qu'il n'y en avait pas dans le html des articles que j'ai récup sur ton site, il faut simplement les ajouter. Sinon tu peux toujours les éditer depuis le BO.

**Comment by kapeco** [comment]
1) merci
2) j'ai regardé je ne vois pas
3) a quel niveau ca va le pourir ?
4)5) j'avais pas pensé à l'édition via le B O , je vais regarder ça

**Comment by corentin-begne** [comment]
2) tu avais le session dans l'url avant ? je vais regarder ce soir dans tes config php si yavait un truc.
3) J'ai pensé à un truc qui devrait passer tout seul faut que je test jte dis ça t'al heure
4/5) je vais voir dans la config si ya pas moyen d'afficher les balises pour les éditer mais en même temps ça évite de les casser par erreur et pour les H1 une fois qu'elle sont mise faut pas les enlever.

**Comment by kapeco** [comment]
2) non je n'avais pas les session dans l'url
3) ok , hate de voir ça
4)5) laisse tomber je m'en suis sorti via le BO, on gérera ça bien plus tard du coup

**Comment by kapeco** [comment]
Bon reste plus que le point 2) a retirer rapidement 

Peut etre avec le fichier htaccess et un rewrtite ?

**Comment by kapeco** [comment]
c'est bon j'ai trouvé 
SetEnv SESSION_USE_TRANS_SID 0

à mettre dans le .htaccess , que j'ai fait et c'est nickel, attention , prend le en compte pour pas l'écraser

**Comment by kapeco** [comment]
Oups par contre ce que tu as fait pour la page d'acceuil fonctionne mais du coup tous les autres liens sont en 404 , faut corriger au plus vite stp !!!!

**Comment by corentin-begne** [comment]
j'ai corrigé les liens direct en prod par contre accueil est revenu avec le lien d'avant.
Les chemins des liens sont éditable dans le BO.

**Comment by corentin-begne** [comment]
pour le pb de session dans l'url comme ça correspond à ton hébergement, met le dans le htaccess qui est à la racine, j'ai mis php 5.4 déjà dedans

**Comment by corentin-begne** [comment]
je t'ai monté la preprod avec les modif pour le lien acceuil et j'ai viré le lien mot de passe oublié. Par contre il faut que tu fasse pointer dev.kapeco.eu dans web pour que ça fonctionne.

**Comment by kapeco** [comment]
Ah bon pas même config pour pré prod et prod ?

**Comment by corentin-begne** [comment]
bah si mais là dev.kapeco.eu pointe sur dev et devrait pointer sur dev/web comme kapeco.com qui pointe sur www/web pas sur www

**Comment by corentin-begne** [comment]
enfin l'archi et le fonctionnement sont pareil mais pas la config, dailleur c'est une branche à part sur le projet, t'amuse pas à essayer de copier le contenu de dev dans www pour mettre en prod ça va tout péter, il faut que je fasse une mep prod.

**Comment by kapeco** [comment]
ok ok :)

**Comment by kapeco** [comment]
je viens de voir que tu as résolu le soucis, c'est tout bon tu peux mettre ça en prod
Merkiii

**Comment by corentin-begne** [comment]
oui c'était un pb de droit sur le rep web.
ok jte mets ça en prod ce soir !

**Comment by corentin-begne** [comment]
faut faire un truc nickel ça serait bien que tu fasses pointer preprod.kapeco.com sur dev/web et dev.kapeco.com sur l'ip de mon ordi comme ça on aurait tous les envs nickel. Il faudrait peut être mettre un htaccess spécial pour ces env afin qu'il ne référence pas et que l'accès soit restreint.

**Comment by corentin-begne** [comment]
je sais pas si t'as remarqué aussi ton nom de domaine n'est pas redirigé automatiquement vers www je sais pas si c'est important pour le seo

**Comment by kapeco** [comment]
Ah bon j'ai pas fait gaffe à ça !!! Mais j'ai mis en préférence dans gwmt le www.
Je vais faire les domaines correctement vers les différents env

**Comment by corentin-begne** [comment]
il faut mettre une règle dans le htaccess je pense sinon une redirection mais je sais pas si c'est possible car c'est www.kapeco.com qui pointe sur kapeco.com normalement vu que c'est lui le domaine.

**Comment by kapeco** [comment]
laisson comme ça pour le moment le temps que je me renseigne , car on été plutot super bien référencé

**Comment by kapeco** [comment]
création des sous domaines en cours, je te laisse faire pour le htaccess afin que ce ne soit pas référencé

**Comment by corentin-begne** [comment]
ok, je met une authentification aussi ?
j'ai fais la mise en prod.

**Comment by kapeco** [comment]
ok

**Comment by corentin-begne** [comment]
j'ai mis l'auth en dev et preprod, accès par mail, du coup j'ai fais une mise en preprod tu peux voir ta nouvelle image. Pour la prochaine mep, je vais ajouter une date de release en paramètre des fichier js/css et image afin de forcer le reload du cache.

**Comment by kapeco** [comment]
tres bonne idée ça ;)

**Comment by kapeco** [comment]
pousse l'image en prod
je ne suis pas encore 100% satisfait de l'image mais au moins c'est mieux
Faut que je fasse pareil pour nous contacter

**Comment by corentin-begne** [comment]
ok c'est en prod et pour les prochains met les direct en 200px de largeur stp j'ai du redimenssionner.

**Comment by kapeco** [comment]
ok ça marche  ;)

merci

**Comment by kapeco** [comment]
par contre faudrait ajouter les infos concernant l'image 

"Devis en ligne gratuit"

**Comment by corentin-begne** [comment]
donne un title pour chaque image tant que j'y suis. tu as reçu les accès pour la dev et preprod normalement ? la dev ne sera pas toujours up mais je l'ai mis en place aussi

**Comment by kapeco** [comment]
oui jai les accès , c'est impec

"Dekra certification"
"Diagnostic de performance énergétique"

**Comment by corentin-begne** [comment]
c'est fait en dev

**Comment by kapeco** [comment]
impec
