### ISSUE TITLE
install en local

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#46]
Je capte pas l'installation en local  !! un truc de fou pourtant j'imagine que c'est simple
PHP Version 5.6.8 , Trop haut ?

**Comment by corentin-begne** [comment]
je ne sais pas, j'ai jamais testé mais ça devrait fonctionner. En fait il faut, soit que tu dl la branche master du project qui est accès sur l'env dev sinon, avec ce que tu as récupéré pour que ça pointe sur la config dev, il faut modifier le define ENV qui est dans le fichier index.php dans web et mettre dev au lieu de prod et recompile les less sinon les fichiers images définis dans les css vont pointer sur la prod et pour ça tu doit installer node avec le package lessc et eexécuter la tache php application task:compileLess

**Comment by kapeco** [comment]
ok je vais voir ça , mais ça ne m'a pas l'air trop clair ;)

**Comment by kapeco** [comment]
hum j'ai rien pour compiler ça , pas possible que tu le compiles pour qu'il s'execute en localhost/kapeco ?

**Comment by kapeco** [comment]
Bon j'ai modif mon fichier hosts , j'arrive en local par www.kapeco.com 
j'ai modif le fichier de conf pour la base de données et toujours rien
ça m'affiche juste les fichiers

**Comment by corentin-begne** [comment]
ouais mais la config prod est spéciale, j'ai changé quelque truc par rapport à la dev notamment sur htaccess. Le plus simple c'est que tu clone la branche master du project avec git, après tu fais pointer localhost/kapeco dans web et tu change la config db de la partie dev et ça devrait fonctionner tout seul.
Si ça liste les fichier au lieu de les exécuter c'est que le htaccess ne fonctionne pas, tu dois surement activer le mode_rewrite .
install https://git-scm.com/download/win et clone https://github.com/corentin-begne/kap.git

**Comment by kapeco** [comment]
Merci j'ai plus besoin normalement mais je vais faire l'installation en local car j'ai envi que ça marche 😉
