### ISSUE TITLE
Changement du logo devis gratuit

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#47]
par celui ci pour voir : 
![devis-en-ligne](https://cloud.githubusercontent.com/assets/11981295/8494352/8858e43c-2164-11e5-92f5-355b801b67b0.png)

**Comment by corentin-begne** [comment]
ok jte le mettrai en dev t'al pour que tu check

**Comment by corentin-begne** [comment]
tu peux check en dev
