### ISSUE TITLE
Nous contacter

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#48]
Laisser l'image en place "nous contacter" au dessous du liens "devis gratuit" comme c'est maintenant, mais la rendre non cliquable, donc la mettre en dur
Par contre ajouter au dessous le lien "Nous contacter"  

![index](https://cloud.githubusercontent.com/assets/11981295/8504431/bbf7798a-21d1-11e5-800c-00c591d23966.png)Nous contacter

Mais centrer en hauteur le texte par rapport à l'image

**Comment by corentin-begne** [comment]
comme title sur les deux images je mets quelque chose ? le lien de je le met en quel style ?

**Comment by kapeco** [comment]
quelles deux images ?
Pour le mail "Nous contacter" comme title 
Le liens tu le mets dans le même style que les autres

**Comment by corentin-begne** [comment]
la grosse image nous contacter

**Comment by kapeco** [comment]
"Nous contacter par téléphone pour plus d'informations sur les diagnostics immobiliers"

**Comment by corentin-begne** [comment]
ok c'est fait en dev tu peux check

**Comment by kapeco** [comment]
Ok y a juste le texte "nous contacter" qui n'est pas dans le style des autres liens de gauche niveau couleur, par contre conserve la taille de la police c'ets bien comme ça

**Comment by corentin-begne** [comment]
là c bon ?

**Comment by kapeco** [comment]
Impeccable 
Go to prod 😉

**Comment by corentin-begne** [comment]
c'est en prod

**Comment by kapeco** [comment]
Merci
