### ISSUE TITLE
Modification formulaire de devis

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#49]
Renommer les pièces
F1 => 1 pièce
F2 => 2 pièces 
Etc ...

**Comment by corentin-begne** [comment]
c'est fait en dev

**Comment by kapeco** [comment]
Sauf qu'il faudrait que tu ajoutes au moins 4 saut de ligne entre le titre et le formulaire

et aussi la mention "Type de transaction  : " devant vente et location

**Comment by kapeco** [comment]
nickel
