### ISSUE TITLE
Modif rapide de contenu

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#50]
dans le footer juste avant "Retrouvez nous aussi sur :"

on retrouve

"Diagnostic immobilier , Amiante, DPE, plomb | KAPECO, Kapeco Diagnostics immobiliers "

Action : supprimer le liens qu'il y a dans cette ligne et modifier le texte de cette ligne par

"Diagnostic immobilier ,Carrez, Boutin, Gaz, Amiante, DPE, Plomb, Electricité, Termites, Assainissement , Kapeco Diagnostics immobiliers"

**Comment by corentin-begne** [comment]
c'est fait en dev

**Comment by kapeco** [comment]
impec , à pousser ;)
