### ISSUE TITLE
Contact : ajout de saut de ligne

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#51]
http://www.kapeco.com/contact

Ajout de trois saut de ligne entre le titre et le formulaire

**Comment by corentin-begne** [comment]
j'ai ajouté 2 br en dev

**Comment by kapeco** [comment]
y en faudrait encore deux je pense

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
impec , MEP accepté ;)
