### ISSUE TITLE
Devis , un peu de cosmétique

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#52]
http://www.kapeco.com/devis-gratuit

Retirer le fieldset 
Mettre le titre de la même couleur que les autres titres (3399FF)
Mettre le bouton "envoyé" dans le même style que le bouton "envoyé" de la page "contact"
et si possible mettre les champs du formulaire dans le même style que ceux de la page "contact"

**Comment by corentin-begne** [comment]
c'est fait en dev

**Comment by kapeco** [comment]
nickel 

Sauf qu'il faudrait que tu ajoutes au moins 4 saut de ligne entre le titre et le formulaire

et aussi la mention "Type de transaction : " devant vente et location

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
Merci mais .. hum ; manque quelque chose visuellement

Possible d'ajouter un cadre comme dans la Creation des ODM ?

**Comment by corentin-begne** [comment]
le fieldset que tu m'as fait virer ?

**Comment by kapeco** [comment]
:D :D :D

**Comment by corentin-begne** [comment]
j'ai changé un peu dis moi si c'est mieux

**Comment by corentin-begne** [comment]
tu me valide ça et je fais une mep

**Comment by kapeco** [comment]
allez go MEP

**Comment by corentin-begne** [comment]
tout est en prod !

**Comment by kapeco** [comment]
Merci
