### ISSUE TITLE
contact en fonction de la géolocalisation

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#53]
celà concerne le mail de contact dans le formulaire de contact de la page devis ainsi que de la page contact , mais ça concerne aussi le numéro de tel de contact affiché dans l'image à droite.
Concernant l'image , je peux effacer le numéro qu'il y a sur l'image, et positionner par dessus un numéro en css par exemple selon la géolocalisation .

Donc côté BO,  je rentre un CP , voir même un département, j'y assigne un mail + tel et lorsque que quelqu'un navigue avec une IP reconnu comme provenant du CP ou du dép alors le numéro de tel s'affiche sur la page, et si la personne essaye de contacter kapeco , ça sera selon le mail qui est défini ou le tel affiché en conséquence

ex1:

CP ou DEP | mail | Tél
60500 | franck@toto.com| 0660606060

ex2 : 
60 |  franck@toto.com| 0660606060

Je peux ajouter une liste indéfini .

Si le surfeur n'appartient à aucun CP ou Dép de cette liste alors les infos de contact par défaut sont ceux qui sont défini aujourd"hui.

On pourrait donc laisser la possibilité de modifier ça dans le BO  en pouvant renseigner les info de contact par défaut

**Comment by corentin-begne** [comment]
ok je vais voir pour te mettre ça en place

**Comment by kapeco** [comment]
thx
ici http://openclassrooms.com/courses/geolocalisez-vos-visiteurs-grace-a-leur-ip

ils ont une API pour le CP , car la ville c'est simple mais source d'erreur surtout que Marseille par exemple existe dans le 13 et le 60

**Comment by corentin-begne** [comment]
ça te dérange pas que toute les pages de ton site dépendent d'une api de géolocalisation ? envoi l'image sans le num, je vais voir pour faire un proto au mieux mais check bdd + api ça va forcément ralentir l'acès au site.

**Comment by kapeco** [comment]
si ça me dérange mais je ne trouve rien d'autre

**Comment by corentin-begne** [comment]
Pour ne pas que ça pourrisse les perfs on a qu'à le faire en deux temps. A l'init serveur on met le num par défaut puis l'init du js appel un webservice qui renvoi le bon num, si le num est différent de celui affiché alors il se change avec un fondu pour que ça se voit.

**Comment by kapeco** [comment]
Yep bonne idée , faut effectivement garder à l'esprit la performance

**Comment by corentin-begne** [comment]
Est ce que les users auquels tu veux associer les cp/dep sont des users existant ou des nouveau qui ne seront utilisés uniquement pour ça ?

**Comment by kapeco** [comment]
existant , par exemple moi pour le moment

**Comment by corentin-begne** [comment]
ok par contre celui par défaut ça sera des valeurs à saisir dans le BO à part comme je viens d'ajouter, tu peux voir un lien Config en plus avec les valeurs configurées.

**Comment by kapeco** [comment]
oui

**Comment by corentin-begne** [comment]
j'ai mis en place la nouvelle image  avec le num positionné à part, je vais faire une mep pour analytics avant de continuer.

**Comment by kapeco** [comment]
Ok

**Comment by corentin-begne** [comment]
pour les mails envoyés pour la création des users je mets l'user par défaut tout le tps ou je dois faire un check par rapport aux infos de l'user ?

**Comment by kapeco** [comment]
Toujours celui par défaut

**Comment by corentin-begne** [comment]
c'est fait !
donc tu peux config l'email, phone et nam du contact par défaut dans le lien config du BO.
Tu peux également associé des code, donc cp ou dep, à des users par le lien Contacts utilisateurs dans le BO. Le fonctionne est qu'à l'init ça met les infos par défaut puis le js fait appel à un webservice qui selon l'ip récup le cp. Avec le cp je check si en bdd j'ai un user qui match ou sinon sur le dep (2 premier chiffre du cp) et je prends en priorité le cp. Si aucun user n'est trouvé, on prends l'user par défaut et sur le retour du webservice si le num trouvé et diff ça le change en fondu.

**Comment by kapeco** [comment]
ça a l'air nickel ça sur le principe c'est eaxctement ce qu'il faut, ça change donc le num visible mais est-ce que ça change aussi le mail de contact partout aussi ?

**Comment by corentin-begne** [comment]
c'est en place aussi sur l'envoi de mail depuis le formulaire de contact

**Comment by kapeco** [comment]
et depuis le devis quand on depasse le nb de pièce ou surface ?

**Comment by kapeco** [comment]
Par contre petit soucis , je suis sur dev et y a aucun numéro par défaut qui s'affiche !

**Comment by corentin-begne** [comment]
oui depuis le devis aussi. c'est un pb de cache papy tu dois avoir encore l'ancienne image. quand je met mon ip en dur je vois bien le num qui change en fondu pour le mien et si je l'enlève donc il se met sur 127.0.0.1 il trouve rien donc laisse l'autre.

**Comment by corentin-begne** [comment]
j'ai test sur ff et chrome

**Comment by kapeco** [comment]
je confirme que tu as raison , donc MEP ok ;)

**Comment by corentin-begne** [comment]
ok c'est parti mais faut que je prépare la bdd avant

**Comment by kapeco** [comment]
vas y prepare prepare ... mais j'ai l'impression que tu n'as pas mis ta cape de zorro ce soir encore !!!

**Comment by corentin-begne** [comment]
non mais j'ai sorti le lasso ^^

**Comment by kapeco** [comment]
lol :yum:

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
merci

Par contre je viens d'envoyer un mail depuis le devis , et j'aurais du recevoir ce mail mais ni mon frère ni moi ne l'avons reçu !

**Comment by corentin-begne** [comment]
ça doit venir de la clé faudrait que je matte ton compte

**Comment by kapeco** [comment]
regarde tes mails

**Comment by kapeco** [comment]
c'est tout bon
