### ISSUE TITLE
push

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#54]
n'envoyer le push (mon truc perso) que si [GEOIP_COUNTRY_NAME] => France

**Comment by corentin-begne** [comment]
c'est fait en dev

**Comment by kapeco** [comment]
pousse ;)

**Comment by kapeco** [comment]
Par contre peux tu faire en sorte que lorsque la ville est vide , je ne recoive pas le push ?

**Comment by corentin-begne** [comment]
c'est ajouté

**Comment by kapeco** [comment]
tu es certain  ??? car je reçois toujours des noms de ville vides ... attentions aux espaces

**Comment by corentin-begne** [comment]
c'est pas en prod aussi

**Comment by kapeco** [comment]
ah ... ben pousse alors

**Comment by kapeco** [comment]
je ne reçoit plus aucun push ... je vais attendre le 1er aout pour voir si ça viens du quotas qui a été dépassé

**Comment by kapeco** [comment]
c'est nickel
