### ISSUE TITLE
sitemap.xml

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#55]
Je viens de mettre à jour le fichier sitemap.xml

à ,ne pas écraser stp ;)

**Comment by kapeco** [comment]
idem pour le fichier robot.txt et Paste.html qui deviens Paste.php

**Comment by corentin-begne** [comment]
ok je vais les récup mais de toute façon comme je fais un rsync ça ne supprime pas les fichier que je n'ai pas dans le project. Par contre le fichier sitemap ne devrait pas être généré lors de la mep pour mettre à jour toute les infos et mettre les bons lien ?

**Comment by kapeco** [comment]
si tu peux faire ça pas de soucis, mais là je le génère a chaque fois

**Comment by corentin-begne** [comment]
oui il faut que tu me dises tout ce que je dois mettre dedans si tu veux que je le crée.

**Comment by corentin-begne** [comment]
je pourrais te mettre un bouton de le BO pour que tu puisses le regénérer

**Comment by kapeco** [comment]
non mais ça va , je le met a jour rapidement sur le site, faut juste que tu ne l'écrase pas

**Comment by corentin-begne** [comment]
c bon le rsync n'écrase pas

**Comment by kapeco** [comment]
impec
