### ISSUE TITLE
title pour le hearder

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#56]
http://www.kapeco.com/images/header.jpg

il faudrait ajouter un title aussi pour cette image : 

"Kapeco Diagnostics immobiliers : amiante, gaz, électricité, performance énergétique DPE, termites,plomb, carrez, boutin, assainissement"

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
impec MEP ;)

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
Parfait , 0 violation SEO ;)

**Comment by kapeco** [comment]
Tu as oublié le T de assainissement dans le title du header

**Comment by corentin-begne** [comment]
oups ... jte change ça t'al heure

**Comment by kapeco** [comment]
ok merci ;)

Je vois que tu reinstalles ton serveur ;)

**Comment by corentin-begne** [comment]
c'est corrigé et en prod

**Comment by kapeco** [comment]
merci fiston
