### ISSUE TITLE
Problème de SEO

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#57]
Level : Error
Message : The page contains multiple canonical formats.
Details : 
The page with URL "http://www.kapeco.com/images/lib/ui-bg_flat_75_ffffff_40x100.png?releaseDate=1436123010" can also be accessed by using URL "http://www.kapeco.com/images/lib/ui-bg_flat_75_ffffff_40x100.png?releaseDate=1436123013".
Search engines identify unique pages by using URLs.  When a single page can be accessed by using any one of multiple URLs, a search engine assumes that there are multiple unique pages. Use a single URL to reference a page to prevent dilution of page relevance. You can prevent dilution by following a standard URL format.

Je n'avais pas cette erreur il y a quelques jours, il me semble que ça viens de ce que tu as mis pour flusher le cache ?

**Comment by corentin-begne** [comment]
en fait je l'ai pas changé pour l'instant mais je l'avais déjà mis sur certain. et du coup tu veux faire quoi ? c'est un peu co comme règle car tous les fichiers statique tu peux y accéder en changeant les paramètre en get et ça affiche la même chose ...

**Comment by kapeco** [comment]
faudrait retirer car maintenant le statique ne va plus trop bouger

**Comment by corentin-begne** [comment]
ok je l'ai viré

**Comment by kapeco** [comment]
c'est en prod ? sinon va y pousse

**Comment by corentin-begne** [comment]
c'est en prod

**Comment by kapeco** [comment]
impec 0 violation SEO maintenant :)
