### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#58]
![2015-07-06 00_22_53-google analytics](https://cloud.githubusercontent.com/assets/11981295/8513679/3d277218-2375-11e5-902b-8d5d666b4a0b.png)

< script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64817000-1', 'auto');
  ga('send', 'pageview');

< /script>

**Comment by kapeco** [comment]
bon du coup tu as du recevoir une invitation

Il faudrait donc un tracking classique sur toutes les pages
Mais il faudrait savoir combien clic sur le bouton "envoyé" de devis et de contact

**Comment by corentin-begne** [comment]
sur toute les pages ? même celles qui nécessite une authentification ? tu veux quel tag pour le clic sur envoyer du devis ? et pour le contact ?

**Comment by kapeco** [comment]
non pour le moment seule les pages sans authentification , on verra ça plus tard quand elles seront terminées

concernant les tags, comme tu veux tant que c'est explicite genre : 
envoisdevis | envoiscontact | boutondevis | homedevis

**Comment by kapeco** [comment]
Bon et bien maintenant que le site est bien avancé , on pourra ajouter des stats sur les pages qui nécessitent un authentification aussi, diagnostic et ODM

**Comment by corentin-begne** [comment]
J'ai mis en place le tracking page view sur toute les pages du front. 
J'ai également mis en place un système qui permet d'associer des event/functions/class js avec des éléments et effectuer des actions en plus selon le type fournit. 
Je t'explique ça car c'est aussi intéressant à ton niveau car ça veut dire que tu peux toi même mettre des éléments à tracker dans les articles.
Les éléments trackés envoient leur id, l'event et le type (si aucun event n'est fournit mousedown est utilisé par défaut), l'élément doit être de la forme : 
```
<xx class="action" data-action='{"type":"track", "event":"click"}'>bla bla</xx>
```
jte laisse test, j'ai mis un console log avec les élément envoyés, pour l'instant j'ai mis à tracker l'envoi du formulaire de contact, celui du devis et l'image devis gratuit, dis moi si je dois en ajouter.

**Comment by kapeco** [comment]
Ok je vais tester ça cet après-midi

**Comment by kapeco** [comment]
J'ai un message d'erreur dans analytics : 

"Aucun code de suivi valide n'a été trouvé pour l'URL par défaut http://www.kapeco.com de la propriété kapeco. Vérifiez que vous avez inséré la bonne version du code de suivi dans vos pages."

**Comment by corentin-begne** [comment]
j'ai utilisé ça : 
https://developers.google.com/analytics/devguides/collection/gajs/

mais je me demande si c'est pas parce que je suis en localhost que ça envoie rien.

**Comment by kapeco** [comment]
étrange , pousse en prod, de toute façon y aura pas trop d'incidence , on saura que les premières stats seront par forcément ajustées

**Comment by corentin-begne** [comment]
c'est en prod

**Comment by kapeco** [comment]
Ok je vais vérifier après la je suis devant Ant-man au ciné on va voir ce que ça donne 😉

**Comment by corentin-begne** [comment]
ça à l'air de fonctionner, je vois les events dans analytics :)

**Comment by kapeco** [comment]
Good 
Je sort de Ant-man je vais regarder ça

**Comment by kapeco** [comment]
moi je vois rien, tu regardes ou ?

**Comment by corentin-begne** [comment]
c'est parce que par defaut il te met une période à partir d'hier à un mois avant, si tu règle dans période aujourd'hui tu les vois

**Comment by kapeco** [comment]
yes c'est bon , par contre c'est quoi ces tag ? 

devisContainer

**Comment by corentin-begne** [comment]
c'est le formulaire du devis quand t'appuie sur envoyer mais normalement tu as avec l'event et le type donc pour celui ci tu dois avoir : 
devisContainer submit form

**Comment by kapeco** [comment]
je t'ai donné des noms en français faut les utiliser ou respecter le principe

"concernant les tags, comme tu veux tant que c'est explicite genre :
envoisdevis | envoiscontact | boutondevis | homedevis "

**Comment by kapeco** [comment]
sinon nickel effectivement ça s'enregistre bien

**Comment by corentin-begne** [comment]
ok bah je vais ajouter un tag spécial que pour les events alors, là j'utilisais l'id de l'élélement

**Comment by kapeco** [comment]
merci , faut vraiment que ce soit en français le plus explicite possible car un jour y aura pas que moi qui visualisera les stats , genre mon frère qui est une bille dans le domaine

**Comment by corentin-begne** [comment]
ok j'ai modifié, après la prochaine mep tu auras, boutondevis devisenvoyer et contactenvoyer . Par contre si tu veux mettre des éléments à tracker il faut ajouter le tag maintenant par exemple : 
```
<a class='action' data-action='{"type":"track", "tag":"liendevis"}'>Devis gratuit</xx>
```

**Comment by kapeco** [comment]
ok impec tu peux mettre en prod alors ;)

**Comment by corentin-begne** [comment]
dès qu'on a valid la géoloc

**Comment by kapeco** [comment]
c'est validé aussi ;)

**Comment by corentin-begne** [comment]
ça c'est bon ? t'as réussi à utiliser ce que je t'ai mis en place ?

**Comment by kapeco** [comment]
ça met du temps a arriver , je vais check à nouveau

**Comment by kapeco** [comment]
c'est impec

**Comment by kapeco** [comment]
y a plus qu'a mettre ça en place sur les pages connectées

**Comment by corentin-begne** [comment]
ça l'est déjà

**Comment by kapeco** [comment]
ah ok , je ferme alors , au besoin je rouvrirais ce topic
Merci
