### ISSUE TITLE
changement des URL

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#6]
concernant les url

http://176.183.159.254/kapeco/devis/gratuit
pourrait etre http://176.183.159.254/kapeco/devis-gratuit

et on retire "conseils" qu'on remplace par "diagnostic/"

http://176.183.159.254/kapeco/conseils-loi-boutin
deviens
http://176.183.159.254/kapeco/diagnostic/loi-boutin

**Comment by corentin-begne** [comment]
c'est fait, l'ancien lien devis fonctionne encore mais je t'ai mis le nouveau

**Comment by kapeco** [comment]
ok impec , on a juste perdu tous les autres liens a moins que tu sois dessus ... ;)

**Comment by corentin-begne** [comment]
ouais j'étais dessus c'est bon maintenant :)

**Comment by kapeco** [comment]
je reviens sur une chose, comme je te vois travailler sur les liens

faisons plutot comme ceci : 

site/categorie/lien

site/diagnostics-immobiliers/expertise-plomb

**Comment by corentin-begne** [comment]
c'est déjà ce que j'ai fais donc si tu vas dans l'admin partie catégorie et que tu changes le champ path, le chemin du lien aura changé, pareil pour les articles mais c'était déjà le cas avant

**Comment by kapeco** [comment]
nickel , je ferme ce post
