### ISSUE TITLE
Soucis avec les balises hx

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#61]
mauvaise hiérarchie de hx --> < h3> Diagnostics immobiliers < /h3> (longueur 23, ligne 39)

< h3> Autres contrôles < /h3> (longueur 17, ligne 103)

< h3> Autres informations < /h3> (longueur 19, ligne 125)

< h3> Connexion < /h3> (longueur 9, ligne 161)

< h3> < /h3> <-- Alerte le texte de cette balise hx est vide (longueur 0, ligne 183) 

Faudrait donc passer les titres des catégories en h2
et vérifier pourquoi y du h3 vide

**Comment by corentin-begne** [comment]
cette balise est utilisé quand on est loggé pour mettre le username

**Comment by corentin-begne** [comment]
mais la balise parent est cachée, ça ne devrait pas impacté le référencement

**Comment by corentin-begne** [comment]
et j'ai mis h3 car c'est ce que tu avais mis dans ta version de dev.

**Comment by kapeco** [comment]
Faudrait quand même corriger du coup

**Comment by corentin-begne** [comment]
ok je vais mettre des h2 mais pourquoi la balise vide pose pb ?

**Comment by kapeco** [comment]
Car il titre sans caractère posé problème 
Google crawl la page et cherche en partie en priorité les mots clef dans les balise hx, mais si il en trouve des vides alors ca génère une erreur donc un malus

**Comment by corentin-begne** [comment]
dans ce cas je mettrai le username dans une div no pb

**Comment by kapeco** [comment]
Ok

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
ok ça a l'air impec => MEP

**Comment by corentin-begne** [comment]
c'est en prod

**Comment by kapeco** [comment]
merci 
ça me met encore une erreur maais c'est du à l'ordre d'affichage du html , donc on ne change rien, c'ets bon
