### ISSUE TITLE
doctype manquant

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#62]
Votre page HTML n'a pas déclaré de version HTML (directive DOCTYPE au début du fichier HTML)

**Comment by corentin-begne** [comment]
mouais

**Comment by kapeco** [comment]
Lol 😀 
C'est quoi ce mouais.
Y juste le doctype a rajouter et ça fera une goute de plus dans l'océan Google

**Comment by corentin-begne** [comment]
non c'est juste que ça sert à rien mais si ça lui fait plaisir on va lui mettre

**Comment by kapeco** [comment]
:-)

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
Merci => MEP
