### ISSUE TITLE
Creation ODM : numéto de lot

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#64]
Salut coco
On viens de me remonter l'info que des numéro de lot peuvent être alpha numérique

Ajouter aussi un textarea afin qu'on puisse nous remonter des infos complémentaires

tu l'appelleras "Notes" et il sera positionné en dernière position

**Comment by corentin-begne** [comment]
si tu veux que je fasse ça, je le ferais en même tps que #35 sinon je vais perdre un temps considérable à me mettre dedans en deux fois.

**Comment by kapeco** [comment]
perdre un temps considérable ? ah oui j'ai pigé , bien-sur fait ça en meme temps que l'autre, je ferme celui-ci
