### ISSUE TITLE
ODM : vue diagnoostiqueur

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#66]
on a ça : 

Nom agence | Nom du propriétaire | Ville du bien | Intervention | Diagnostiques

il faudrait

Nom agence | Nom du propriétaire | adresse_complete_du_bien | Intervention | Diagnostiques

**Comment by corentin-begne** [comment]
np

**Comment by corentin-begne** [comment]
C'est fait donc que pour les diagnostiqueurs, les agences ne voient que la ville comme avant.

**Comment by kapeco** [comment]
Fait les pour les deux ça sera mieux 
C'est vrai j'ai pas pensé aux agences sur ce coup la . J'ai pensé qu'à ma pomme

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
ok goto prod
