### ISSUE TITLE
Liens paramètre pour les utilisateurs

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#67]
Donc rajouter pour tous les utilisateurs le lien "paramètre" avec dedans :+1: 

La possibilité aux utilisateurs de pouvoir changer leur mot de passe et leur mail ainsi que leur tel

**Comment by corentin-begne** [comment]
ok je vais voir pour ajouter ça.

**Comment by kapeco** [comment]
Merci

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
impec aussi Go to MEP

**Comment by kapeco** [comment]
MEP ok
