### ISSUE TITLE
Mail pour les nouveaux utilisateurs

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#68]
Quand on crée un nouvel utilisateur, il faudrait l'envois automatique d'un mail lui indiquant ses accès

L'objet : "KAPECO Diagnostic : confirmation de votre inscription"

Body : "Bonjour,

Nous vous confirmons votre inscription sur le site de KAPECO Diagnostics immobiliers 

Votre identifiant est : toto@toto.com
Votre mot de passe actuel est : 123456

Une fois identifié, vous devrez changer votre mot de passe en allant dans vos paramètre http://www.kapeco.com/user/setting

Vous pouvez dès à présent vous connecter sur notre site internet http://wwwkapeco.com

L'équipe Kapeco"

**Comment by corentin-begne** [comment]
ok

**Comment by kapeco** [comment]
Good

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
Nickel 
GO to MEP

**Comment by kapeco** [comment]
mep OK
