### ISSUE TITLE
alerte pour les agents

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#69]
De la même manière que ce que tu as fait pour les diagnostiqueur : puce rouge et nombre en rouge au niveau du liens ou il y a des nouveautés
Il faudrait faire ça aussi pour les agences lorsqu'on leur up un nouveau diag et lorsqu'on leur valide un ODM
Par contre concernant l'odm , le liens redeviens normal lorsque la liste des odm à été affichée.
Alors que pour les diagnostics , ça décompte si le fichier à au moins été téléchargé une fois

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
ouais sauf que ça ne fonctionne pas complètement :"Par contre concernant l'odm , le liens redeviens normal lorsque la liste des odm à été affichée."
ca reste toujours !!!

**Comment by corentin-begne** [comment]
t'es sur parce que je l'ai testé hier et ça fonctionnait nickel ... vide bien ton cache et refait le truc depuis le début, ça correspond aux odm qui ont été validé mais pas encore vu et il faut être sur la page pendant au moins 0.5s pour qu'ils soient vu.

**Comment by kapeco** [comment]
ouais ça f

**Comment by kapeco** [comment]
bon je crois qu'il y a un autre soucis, y a deux etats pour les ODM coté agence : 
"en attente" et "réservé"
y a besoin de cet utilité que pour les "réservé", alors que la c'est l'inverse à ce que je vois. ,pourtant j'avais écrit "et lorsqu'on leur valide un ODM"

Faut bien comprendre le scénario : 
L'agent immobilier crée plusieurs ODM (4 par exemple), il à donc une liste d'odm "en attente" => pas de pastille en rouge
Le diagnostiqueur passe et lui valide un odm uniquement
L'agent immo voit la puce passer en rouge avec entre parenthèse (1) , dès qu'il clic sur le liens odm et qu'il arrive sur la page de ses demandes d'odm, alors la puce repasse couleur normal et le chiffre entre () se décompte automatiquement du nombre d'odm listé en statut "réservé". Si il à plusieurs page d'odm avec des "réservé" dans plusieurs page il faut qu'il parcours toute ses pages pour que le compteur () redescende à zero.
Et du coup c'est maintenant que je comprend mieux ta subtilité d'ajouter une fonction qui "surligne" en rouge quelques instant les lignes qui n'avaient pas encore étaient vue.

**Comment by kapeco** [comment]
oups ... méa culpa , j'était en vu diagnostiqueur ... donc tout fonctionne bien en fait , t'es un vrai pro du javascript :palm_tree:

**Comment by corentin-begne** [comment]
:)
oui comme facebook par exemple quand tu mattes tes notifs, je te le mettrai en place avant la mep si tu veux voir ce que ça rend, c'est rapide.

**Comment by kapeco** [comment]
ok ça peut etre cool :)

**Comment by corentin-begne** [comment]
jte l'ai mis pour que tu puisse test, je prépare le mise en preprod on va faire preprod en premier pour être sur de rien oublier.

**Comment by corentin-begne** [comment]
j'ai préparé la preprod, j'attends que tu me valide, je vais préparer la prod en attendant.

**Comment by corentin-begne** [comment]
la prod est prête aussi, j'attends ta validation.

**Comment by kapeco** [comment]
je test
mais déja en preprod je n'arrive plus à me logguer avec un user agence :(

**Comment by corentin-begne** [comment]
non mais je n'ai ni fait la mise en preprod ni la mise en prod j'ai juste préparé les bdd, j'attends que tu valide le truc en dev et je lance en preprod pour check.

**Comment by kapeco** [comment]
ah ok , mais quand même chelou que je n'arrive pas a m'authetifier

**Comment by kapeco** [comment]
yes c'est bon le rouge ;)

**Comment by kapeco** [comment]
du coup tu pousses tout les topics qui sont bon à être mis en prod en même temps ?

**Comment by corentin-begne** [comment]
ok je lance la preprod mais moi j'arrive à me log avec mon compte diag, j'ai plus de compte agence en preprod/prod tu me les as del

**Comment by kapeco** [comment]
ouais balance mais j'ai crée un compte agence et je n'arrive pas a me connect j'y arrive juste avec mon compte diag aussi

**Comment by corentin-begne** [comment]
c'est en perprod, j'ai réussi à me connecter avec le compte robertdupont@gmail.com vide bien ton cache, jte conseille d'ouvrir la console et de la paramétrer pour désactiver le cache quand elle est ouverte et l'ouvrir avant d'accéder à la page comme ça t'es sur que t'as pas de cache !!!

**Comment by kapeco** [comment]
essaye avec lapinkrr@gmail.comet le même passe que robert

**Comment by kapeco** [comment]
ça me saoul !!!!!!!!!!!!!!!! toujours login ou mot de passe incorect !

**Comment by corentin-begne** [comment]
ok j'ai trouvé c'est parce que la partie admin pointe sur la prod donc tu vois des users qui ne sont pas en preprod, j'ai refais une preprod ça devrait être good dsl

**Comment by kapeco** [comment]
ah ok ... mais j'ai plus de cheveux à cause de toi maintenant lol

**Comment by corentin-begne** [comment]
XD

**Comment by corentin-begne** [comment]
chacun son tour !

**Comment by kapeco** [comment]
t'en profite fiston mais moi j'ai plus l'age , ils tombent tout seul maintenant !

**Comment by corentin-begne** [comment]
et puis ils sont blancs ^^

**Comment by kapeco** [comment]
oui ... :(

**Comment by kapeco** [comment]
je vais porter le voil comme ça , ça ne se verra pas xD

**Comment by corentin-begne** [comment]
ça t'irai bien en plus

**Comment by kapeco** [comment]
je vais me marier avec imane lol

**Comment by corentin-begne** [comment]
on verrai juste les poils d'oreille qui dépassent

**Comment by kapeco** [comment]
mdr :D

**Comment by corentin-begne** [comment]
ah vous deux vous pourrez faire un bon hamac xD

**Comment by kapeco** [comment]
miam

**Comment by kapeco** [comment]
jarrive même plus le logger avec mon compte maintenant !

**Comment by corentin-begne** [comment]
je check

**Comment by kapeco** [comment]
c'est bon

**Comment by corentin-begne** [comment]
... tu deviens fou papy ^^

**Comment by kapeco** [comment]
yes
bon je viens de me rendre compte d'un manque dans la vu diagnostiqueur => odm
on a : 
Nom agence | Nom du propriétaire | Ville du bien | Intervention | Diagnostiques

Il faudrait ajouter le nom de l'agent

Nom agence | Agent | Nom du propriétaire | Ville du bien | Intervention | Diagnostiques

**Comment by kapeco** [comment]
sinon pour le reste ça peut aller en prod déjà ça a l'air tout bon

**Comment by corentin-begne** [comment]
c'est fait en dev, si c bon ça part en prod avec le reste.

**Comment by kapeco** [comment]
faudrait réduire la police

**Comment by corentin-begne** [comment]
partout ou que cette case ?

**Comment by kapeco** [comment]
toutes les cases

**Comment by corentin-begne** [comment]
ça le fera aussi quand tu sera loggé en mode agence

**Comment by kapeco** [comment]
oui

**Comment by corentin-begne** [comment]
c fait

**Comment by corentin-begne** [comment]
j'ai réduit les headers aussi

**Comment by corentin-begne** [comment]
je balance en prod ?

**Comment by kapeco** [comment]
ouais balance la purée !

**Comment by corentin-begne** [comment]
c'est fait ! oublie pas de mettre à jour les infos des agences. Si tu peux aussi faire le tri dans les issues et revoir les priorité. oublie pas de m'envoyer les coordonnées pour les factures aussi stp :)

**Comment by kapeco** [comment]
mettre à jour les infos agences ?

**Comment by kapeco** [comment]
ouais j'attend un mail de mon frère avec les coordonnées qu'il faut

**Comment by corentin-begne** [comment]
ouais vu que j'ai ajouté addresse, code postal, tel, email et ville

**Comment by kapeco** [comment]
ah oui :)
