### ISSUE TITLE
Template pour les 404

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#7]
"Cher internaute,

La page que vous recherchez n'existe pas ou a été déplacée.

Pour continuer votre navigation, choisissez l'une des rubriques ci-dessous :
Accueil
Loi carrez
Loi Boutin
Diagnostic gaz
Expertise plomb
Diagnostic termite
Diagnostic amiante
Diagnostic électricité
Etat des risques naturels
Performance énergétique

Merci pour votre compréhension.

L'équipe kapeco.com"

( bien sur avec les liens qui vont bien)

**Comment by corentin-begne** [comment]
c'est fait, j'ai mis en titre "Page introuvable"

**Comment by corentin-begne** [comment]
je me suis trompé dans les liens je change ça tout à l'heure

**Comment by kapeco** [comment]
ok

**Comment by kapeco** [comment]
Par contre je ne vois pas le titre
et si tu pouvais le mettre aussi gros et de la même couleur que les autres titres

**Comment by corentin-begne** [comment]
j'ai pas mis de titre h3, je voulais parler de la balise title, le titre de l'onglet

**Comment by corentin-begne** [comment]
les liens sont corrigés

**Comment by kapeco** [comment]
ok mais du coup de te parle du titre visible ;)

**Comment by corentin-begne** [comment]
ouais non j'en ai pas mis, t'en veux un ? tu veux quoi ?

**Comment by kapeco** [comment]
Page introuvable

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
C'est mieux comme ça 😉
