### ISSUE TITLE
Problème avec les siret

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#71]
en bo dans les agences quand je met un siret 51866641700036
si je raffraichi ça deviens 2147483647

Je pense que tu as mal typé le champ

**Comment by corentin-begne** [comment]
oui, je crois que j'ai mis le bon nombre de caractères mais en int du coup ça le fait pas, je te change ça ce midi, je dois refaire une mep pour corriger car il faut que je regénère le schéma de la bdd pour le backend

**Comment by kapeco** [comment]
ça marche

**Comment by corentin-begne** [comment]
check en dev normalment c bon

**Comment by kapeco** [comment]
yes c'est impec ! go to prod

**Comment by kapeco** [comment]
en prod nickel merci
