### ISSUE TITLE
Mandrill

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#72]
Madrill est pluggé sur quel compte en prod ?

Parce que je ne vois rien dans mon compte

**Comment by corentin-begne** [comment]
pareil qu'en dev, c'est le même compte partout

**Comment by kapeco** [comment]
ok mais du coup quel compte ? Faudrait plugger le miens au moins en prod

**Comment by corentin-begne** [comment]
je t'avais filé mon compte pour y accéder, je croyais tu t'étais donné des permissions.
utilise mon compte et mets ce que tu veux :  
corentin.begne@gmail.com le pass tu le connais

**Comment by kapeco** [comment]
Ah bon je connais le pass ?!
Renvoi

**Comment by corentin-begne** [comment]
oui c'est celui de la preprod ... c'est pas grave je t'ai renvoyé les accès par mail

**Comment by corentin-begne** [comment]
j'ai mis ta clé en prod et la mienne en dev/preprod faudra test que ça fonctionne bien après la prochaine mep

**Comment by kapeco** [comment]
Si tu l'as mise en prod pourquoi attendre la prochaine mep pour test ? Je ne pige pas

**Comment by corentin-begne** [comment]
bah non j'ai pas mis en prod, je fais pas des mep à chaque fois que je change un petit truc c'est relou, ce que je voulais dire c'est dans le config du projet.

**Comment by kapeco** [comment]
Ok

**Comment by kapeco** [comment]
bon je viens d'envoyer un mail et je ne vois rien sur mandrill

**Comment by kapeco** [comment]
K46eZ9AlFO4L1MqroOpnfg

**Comment by corentin-begne** [comment]
j'utilisais déjà cette clé, j'ai modifié un  peu la lib pour être sur qu'il prenne celle que je lui fournit. je ferais un mep lorsque j'aurai fini la géoloc que j'ai bien avancé

**Comment by kapeco** [comment]
j'ai pas tout compris ce que tu veux dire , mais une fois le mep faite ça sera bon ?

**Comment by corentin-begne** [comment]
ça devrait vu que je peux pas test

**Comment by kapeco** [comment]
ok fait moi sign quand je pourrais test alors

**Comment by kapeco** [comment]
Je ne vois toujours rien sous mandrill

**Comment by corentin-begne** [comment]
je check

**Comment by corentin-begne** [comment]
quand je test en prod je vois pas de nouveau mail dans mon mandrill et en dev ça fonctionne donc ça devrait le faire. sinon balance ton compte que je matte.

**Comment by kapeco** [comment]
accès envoyés par mail

**Comment by kapeco** [comment]
mais comme je te dis , aucun mail n'est réceptionné sur aucune des deux boite mail configurées pour le moment

**Comment by corentin-begne** [comment]
pff tu l'as mis en test key
![image](https://cloud.githubusercontent.com/assets/4975024/8763674/9b573c72-2da9-11e5-89cf-6080af4f6b25.png)

**Comment by corentin-begne** [comment]
si tu matte les logs de l'api tu vois bien que les accès qu'il y a eu. Apparemment tu peux pas modifier la clé existante de test en normal, je vais en créer une nouvelle pas de test, la mettre dans le projet et refaire une mep

**Comment by corentin-begne** [comment]
c'est en prod !

**Comment by corentin-begne** [comment]
ça à l'air de fonctionner, vous recevez les mails ?

**Comment by kapeco** [comment]
ben merde alors ...

La le mail est bien envoyé mais aucune traces sur outbond

**Comment by corentin-begne** [comment]
si c bon je le vois mtn, c pas instantané

**Comment by kapeco** [comment]
ah si c'est bon , ça met juste un peu de temps effectivement

**Comment by corentin-begne** [comment]
si tu doute matte api logs dans settings

**Comment by kapeco** [comment]
non c'est bon , nickel même
