### ISSUE TITLE
Probleme avec le mail suivant la création d'un user

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#73]
En effet le mot de passe envoyé dans le corps du mail est resté à 123456 alors que j'ai forcément mis autre chose
Du coup j'ai eu des appel à cause d'une impossibilité de se logger

**Comment by corentin-begne** [comment]
ah bah ouais je croyais que tu m'étais auto 123456 pour obliger l'user à le changer, ça se fait fréquemment et aussi le mdp je l'ai plus, il est encodé dans la partie client, je ne peux pas l'envoyer à l'user.

**Comment by kapeco** [comment]
Ok
