### ISSUE TITLE
Tarifs

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#74]
Je regarde comment ajouter des tarifs , il y a trois champs : 

area | nb | value

Je ne comprend comment tu fais la relation avec le nombre de pièce  !  y a une autre table ? c'est en dur dans le code ?

**Comment by corentin-begne** [comment]
c'est secret je te le dirai pas ! le seul truc qu'il y a en dur dans le code c'est +30€ si c'est une maison.

**Comment by kapeco** [comment]
Hum hum 
Comment ajouter d'autres tarifs alors , car faut que je sois autonome pour cette partie la aussi

**Comment by corentin-begne** [comment]
je déconne xD
donc si la surface associé au nb de pièce est supérieur à celle saisie je prends celle ci pour les calculs ce qui correspond à area. nb correspond aux nb de diagnostics qui doivent être réalisés et ça donne cette requete :  
```
select max(value) as price where area < :area and nb = :nb
```
+30 si maison et 0 si surface supérieur à 170 pour mettre le formulaire de contact.

**Comment by kapeco** [comment]
Ok donc si je rentre juste des donnée dans le tableau ça ne sert a rien , faut aussi allonger la liste du nombre de pièces

**Comment by corentin-begne** [comment]
oui c bloqué en dur ça par contre, tu peux juste changer les prix parce que si tu change les autres valeurs ça va foirer.

**Comment by kapeco** [comment]
Ok merci 
Quand j'ajouterai des prix on verra ça ensemble alors

**Comment by kapeco** [comment]
bon j'ai les prix, je fais quoi , je les rentre en DB ? ou je t'envois un fichier exel avec tout dedans ?

**Comment by corentin-begne** [comment]
bah faut que je me mette en place un système complet où le select est basé sur les prix présent en bdd sinon on va toujours galérer

**Comment by kapeco** [comment]
ok tiens moi au courant
ça serait bien d'être complétement indépendant , genre je rentre meme le nombre de pièce en

**Comment by corentin-begne** [comment]
c'est fait !
donc le select du devis est pluggé sur les tarif de la bdd, il récupère la liste des surfaces.
pour les ajouter correctement, il faut les ajouter pour tous les nb de diag.
jte laisse test si c'est ok je le mettrai aussi dans l'odm comme tu voulais

**Comment by kapeco** [comment]
ok c'est bien mais je ne voit pas ou ajouter le nb de pieces

**Comment by corentin-begne** [comment]
c'est progressif par rapport au à la surface

**Comment by corentin-begne** [comment]
15 chambre
30 1 pièce
20 2 pièces
...

**Comment by kapeco** [comment]
Oui mais non , là je rajoute 10 pièces

**Comment by corentin-begne** [comment]
tu zaap celles entre deux quel intérêt ?
si veux  ça, je dois refaire toute la structure de cette table et donc refaire le système de calcul

**Comment by kapeco** [comment]
hein ? je ne zape rien, j'ajoute juste des tarifs qui vont des pièces 7 à 10

**Comment by corentin-begne** [comment]
bah alors c'est bon.
la le 170 c'est pour 6 pièces, si t'ajoute une surface supérieure ça sera pour 7 pièces, une autre et ça sera pour 8 pièeces etc et il a joute max pièce +1 et supérieur pour mettre le formulaire de contact.
je croyais que tu voulais passer de 6 à 10 direct ...

**Comment by corentin-begne** [comment]
si tu veux mieux comprendre, il fait un 
```
select disctinct area from Price where are > 0 order by area
```
et de ça il construit le select que tu as de chambre à piece +1 et sup

**Comment by kapeco** [comment]
ah ben nickel ton système

**Comment by kapeco** [comment]
par contre c'est au dessus du dernier enregistrement qu'il propose le formulaire de contact automatiquement ou c'ets écrit en dure ?

**Comment by corentin-begne** [comment]
c'est automatique, par exemple la valeur max c'est 270 pour 6 pièces du coup il ajoute 271 pour 7 pièces et plus comme ça ça matche pas et il met le formulaire

**Comment by kapeco** [comment]
yes je vois ça , go to MEP alors

**Comment by corentin-begne** [comment]
c'est en prod !

**Comment by kapeco** [comment]
yes jai vu merci

faudrait juste ajouter un coût que j'oublie souvent

Tu sais que pour une maison on ajoute + 30 €
Mais quand la surface > 250 m² c'est + 50 € au lieu des +30€

**Comment by kapeco** [comment]
hum y a un souci dans le calcul du prix 
![2015-07-27 19_27_13-devis gratuit](https://cloud.githubusercontent.com/assets/11981295/8912833/91e0e146-3495-11e5-874b-a8d1b4698dea.png)

**Comment by corentin-begne** [comment]
c'est modifie et en prod !
j'espère que tu as mis une entrée pour chaque nb de diag sinon c'est normal que ça fasse de la merde

**Comment by kapeco** [comment]
je revérif

**Comment by kapeco** [comment]
merde y a un bordel entre la 6 ème et la 7eme piece ... vais voir comment corriger

**Comment by kapeco** [comment]
c'est tout bon :)
