### ISSUE TITLE
quelques erreurs

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#76]
voir ici

https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.kapeco.com%2F

**Comment by corentin-begne** [comment]
j'ai modifié le content-language et j'ai encodé le nom des villes dans le footer. par contre l'attribut basepath dans le body et des id qui se répète dans les liens j'en ai besoin, c'est galère de changer et je vois pas en quoi ça les regarde.

**Comment by kapeco** [comment]
ok ça marche au moins c'est déjà ça de corrigé , merci
