### ISSUE TITLE
soucis avec "lier à google"

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#77]
Mon frère n'arrive pas à lié a son google agenda

![agenda](https://cloud.githubusercontent.com/assets/11981295/8767373/c1f5b1f4-2e5a-11e5-9533-98e920daf7b5.png)

**Comment by corentin-begne** [comment]
c'est parce que je n'ai pas créé l'app prod, je n'ai fait que pour dev et preprod. Je vais mettre la version prod mais je ne pourrais pas faire de mep tout de suite.

**Comment by kapeco** [comment]
hum ok , donc mon compte n'est pas lié non plus ?

Je pensais que c'était en prod cette partie là

**Comment by corentin-begne** [comment]
c'était en prod mais on avait pas test, on avait test qu'en preprod et du coup pour la prod je dois créer une autre app avec une callback qui pointe sur le domaine configuré.

**Comment by kapeco** [comment]
ok donc on crée des agences et des users et si ils commencent à nous envoyer des odm on ne verra rien dans notre agenda ? ... hum ... embettant ça  !
dis moi quand tu peux mettre ça en prod aussi car sinon on va passer pour des charlots

**Comment by corentin-begne** [comment]
bah c'est clair mais bon faut bien test avant, je penser que  t'allais faire plein de test avant de lancer vraiment en prod cette partie Je ne pourrais mettre en prod que quand tu m'auras validé les nouveaux users car je suis sur la même branche.

**Comment by kapeco** [comment]
je pensais que c'était déjà en prod depuis longtemps c'est pour ça

**Comment by corentin-begne** [comment]
oui mais t'as pas test du coup j'avais oublié de créer une app pour la prod vu que cet environnement n'existait pas quand je l'ai fait

**Comment by kapeco** [comment]
ok je pige , bon pas trop grave , je te laisse finaliser ça

**Comment by corentin-begne** [comment]
c'est en prod

**Comment by kapeco** [comment]
ok je demande à mon frère de tester

**Comment by corentin-begne** [comment]
tu peux test avec ton compte en déliant et reliant

**Comment by kapeco** [comment]
même erreur que pour mon frère :(
je ne peux plus lier

**Comment by corentin-begne** [comment]
ok je regarde ça

**Comment by kapeco** [comment]
![2015-07-26 21_42_04-parametres](https://cloud.githubusercontent.com/assets/11981295/8895567/36fb5a10-33df-11e5-98d0-a77c78e8c8d8.png)

**Comment by corentin-begne** [comment]
j'ai trouvé, il avait mis https par défaut, je corrige et je refais une mep

**Comment by kapeco** [comment]
ok

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
nickel
