### ISSUE TITLE
Soucis avec le devis

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#78]
![2015-07-20 16_44_56-devis gratuit](https://cloud.githubusercontent.com/assets/11981295/8778673/81cb4eea-2eff-11e5-95a1-d19d11a478aa.png)

Comme tu peux le voir la dessus il manque plusieurs diag : 
1) le gaz qui est pourtant bien coché !!!
2) l'électricité puisque ça date de plus de 15 ans

**Comment by corentin-begne** [comment]
dans mes règle le diag gaz n'est mis que si date < 1er juillet 1997 et gaz coché bien sur.
Pareil pour l'électricité ça n'est mis que si date < 1er juillet 1997.
par rapport aux règles que tu m'as dit

**Comment by kapeco** [comment]
ah ben non , gaz et élec c'est si >15 ans
Je n'ai pas pu dire ça dans les règles, c'est la base

Pas grave , faut corriger

**Comment by corentin-begne** [comment]
ça veut dire tout le temps du coup c'est bizarre, je me basais sur la dernière date du select sinon elle ne sert à rien. Il ne faut pas juste ajuster la date pour que ça fasse 15 ans ? ça serait plus logique

**Comment by corentin-begne** [comment]
et pour éviter de changer tout le temps, le select devrait plutôt être du genre (je mets au hazard) : 
>15 ans
>30 ans
>50 ans
...
selon les valeurs utiles à la détermination des diagnostics

**Comment by kapeco** [comment]
non du coup quand on selectionne "après le 1er juillet 1997" , faut ajouter un champs dans lequel on peut mettre l'année
Imagine que c'est construit depuis 14 ans , alors effectivement pas de gaz ni d'élect ..; mais les années passent et l'année prochaine il faudra le gaz et l'elect parcequ'on sera à 15 ans

**Comment by corentin-begne** [comment]
d'où ce que je viens d'écrire

**Comment by corentin-begne** [comment]
sinon les dates ne servent à rien

**Comment by kapeco** [comment]
si si faut laisser comme c'est écrit, dans les norme et juridiquement c'est comme ça qu'il faut l'afficher

**Comment by corentin-begne** [comment]
bah du coup mettre les bonnes dates à jour tout le temps alors si c'est juridique ou alors ils disent qu'il faut mettre ces dates là ? et du coup pour plomb et aussi amiante aussi ? va falloir que je refasse la partie php et js :/ et si on fait comme tu dis les dates du select ne servent à rien vu qu'elle ne représente pas les bonnes périodes.

**Comment by corentin-begne** [comment]
parce que la version avec ajout d'un champ pour mettre l'année si 1er Juillet 1997 ça n'existe pas et ça n'était pas prévu, sur l'odm non plus.

**Comment by kapeco** [comment]
il fait respecter les bornes mis par les date actuelles 
Mais il faut aussi ajouter l'électricité si > 15 ans , idem pour le gaz si il est coché .
Y a pas gros changement , uniquement lorsque qu'on se trouve après 1997

**Comment by corentin-begne** [comment]
donc je les met tout le tps en fait

**Comment by corentin-begne** [comment]
ok c'est fait côté devis, je n'ai pas touché à la partie ODM.

**Comment by kapeco** [comment]
Merci pour le côté devis . Et comme tu l'as deviné il faudra mettre à jour le côté odm

**Comment by corentin-begne** [comment]
bah côté odm ya pas l'info gaz donc je le met jamais et élec si on se base sur ce que tu m'as dis, je dois le mettre tout le tps donc dès qu'il touche à n'importe quelle caractéristique je lui remet ?

**Comment by kapeco** [comment]
mais si tu as l'habitude de faire nimp ;) c'est juste qu'on ne se comprend pas 

" élec si on se base sur ce que tu m'as dis, je dois le mettre tout le tps"  je ne vois pas ce que tu veux dire , elec on ne le met pas tout le temps , uniquement si l'installation à plus de 15 ans
l'odm doit reprendre les règles du devis ce qui me semble normal

**Comment by kapeco** [comment]
Par contre tu dis que c'est fait côté devis mais je ne vois rien :(
Quand je met "après le 1er juillet 1997" ça ne me propose pas un nouveau champs pour rentrer une date exacte

**Comment by corentin-begne** [comment]
ah ouais j'ai pas ajouté de champ pour saisir de date, j'ai juste changer pour si tu sélecitonne gaz ça le met tout le tps quelque soit la date et élect ça le met tout le temps aussi donc pour que ça corresponde a tes dates. Ajouter un champ encore mais je comprends pas pk tu me dis ça que mtn alors ça te semble normal

**Comment by kapeco** [comment]
Pour le champs je te l'ai deja dit plus haut , mais si on remonte plus loin dans le temps , c'est tout simplement que je fait peu de diag sur des maisons récente et du coup je n'étais pas confronté au probleme. que je découvre avec l'expérience terrain du coup

**Comment by corentin-begne** [comment]
oui mais on a retravaillé sur le devis et l'odm ya pas lgtps,on aurait pu le faire en même tps. Pour ça et la partie user j'en ai jusque la semaine prochaine, je ne pourrais pas faire de mep avant.

**Comment by kapeco** [comment]
ok on est vendredi ca tombe bien ;)

**Comment by corentin-begne** [comment]
on serait pas mardi plutôt xD le plus chiant c'es pour ton push et google agenda. Après j'aurais peut être fini avant mais je préfère te dire large pour être sur.

**Comment by kapeco** [comment]
ça marche mon petit 

Ah oui on est que mardi je me voyais déjà bientot la semaine prochaine lol

**Comment by corentin-begne** [comment]
je t'ai ajouté le champs pour mettre la date si le user sélectionne après le 1er Juillet 1997, un check est fait sur la date et si > 15 ans je met diag élect et si coché gaz je le met aussi.
valide ça et je mets pareil sur l'ODM

**Comment by kapeco** [comment]
Ok fonctionne nickel :)

MEP pour ça et pareil pour l'ODM
D'ailleurs au passage tu peux ajouter le nombre de pièce dans l'ODM stp

**Comment by kapeco** [comment]
tout good  pour le devis mais pour l'ODM ça reste a faire

**Comment by corentin-begne** [comment]
c'est en place sur l'odm aussi

**Comment by corentin-begne** [comment]
je t'ai mis en place le double select année/mois selon l'année selectionée sur la partie devis.
check que ça fonctionne bien et que ça correspond à ce que tu veux et je le met sur l'odm

**Comment by kapeco** [comment]
impec => ODM

**Comment by kapeco** [comment]
punaise faut que tu ailles passer une nuit en roulotte plus souvent , ;)

**Comment by corentin-begne** [comment]
c'est fait dans l'odm, création/édition et alert check bien que ça fonctionne correctement.

**Comment by kapeco** [comment]
c'est beau ... :)

par contre je pense qu'il y a un soucis , je met octobre 2000 , donc moins de 15 ans et ça propose toujours l'élec , si javais mis juillet j'aurai compris

**Comment by corentin-begne** [comment]
c'est corrigé, j'avais oublié de répercuter un changement à la fin

**Comment by corentin-begne** [comment]
check bien tout et jte fais une mep ce soir

**Comment by kapeco** [comment]
ah ah ah 

tu vois je check ;)

**Comment by kapeco** [comment]
ça ne marche toujours pas , même soucis, j'ai mis septembre apres avoir choisi juillet et "electricité" reste !!

**Comment by corentin-begne** [comment]
dès que tu mets >= septembre ça enlève élect, je viens de test , vide ton cache sinon.

**Comment by kapeco** [comment]
je n'ai pas de cache , ça marche sous chrome mais pas sous firefox

**Comment by corentin-begne** [comment]
ah bon bizarre, je vais check ça t'al

**Comment by kapeco** [comment]
ok
moi je file le boulot m'appel

**Comment by corentin-begne** [comment]
dsl mais ça fonctionne aussi nickel chez moi sur ff que ce soit sur la partie devis ou ODM.

**Comment by kapeco** [comment]
je met sept 2000 sans passer par autre chose et ça me le coche direct !!!

Fait la mep, je verrais bien sur l'autre nom de domaine comment ça se comporte
Mais je n'ai pas de cache , j'ai vidé le cache au cas ou et toujours pareil , donc je retesterai en prod

**Comment by corentin-begne** [comment]
?

**Comment by kapeco** [comment]
ben ouais du coup je part du principe que ça viens de chez moi , donc MEP et on verra

**Comment by corentin-begne** [comment]
j'ai trouvé le bug sur ff, j'avais mal testé, je vais essayer de corriger.

**Comment by corentin-begne** [comment]
c'est corrigé, je vais faire la mep

**Comment by corentin-begne** [comment]
c'est en prod !

**Comment by kapeco** [comment]
Ah super je ne suis pas fou 😊 
Merci
Le reste aussi est en prod ?

**Comment by kapeco** [comment]
mep ok
