### ISSUE TITLE
Mail lors de la création d'un user

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#80]
Quand on crée un user c'est toujours envoyé depuis contact@kapeco.com
Ca serait bien que ce soit envoyé via le mail du compte qui est loggué pour créer l'user

**Comment by corentin-begne** [comment]
ok

**Comment by kapeco** [comment]
merci

**Comment by corentin-begne** [comment]
c'est fait

**Comment by kapeco** [comment]
Au top Superman 😉 mep

**Comment by kapeco** [comment]
c'est tout bon
