### ISSUE TITLE
Demander un rdv

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#81]
Je viens de penser à une amélioration
Lorsque quelqu'un fait un devis, pour le moment ça s'arrete là sauf si il dépasse un quota et dans ce cas il y a le formulaire de demande de devis personnalisé

L'idée concerne les devis "classique" . apres le détail du devis on pourrait mettre un bouton "Demandez un rendez-vous pour effectuer les diagnostics" , si on clic ca ouvre un formulaire d'envois de demande de rendez-vous avec les infos du devis pré-remplies

objet "demande de rendez-vous"

body "Pouvons nous planifier un rendez vous afin de réaliser les diagnostics concernant le bien suivant : 
.... contenu venant du devis ...

"

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
c'est super , faudrait juste changer la couleur du bouton en vert comme le bouton devis

**Comment by corentin-begne** [comment]
je l'ai mis en vert mais pas comme le bouton du devis car c'est une image sinon tu me file une couleur, un dégradé ou une image comme tu veux.

**Comment by kapeco** [comment]
c'est impec comme ça pour le moment ;)

tu l'as taggé pour analitycs  ?

sinon voici le tag : "rendez-vous"

**Comment by kapeco** [comment]
et puis => MEP

**Comment by corentin-begne** [comment]
ok j'ai ajouté le tag analytics.
je ferais une mep lorsque j'aurai fini la date de construction dans l'ODM

**Comment by kapeco** [comment]
ça marche :)
alors cette roulotte  ?

**Comment by corentin-begne** [comment]
nickel, en plus il faisait trop beau ça déchirait :)

**Comment by kapeco** [comment]
T'as tout déchiré alors  xD

**Comment by kapeco** [comment]
mep ok
