### ISSUE TITLE
fonction pour les users agence

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#82]
Il faudrait ajouter un champs "fonction" pour les users
afin que l'on puisse savoir si un user s'occupe de la vente , de la loc ou autre
varchar 255 je pense

et donc répercuter ça aussi dans les champs listés dans le liens diagnostics

**Comment by corentin-begne** [comment]
ok pas de pb mais tu veux que ça soit un texte ouvert ou une liste fermée que tu pourrais gérer par le BO par exemple ?

**Comment by kapeco** [comment]
hum je pense qu'une liste gérable serait mieux effectivement

Par contre ensuite on va attaquer le BO , car c'est un bordel quand on a pleins d'agence , enfin on verra ça terminons déjà tout ce qui est sur le feu

**Comment by corentin-begne** [comment]
par contre ça sera les mêmes fonctions pour tous les type d'user et ils devront tous en avoir une

**Comment by corentin-begne** [comment]
pour le BO si tu veux autre chose que les form auto ça va faire autant de dev que sur le front

**Comment by kapeco** [comment]
Faut pas que ce soit obligatoire

**Comment by corentin-begne** [comment]
ok du coup ça sera dans un lien à part, pas directement à la création de l'user

**Comment by kapeco** [comment]
Ah bon 😞 c'est la misère ca déjà qu'on a pas tout sous la main ...

**Comment by kapeco** [comment]
Dans ce cas rend le obligatoire 
Avec la liste suivante 
Transaction
Location
Technicien 
Manageur 
Responsable 


Par défaut c'est transaction qui est positionné car ça va être 90% des cas

**Comment by corentin-begne** [comment]
bah oui mais si tu le veux pas obligatoire, je dois le mettre la liaison entre user et fonctions dans une table à part donc un lien en plus.
Ok je vais faire ça.

**Comment by corentin-begne** [comment]
c'est fait !
donc tu as un lien Fonctions utilisateurs dans le BO que j'ai init avec les fonctions que tu as définit et dans user tu peux affecter une fonction à un user (functions). j'ai ajouté aussi l'info dans le listing user dans les diagnostics

**Comment by kapeco** [comment]
C'est impec !
MEP

**Comment by corentin-begne** [comment]
ok je vais faire la MEP. par contre je faisais une sauvegarde de la bdd avant de commencer et elle fait déjà 227 Mo :/

**Comment by corentin-begne** [comment]
le mep est faite !!!
check bien que tout ce que j'ai fais est ok

**Comment by kapeco** [comment]
ca c'est ok
