### ISSUE TITLE
Mail lors de l'envois d'un diag

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#83]
très bien ce site
comment sais t on qu'un diag est disponible sur votre site après intervention chez le client ?
Très cordialement
Cabinet SOGIM

Faudrait donc ajouter l'envois d'un mail à l'user quand on lui met à dispo un diag

Objet : KAPECO Diagnostic : Notification de mise à disposition de document

body : 
"Bonjour,

Nous vous informons que des documents ont été déposé dans votre espace client Kapeco.

Pour les consulter, merci de vous connecter sur: KAPECO - Diagnostics (liens vers : http://www.kapeco.com/diagnostic/find )

L'équipe KAPECO."

**Comment by corentin-begne** [comment]
ok

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
C'est c'est bien 😊 toi ton mep

**Comment by kapeco** [comment]
impec je ferme
