### ISSUE TITLE
Visualisation de qui DL

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#85]
Quand on passe la souris sur le lien de DL dans diagnostic en tenps qu'admin , on peux voir qui à DL et combien de fois, ça serait bien de voir la date/heure aussi

**Comment by corentin-begne** [comment]
ben là c'est groupé par user donc tu peux pas trop et si on liste ça va vite devenir illisible sur ça

**Comment by kapeco** [comment]
on peux mettre l'info de date du dernier DL

**Comment by corentin-begne** [comment]
ok

**Comment by corentin-begne** [comment]
c'est fait !

**Comment by kapeco** [comment]
nickel => MEP

**Comment by kapeco** [comment]
ok
