### ISSUE TITLE
Meta pour les faux liens

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#86]
Je suis sur la page http://www.kapeco.com/diagnostics-immobiliers/diagnostic-gaz/chantilly

<title>Diagnostic gaz - Kapeco</title>
<META Name="Title" Lang="fr" Content="Diagnostic gaz - Kapeco">
<META Name="Description" Lang="fr" Content="Diagnostic immobilier,  diagnostic gaz,  Kapeco">
<META Name="Keywords" Lang="fr" Content="Diagnostic immobilier, Diagnostics immobiliers,  diagnostic gaz, gaz,  Kapeco">

Comment est-ce que je peux gerer ces méta ?

**Comment by corentin-begne** [comment]
tu ne peux pas, les faux liens ont les même meta que le lien auquel ils sont associés

**Comment by kapeco** [comment]
ok
