### ISSUE TITLE
Connaitre la taille de la DB

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#87]
Afin de maitriser l'espace utilisé par la DB

ça serai bien depuis le BO de pouvoir consulter celle-ci, soit un clic qui générer l'info, soit directement un affichage en dur sous les liens 

voici la requette

SELECT round(sum(data_length+index_length)/1024/1024,4)
    FROM  INFORMATION_SCHEMA.PARTITIONS
    WHERE TABLE_SCHEMA = 'kapeco001'

**Comment by corentin-begne** [comment]
c'est fait !
par contre j'ai mis sum(data_length+index_length) et après selon la taille je mets le bon texte

**Comment by kapeco** [comment]
ok impec => MEP

**Comment by kapeco** [comment]
ok
