### ISSUE TITLE
Bouton de retour ne fonctionne plus

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#88]
![2015-07-26 21_00_49-rechercher un diagnostic](https://cloud.githubusercontent.com/assets/11981295/8895398/7674cbc8-33d9-11e5-8e5c-75192593e108.png)

Et dans certains cas il a même disparu

**Comment by corentin-begne** [comment]
effectivement, t'avais pas vraiment test en fait alors, je corrige ça

**Comment by kapeco** [comment]
ben pas les regressions non , juste els nouveauté

**Comment by corentin-begne** [comment]
c'est corrigé, jte laisse check et je refais une mep

**Comment by kapeco** [comment]
en preprod ou en dev ?

**Comment by corentin-begne** [comment]
dev

**Comment by corentin-begne** [comment]
preprod ça fait lgtps que j'ai pas fais, je vais galérer quand je vais devoir en faire une

**Comment by kapeco** [comment]
y a plus la pastille coté agence quand on leur met a dispo un diag

**Comment by corentin-begne** [comment]
je l'ai en dev

**Comment by corentin-begne** [comment]
tant qu'il a pas été dl

**Comment by kapeco** [comment]
pas en prod je viens d'up un diag pour un user test et y a pas de pastille

**Comment by kapeco** [comment]
par contre le mail est bien arrivé et ça c'est nickel

**Comment by corentin-begne** [comment]
quel user que je check ?

**Comment by kapeco** [comment]
Pour le bouton retour , c'est bon en dev

**Comment by kapeco** [comment]
lapinkrr@gmail.com

**Comment by corentin-begne** [comment]
c'est normal, il te compte en attente que les diag que tu peux dl

**Comment by corentin-begne** [comment]
vu que tu peux le décrémenter que quand tu le dl

**Comment by corentin-begne** [comment]
ce sont les odm qui se compte à la vision et ça tu me l'a bien spécifié me dis pas que c'est pas le bon fonctionnement

**Comment by kapeco** [comment]
yep c'est bon ça , mais pour les diags y avait pas une pastille aussi qui se décompte quand on à déjà dl au moins une fois ?

**Comment by corentin-begne** [comment]
oui mais elle ne se compte que si le diag peut être dl

**Comment by kapeco** [comment]
humm ... dans ce cas vais voir si faut étendre ça a tout les status ou pas , je ferai un nouveau issue si nécessaire
