### ISSUE TITLE
suite a la MEP

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#89]
JE ne sais pas ce que tu as changé coté perf mais voila
![chartdayservletstatehistory](https://cloud.githubusercontent.com/assets/11981295/8895729/534e64f0-33e4-11e5-9e25-5e8a9e7818ef.png)

**Comment by corentin-begne** [comment]
donc c'est une bonne chose ?

**Comment by kapeco** [comment]
carrément !!!

**Comment by corentin-begne** [comment]
cool, je vois pas trop ce que j'ai fais mais de toute manière je fais toujours gaffe aux perfs :)

**Comment by kapeco** [comment]
c'est bien ça c'est important
