### ISSUE TITLE
Grant access

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#9]
Permettre de mettre un utilisateur dans plusieurs groupes ou si tu préfères, atribuer plusieurs droits à un utilisateur

**Comment by corentin-begne** [comment]
actuellement c'est un droit par user, ça va me demander pas mal dev vu que je suis parti comme ça.
Dans quel but exactement ? les droits ne se croisent pas à part pour ajouter le droit admin a un diagnostiqueur mais bon avoir un compte à part ça évite les erreurs aussi après c'est comme tu veux.

**Comment by kapeco** [comment]
ben jaimerai ne pas avoir trois comptes pour éditer depuis le front, editer depuis le backofice et travailler en tant que diagnostiqueur
Pareil pour mon frere et peut être d'autre a l'avenir alors avoir cette souplesse serait très appréciable

**Comment by kapeco** [comment]
je pense qu'il faut juste serialize les droits en DB , comme ça a la lecture tu dé-serialize , et ça fait pas trop de boulot.
Lors de la création d'un compte ou sa modification , les différents "groupe" apparaissent sous forme de multi checkbox

**Comment by corentin-begne** [comment]
sauf que si je fais ça on pourra plus éditer dans le backoffice, tout est basé sur des foreign key avec id, il faut obligatoirement que je fasse une table de lien intermédiaire et que je change tout le fonctionnel des permissions si tu veux ça.

**Comment by kapeco** [comment]
Krrrr krrrrr krrrrr 
Si tu ne le fait pas maintenant il faudra la faire plus tard , donc ....

**Comment by corentin-begne** [comment]
ok c'est fait, je t'ai supprimé tes anciens comptes et je t'ai créé un compte super admin / admin / diagnostiqueur :
francky
123456

**Comment by kapeco** [comment]
Tu vois c'était pas si long que ça à faire 😉 

Merci en tout cas , je vais tester

**Comment by corentin-begne** [comment]
non c'était pas si long mais c'est le fait de revenir sur un fonctionnement, il y a toujours un risque que j'ai oublié de changer des check à des endroits et que ça bug.

**Comment by kapeco** [comment]
Ouais je sais bien mais c'est plus souple comme ça 😊
