### ISSUE TITLE
ODM

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#90]
Ne par rendre obligatoire le tel du client

Quand on selectionne "appartement" ne pas rendre obligatoire étage et porte

Et de manière générale ajouter un champs "Nombre de pièces"

**Comment by corentin-begne** [comment]
c'est en place, avec le select nb de pièce du devis

**Comment by kapeco** [comment]
Faudrait plutôt un champs libre numérique

**Comment by corentin-begne** [comment]
ah bon pourtant c'est pas ce qu'on avait dit dans l'issue sur les tarifs #74  ?

**Comment by kapeco** [comment]
Non mais la c'est un odm on ne calcul pas le prix 
On veux connaître la surface et le nombre de pièces comme ça quand on part en mission on peut estimer le temps que ça va nous prendre

**Comment by corentin-begne** [comment]
bah la surface tu l'as pas là ... je peux changer si tu veux et mettre un champ numérique mais me refais pas changer après

**Comment by kapeco** [comment]
oui met juste un champs numérique et met un champs surface en numérique aussi comme ça ça sera complet et tu fais la MEP

**Comment by corentin-begne** [comment]
ok

**Comment by corentin-begne** [comment]
faudra que tu test avant quand même

**Comment by corentin-begne** [comment]
c bon tu peux test

**Comment by corentin-begne** [comment]
check bien aussi la date de construction création/édition/mail #78

**Comment by kapeco** [comment]
bon ça ne marche pas , j'ai coché non pour clef a l'agence et ça m'a envoyé oui en push

et je n'ai pas les coordonnées du proprio dans le push 

Et je n'ai pas recu de mail sauf un de toi

**Comment by kapeco** [comment]
je confirme , même erreur dans le mail

**Comment by corentin-begne** [comment]
j'ai pas testé clef de l'agence je vais voir par contre les coordonnée je les ai dans le mail, je les ai pas que si je coche que ce sont les même que celles du bien.
je test

**Comment by corentin-begne** [comment]
ok normalement c'est corrigé, tu peux test !

**Comment by kapeco** [comment]
faut toujours les avoir car comment on peut les connaitre sinon ? le client on ne le connait pas et c'est justement l'agence qui nous donne l'info

**Comment by corentin-begne** [comment]
bah non mais tu sélectionne non dans "Adresse du propriétaire différente de celle du bien ?" ça veut dire que l'adresse du proprio est celle du bien donc celle qui est indiqué au dessus, je vais la remettre quand même ...

**Comment by kapeco** [comment]
non je te parle du mail et du tel

**Comment by corentin-begne** [comment]
bah ils sont optionnel mtn donc je les met quand ils y sont

**Comment by kapeco** [comment]
depuis tout à l'heure je les met et je ne les ai pas dans mon mail et mon push 
sauf si je coche que l'adresse du proprio est dirrefente alors ca me met le mail et le tel du proprio en plus de l'adresse du poprio

**Comment by kapeco** [comment]
même si c'est optionnel , quand je les renseuigne j'aimerai bien les avoir ;)

**Comment by kapeco** [comment]
tu comprend petit ?

**Comment by corentin-begne** [comment]
effectivement je crois que ça bug je check

**Comment by kapeco** [comment]
j'en suis sur moi xD

**Comment by corentin-begne** [comment]
ok j'ai trouvé tu peux retest !

**Comment by kapeco** [comment]
et puis si dans le mail tu pouvais mettre le même ordre quand dans le formulaire 

je parle précisément de

type de bien
surface
nombre de pièce

au lieu de 

surface 
nombre de pièce 
type de bien

**Comment by corentin-begne** [comment]
c'est modifié !

**Comment by kapeco** [comment]
c'est tout bon maintenant :)

**Comment by corentin-begne** [comment]
cool je mep !

**Comment by kapeco** [comment]
non

**Comment by corentin-begne** [comment]
ah

**Comment by kapeco** [comment]
y a un soucis

j'ai mis année 2000 et ça a coché par défaut électricité
alors que ca ne fait pas encore plus de 15 ans

**Comment by corentin-begne** [comment]
ok je regarde

**Comment by kapeco** [comment]
par contre coté devis ça fonctionne bien

**Comment by corentin-begne** [comment]
bah si 2000 selon le mois ça fais plus de 15 ans ... sur l'odm le check est en js et sur le devis en php donc normal

**Comment by corentin-begne** [comment]
je viens de test ça fonctionne nickel au jour près

**Comment by kapeco** [comment]
pourquoi y a une différence entre l'odm et le devis alors ?

**Comment by kapeco** [comment]
dailleurs tu viesn de souvelever un soucis, on ne demande jamais le mois quand ça tombe pile sur la quizieme anée ...

**Comment by kapeco** [comment]
lol j'ai tellement bien écrit qu'on dirait que je suis bourré mdr :D

**Comment by corentin-begne** [comment]
j'ai le même résult des deux côté, pour le 200-01-01 il me met électricité partout.
je comprends pas ce que tu dis, je calcul par rapport à la date actuelle donc le mois est bien pris en compte vu qu'il est entré dans l'input

**Comment by kapeco** [comment]
toi tu rentre le mois, mais le gars peut dire 2000  alors que ça peut être décembre 2000

**Comment by corentin-begne** [comment]
il est obligé de mettre une date yyyy-mm-dd

**Comment by corentin-begne** [comment]
avec le picker

**Comment by kapeco** [comment]
ben non , jusqu'a maintenant j'ai toujours mis que l'année, ya pas de picker

**Comment by corentin-begne** [comment]
ton browser c'est de la merde, moi j'ai un date picker sous chrome

**Comment by kapeco** [comment]
mais c'est une bonne idée le picker ;)

**Comment by corentin-begne** [comment]
qui oblige a saisir une date yyyy-mm-dd

**Comment by kapeco** [comment]
moi j'ai juste un champs alpha numérique ou numérique d'ailleurs je ne sais meme pas

Faut valider sous firefox aussi et IE alors

**Comment by corentin-begne** [comment]
html5 ... je vais pas mettre un date picker js our les browser pourri alors que c natif check sous chrome tu verras

**Comment by corentin-begne** [comment]
à la limite je pourrais si tu veux parce qu'il est déjà chargé pour la date d'intervention mais bon c'est con quand même et sur le devis par contre  ça n'y est pas

**Comment by kapeco** [comment]
oui je viens de check sous chrome , y a un picker effictivement , pas très pratique comme picker mais y en a un.

**Comment by kapeco** [comment]
faudrait mettre juste un petit picker tout simple , tu clic sur le champs ça ouvre le picker sans laisser la possibilité de saisie dans le champs. on clic juste dans les cases du picker et c'est tout , ca rla je me suis embrouillé en essayant de rentree la date a la main , et ensuite j'ai vu la fleche pour ouvrir le picker.
Alors si moi je m'embrouille je n'imagine même pas les autres

**Comment by corentin-begne** [comment]
hmm ok je vais voir ça faut que je mette sur le devis aussi j'imagine

**Comment by kapeco** [comment]
bien deviné sinon ça fausse tout

**Comment by corentin-begne** [comment]
bah ouais surement pour ça que les calculs sont foiré moi je m'attends a avoir une date

**Comment by kapeco** [comment]
ben ouais je comprend mieux maintenant

**Comment by kapeco** [comment]
un truc comme ça tout simple http://jqueryui.com/datepicker/
mais en français

**Comment by corentin-begne** [comment]
bah je vais utiliser celui qu'on a déjà

**Comment by corentin-begne** [comment]
c'est celui là de toute façon

**Comment by kapeco** [comment]
avec l'heure et tout ?
c'est pas terrible

**Comment by corentin-begne** [comment]
non avec l'heure c'est un mixe qui est le datetimepicker mais ya le datepicker sans l'heure aussi

**Comment by kapeco** [comment]
ça va alors :)

**Comment by corentin-begne** [comment]
c'est bon ! test et je mets sur le devis

**Comment by kapeco** [comment]
c'est exactement ce que je ne voulais pas, imagine pour revenir à Mars 2000 le nombre de clic qu'il faudra faire  !!!!

**Comment by corentin-begne** [comment]
vas y restest, ya un select pour changer d'année mtn

**Comment by kapeco** [comment]
impec :)

**Comment by corentin-begne** [comment]
j'ai mis sur devis aussi

**Comment by kapeco** [comment]
ok par contre galère pour aller avant 2005

**Comment by kapeco** [comment]
affiche au moins les 15 dernière année dans le select

**Comment by corentin-begne** [comment]
recheck

**Comment by kapeco** [comment]
ouais c'est bon , ça commence après 1997, nickel

Mais je me demande si on ne s'est pas pris la tête pour rien

Le gars qui à 2000, il rentre juste 2000 et ça suffit
Par contre le gars qui tombe l'année des 15 ans , on le demande le moi en plus 
comme ça pas de datepicker, juste un champ numérique voir un deuxième si on est à 15 ans

**Comment by corentin-begne** [comment]
mtn que c fait on pourrais peut être laisser ?

**Comment by kapeco** [comment]
je viens d'édit le message du dessus

**Comment by kapeco** [comment]
faut qu'on aille vraiment toujours au plus simple pour l'utilisateur , donc qu'il faudrait mieux faire comme je viens de l'expliquer

**Comment by corentin-begne** [comment]
c'est super galère ton truc alors que le datepicker oblige à choisir une date et je l'ai déjà mis en place

**Comment by corentin-begne** [comment]
c vraiment pas pratique ton truc en plus niveau user c beaucoup plus simple et pratique un picker

**Comment by kapeco** [comment]
je suis désolé , mais je me suis laissé embarqué dans le datepicker car tu avais déjà mis ça sans que je m'en rende compte, mais après réflexion c'est beaucoup plus simple pour l'utilisateur sans date picker, il rentre juste une annéé et il passe a la suite. et si il tombre la quizième année on lui demande le mois en plus et c'est tout , 
ça ne concernera que très peut de personne (15ème année ) alors autant faire comme ça

**Comment by kapeco** [comment]
sinon à chaque fois il va falloir qu'ils se posent la question du mois ... et ça va leur prendre la tête pour rien car ils ne seront quasi jamais dans la quizième année

**Comment by corentin-begne** [comment]
tu fais galérer ... bah dsl je vais pas pouvoir faire ça mtn ça me fait changer plein de truc et ajouter du js

**Comment by kapeco** [comment]
ouais je comprend
si tu peux mettre les autres changement en prod, on mettra ca a la mep suivante

**Comment by corentin-begne** [comment]
si je fais une mep t'as tout ou rien avec ce que je viens de faire

**Comment by kapeco** [comment]
met tout alors car le reste c'est important, ensuite on reviendra sur cette partie uniquement

**Comment by corentin-begne** [comment]
parce que de toute façon sur le devis on l'avais déjà mis et ça devait foirer sur autre que chrome et ceux qui support l'input date html

**Comment by corentin-begne** [comment]
ok

**Comment by kapeco** [comment]
après faut que tu ailles t'allonger auprès de ta belle  ;)

**Comment by corentin-begne** [comment]
ouais :D

**Comment by kapeco** [comment]
et moi aussi d'ailleurs ... elle doit croire que je chat avec des nana mdr :)

**Comment by corentin-begne** [comment]
^^

**Comment by corentin-begne** [comment]
c'est en prod !

**Comment by kapeco** [comment]
un truc de fou , il manque l'étage

**Comment by kapeco** [comment]
mais va te coucher tu fera ca en même temps que le reste

**Comment by corentin-begne** [comment]
à quel niveau (si je peux check vite fais)

**Comment by kapeco** [comment]
ben partout

dans l'odm je met un étage et ça ne le met ni dans le puch ni dans le mail ni nullpart

**Comment by kapeco** [comment]
pour info j'ai testé avec l'étage 0 pour dire rez-de-chaussée car c'est un champs numérique

**Comment by kapeco** [comment]
o c'est bon j'ai vu l'étage dans ton dernier ODM , tu peux pousser en prod

**Comment by corentin-begne** [comment]
en fait c'est 0, il le considère vide, je vais corriger

**Comment by kapeco** [comment]
ah ok

**Comment by kapeco** [comment]
nickel , étage 0 ;)
tu peux pousser

**Comment by corentin-begne** [comment]
c'est en prod !

**Comment by kapeco** [comment]
ok merci je check

**Comment by kapeco** [comment]
tout bon :)

Merci fiston Krrrrrrrrrrrr

**Comment by corentin-begne** [comment]
np ;)

**Comment by kapeco** [comment]
Bon y a quand même un souci dans agenda 

j'ai crée un ODM avec un agence test qui s'appel agence franck

et le titre de mon ODM c'est 
Mission diagnostic agence Efficity Julien Lemercier [8 rue boucry 75018 PARIS-18E--ARRONDISSEMENT]

J'ouvre un issue pour ça , on verra plus tard

**Comment by corentin-begne** [comment]
je passais par là, j'ai corrigé et mis en prod !

**Comment by kapeco** [comment]
nickel merci
