### ISSUE TITLE
Diag

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#93]
![2015-07-31 10_22_59-rechercher un diagnostic](https://cloud.githubusercontent.com/assets/11981295/9003422/2d1a6620-376e-11e5-8031-e34ccac9c017.png)

Ajouter une colonne "date" entre "note" et "état", avec en plus lors du survol la possibilité de voir l'heure du dépot.

**Comment by corentin-begne** [comment]
c'est fait, ça fonctionne nickel en dev mais prod vu que mysql n'est pas à la bonne version, les date doivent être à 0, j'ai ajouté ce qu'il faut dans les requête mais ça ne fonctionnera que pour les prochains créé. Pareil pour les autres date (download, user, agence, mission)

**Comment by kapeco** [comment]
impec, on verra ça en prod => MEP

**Comment by kapeco** [comment]
mep ok
