### ISSUE TITLE
[ URGENT] Soucis avec ODM

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#94]
Y a un souci avec les info qui arrive dans une demande d'ordre de mission et celle qui se mettent dans google agenda:

Tu verras qu'il n'y a pas les infos concernant les coordonnées du client et également le champ clés à l'agence est un coup oui un coup non : 

ça c'est ce qui est arrivé par mail : 

Type de mission : Vente
Type de bien : Maison
Annee de construction : Entre 1949 et 1997
Adresse du bien : 26, allée Rémond 93190 LIVRY GARGAN

Nom du propriétaire : VAUTROT
Adresse du propriétaire :
Email du propriétaire : michel@blueline.fr
Tél du propriétaire : 0684622248

Missions :

- Dpe
- Amiante
- Gaz
- Electricite
- Termites
- Ernt

Date d'intervention souhaitee :
Clef a l'agence ? oui
RDV avec le client sur le lieu ? oui
Règlement : Client

Notes : proposer un devis et prendre rdv rapidement

et ça c'est ce qui s'est mis dans l'agenda
![image](https://cloud.githubusercontent.com/assets/11981295/9022238/5e155702-386e-11e5-8818-9c4b922ee111.png)

**Comment by corentin-begne** [comment]
je check

**Comment by corentin-begne** [comment]
j'ai corrigé quelque trucs et j'ai ajouté les nouveaux, ça devrait fonctionner correctement, tu peux tester en dev.

**Comment by corentin-begne** [comment]
tu pourras pas test en dev mais check les changements que j'ai fais mail, édition, création etc et je ferais une mep

**Comment by kapeco** [comment]
Je test ou si je peux pas test en dév ?

**Comment by corentin-begne** [comment]
quand j'aurai fais la mep je te parle du reste

**Comment by kapeco** [comment]
Je pige pas tout la

**Comment by corentin-begne** [comment]
test par rapport aux changements que j'ai fais que tout fonctionne bien, normalement ce pb est réglé mais tu pourras pas test en dev donc tu me valide le reste et je fais une mep comme ça tu pourras testé google agenda.

**Comment by kapeco** [comment]
ok , bon je valide c'est bon

**Comment by corentin-begne** [comment]
bah non vu que tu veux que je vire le select avec le nb de pièce ...

**Comment by kapeco** [comment]
ok

**Comment by kapeco** [comment]
sinon cet anniv de pacs ... bien passé ? ;)

**Comment by corentin-begne** [comment]
c'est pas encore on part demain

**Comment by kapeco** [comment]
ah ouais vous allez ou ?

**Comment by corentin-begne** [comment]
http://www.au21.fr/roulotte-arras.php

**Comment by kapeco** [comment]
t'es devenu romantique ou c'est elle qui a réservé ;)

30 mn de Jacuzzi et de sauna ! ... ça va pas suffir ça :p

**Comment by corentin-begne** [comment]
c'est elle qui a trouvé bien sur mais ça à l'air cool :)
non c'est clair mais ya une piscine dehors, ya intérêt à faire super beau demain !!!

**Comment by kapeco** [comment]
oui ça a l'air bien sympa en tout cas , faudra bien profiter fiston ;)
c'est papy qui te le dit :p

**Comment by corentin-begne** [comment]
tkt ;)

**Comment by kapeco** [comment]
;)

**Comment by corentin-begne** [comment]
c'est bon ça ?

**Comment by kapeco** [comment]
oui
