### ISSUE TITLE
Temps de session

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#95]
Apparement le temps de session est trop court

L'assistante de mon frère qui reste sur le site toute la journée doit se reconnecter trop régulièrement pour continuer à travailler sur le site , possible d'allonger ça ?

**Comment by corentin-begne** [comment]
j'ai mis un init_set sur 48h, à voir si ça fonctionne sur le mutu

**Comment by kapeco** [comment]
ok on testera 

merci

c'était à combien avant ?

**Comment by corentin-begne** [comment]
je sais pas, fais un phpinfos() tu verras mais je crois que par défaut c'est 1440s = 24mn

**Comment by kapeco** [comment]
ok
