### ISSUE TITLE
Soucis dans titre Agenda

### ISSUE THREAD

**Issue by kapeco** [corentin-begne/kap#96]
Bon y a un souci dans agenda 

j'ai crée un ODM avec un agence test qui s'appel agence franck

et le titre de mon ODM c'est 
Mission diagnostic agence Efficity Julien Lemercier [8 rue boucry 75018 PARIS-18E--ARRONDISSEMENT]

9a serait bien d'avoir dans le titre le nom de la bonne agence , je ne sais pas commence c'ets possible !!!

sinon le titre faudrait que ça soit

Diagnostic [nom du client ] [ ville] pour [nom de l'agence]

**Comment by corentin-begne** [comment]
c'est corrigé et en prod, je changerais le titre plus tard

**Comment by kapeco** [comment]
ok merci

ça venait de quoi l'embrouille ??

**Comment by kapeco** [comment]
Bon toujours pas bon du tout :(
Agnes lombard de Orpi senlis m'a fait un ODM
et ça enregistre l'odm dans l'agenda sous le nom de Pierre Lièvre de Efficity

**Comment by corentin-begne** [comment]
je vais corriger mais c'est juste le titre sur google agenda tout le reste est bon, t'utilises pas google agenda pour faire ta facturation quand même ?
je vais changer le titre et corriger, là en fait j'ai mis le nom de l'agence de celui qui réserve au lieu du nom de l'agence du gars qui a créé l'odm

**Comment by kapeco** [comment]
ben là celui qui réserve c'était moi et je ne m'appel pas Pierre lièvre !
c'est effectivement le nom de l'agence de celui qui crée l'odm qu'il faut mettre

"t'utilises pas google agenda pour faire ta facturation quand même ?" ... oui et non . j'envois la facture à celui qui m'a contacté et si je vois toto et bien je facture à toto, mais si c'est pas toto qui m'envois l'odm alors ça fou le bordel
On à plusieur support pour l'information , le site, le mail, le push et l'agenda, quand onest sur le terrain on doit pouvoir se fier à l'info qu'on voit quelque soit la source, du coup on ne va pas forcément vérifier toutes les sources et comparer. et le support qu'on consulte le plus souvent c'est l'agenda , donc oui on peut s'en servire indirectement pour la facturation. surtout l'employé de mon frère qui ne travail qu'avec ça

**Comment by corentin-begne** [comment]
okok

**Comment by corentin-begne** [comment]
c'est bon c'est corrigé, je te fais une mep comme ça t'auras ça le temps de session

**Comment by corentin-begne** [comment]
yavait une erreur dans la requête aussi pour ça t'avais n'imp

**Comment by corentin-begne** [comment]
c'est en prod !

**Comment by kapeco** [comment]
ah ben si tu fait n'imp maintenant va falloir que tu travails en binome avec PGM ;)
